$(document).ready(function(){    
    $.easy.navigation();
    $.easy.tooltip();
    $.easy.popup();
    $.easy.external();
    $.easy.rotate();
    $.easy.forms();
    $.easy.showhide();
    $.easy.jump();
});