= Instantiation

== PageFactory
Pages need to be created initially via. `PageFactory` interface, which will be provided by the `PageFactoryProvider` as `PAGE_FACTORY` instance.

When the page is instantiated, Testerra automatically checks its annotated elements.

[source,java]
----
HomePage homePage = PAGE_FACTORY.createPage(HomePage.class);

// Or use an explicit WebDriver
HomePage homePage = PAGE_FACTORY.createPage(HomePage.class, WebDriver otherWebDriver);
----

Once you created a page, you can create other pages directly from this page, to keep track of the same WebDriver.

[source,java]
----
OtherPage otherPage = homePage.createPage(OtherPage.class);
----

== Optional pages

You can also try to create a page, when you want to handle unexpected redirects at some point.

[source,java]
----
homePage.waitForPage(OtherPage.class).ifPresent(otherPage -> {});
homePage.waitForPage(OtherPage.class, int seconds).ifPresent(otherPage -> {});
----


== Page Prefixes (*deprecated*)

NOTE: Using page prefixes is an uncommon feature and therefore marked as `@deprecated`

Page Prefixes can influence which concrete classes get instantiated by the `PageFactory`. They work together with a inheritance scheme of page classes. This can be useful if there is a base page which can come in different concrete variations. Example:

There is a `BaseClass` which inherits from the `Page` class and contains the basic functionality of a page.
Then the `Page` can come in 2 different variations.
We can represent this as `Variation1BaseClass` and `Variation2BaseClass`.
They both inherit from `BaseClass`.
Before instantiation, we can set the prefix using the `PageFactory`.
Then we instantiate it and we can get our variation of the base class.
[source,java]
----
PAGE_FACTORY.setGlobalPagesPrefix("Variation1");
//this actualy creates a Variation1BaseClass
BaseClass baseClass = PAGE_FACTORY.createPage(BaseClass.class);
----
Default is no prefix.

Usage:
[source,java]
----
// Set a global Prefix
PAGE_FACTORY.setGlobalPagesPrefix("prefix");

// Set a thread local prefix. See next row about cleaning this prefix.
PAGE_FACTORY.setThreadLocalPagesPrefix("prefix");

// The thread local pages prefix is not cleared automatically,
// be sure to always set the correct one or clear it after using.
PAGE_FACTORY.removeThreadLocalPagePrefix();
----
