= Check Annotations

include::../properties/property-attributes.adoc[]

The `@Check` annotation is used to verify the actual presence of an element on the site.
All UiElements that are marked with the `@Check` annotation are automatically checked when instantiated by the `PageFactory`.

In the example, the first UiElement has the `@Check` annotation, the second doesn't.
The result is, that the presence of the first element will be checked by the constructor, the second won't.
If a checked element is not found, the constructor will throw a `PageFactoryException`.

[source,java]
----
@Check
private UiElement checked = find(By.name("checked"));
//no @Check here
private UiElement unchecked = find(By.name("unchecked"));
----

The `@Check` annotation will use the default `CheckRule` defined in `test.properties`.
It is also possible to overwrite the default `CheckRule` for a single `@Check` annotation.

[source,java]
----
@Check(checkRule = CheckRule.IS_PRESENT)
private UiElement checked = find(By.name("checked"));
----

Change the check rules for the whole project (global) with the following:

.test.properties
[source,properties,subs="attributes"]
----
{guielement_checkrule}=IS_PRESENT
----

Available CheckRules are

* IS_DISPLAYED
* IS_NOT_DISPLAYED
* IS_PRESENT
* IS_NOT_PRESENT

The default is IS_DISPLAYED.

With nonFunctional attribute the check only adds a warning in Testerra report.
The test will not interrupted at this position.

[source,java]
----
@Check(nonFunctional = true)
private UiElement checked = find(By.name("checked"));
----

With following `@Check` annotation you can define a special error message.

[source,java]
----
@Check(prioritizedErrorMessage = "My error message.")
private UiElement checked = find(By.name("checked"));
----
