= Best Practices

== Project setup

=== Normalize file encoding

Always use the same file encoding for all your source file types like `.html`, `.properties`, `.java` etc.

IntelliJ: You can change the default encoding for files at _File -> Settings -> File Encodings_

=== Normalize file endings

Prevent using default line ending `CRLF` on Windows.

Git: Setup `git config --global core.autocrlf input` to prevent any commited CRLF.

== Always prefer Assertions

If you need to check several properties of a GuiElement, always prefer

. <<Assertions>> due to the human-readable and precise description
. over <<Waiters>> because of their fault tolerance
. over <<Checks>>

[source,java]
----
// Good practice
element.asserts().assertText("Search results");

// Bad practice
Assert.assertTrue(element.getText().contains("Search results"));
----


== Always describe your asserts

In that specific case where you can't use `asserts()`,
then use the extended <<Assert Utilities>> to more precise in your statement and pass a proper description text.

[source,java]
----
int actualSearchResultCount = Integer.parseInt(element.getText());

// Good practice
AssertUtils.assertGreaterThan(actualSearchResultCount, 5, "Search results count");

// Bad practice
Assert.assertTrue(actualSearchResultCount > 5);
----
