= Best Practices

This section contains several articles for best practices for the usage and implementation of tests with Testerra.

== Project setup

Project setup recommendations.

=== Normalize file encoding

Always use the same file encoding for all your source file types like `.html`, `.properties`, `.java` etc.

IntelliJ: You can change the default encoding for files at _File -> Settings -> File Encodings_

=== Normalize file endings

Prevent using default line ending `CRLF` on Windows.

Git: Setup `git config --global core.autocrlf input` to prevent any commited CRLF.

== Support multiple profiles

Supporting multiple profiles is useful, for different environments or test suites.

.build.gradle
[source, gradle, role="primary"]
----
test {
    def profiles = [
        "mySuite": "suite.xml"
    ]

    def suiteFiles = []
    profiles.each { k, v ->
        if (project.hasProperty("" + k)) {
            def f = 'src/test/resources/' + v
            suiteFiles << f
        }
    }

    useTestNG() {
        suites(suiteFiles as String[])
    }
}
----

.pom.xml
[source, xml, role="secondary"]
----
<project>
   <profiles>
        <profile>
            <id>mySuite</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skip>false</skip>
                            <suiteXmlFiles>
                                <suiteXmlFile>src/test/resources/suite.xml</suiteXmlFile>
                            </suiteXmlFiles>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
----

.Gradle
[source, bash, role="primary"]
----
gradle test -PmySuite
----
.Maven
[source, bash, role="secondary"]
----
mvn test -PmySuite
----

== Quality Assurance Attributes

As we know, things changing all the time. And in the context of a website, it may also change in several ways

* Layout
* Design
* Features

=== Problem

The features of a website are covered by functional tests based on GuiElements. But GuiElements are using identifiers based
on the Document Object Model (DOM) of the website. The DOM is based on HTML elements and can vary between static and highly dynamic.
That means, if the layout or design changes, the DOM may also change and in consequence also the identifiers of the GuiElements which affects the functionality of the tests.

WARNING: Tests covering features may break if the layout or design changes.

_Layout Change_ -> _DOM Change_ -> _Identifier Change_ -> _GuiElement not working as expected_

Changing identifiers carry the following additional risks:

- _False Negative_: Tests failing, even if the feature is not broken
- _Sisyphus work_: Test engineers must consistently update the identifiers
- _No coverage_: The features and the tests are mostly out of sync.

=== Solution

To prevent these risks above, it's a good practice to introduce a more stable form of identifiers based on the non-standard HTML `@data-qa` attribute.

* These attributes are stable and don't change, even if the DOM changes.
* It enhances the DOM with more semantic features.
* They don't affected any other attributes like `@id` or `@class`.
* They are independet of the underlaying framework like Bootstrap, Angular or whatsoever.
* They can be easily removed in Live environments.

NOTE: Developers should integrate these attributes in their HTML code.

=== Recommendation

We recommend a syntax, there the `@data-qa` tag contains 3 parts separated by slash (/) to describe it's behaviour.

`data-qa="[type]/[name]/[id?]"`

Where `name` and `id` are free to define, `type` is not and should be one of these semantic types.

==== Semantics

[cols="1,2,4a"]
|===
| Prefix | Description | Examples
| section | Non-interactive area with content
| [source, html]
----
<article data-qa="section/article">
----
| input | Interactive input elements
|
[source, html]
----
<input data-qa="input/searchQuery"/>
----
| action | Interative elements that performs an action
|
[source, html]
----
<button data-qa="action/login">Login</button>
<a href="https://google.com" data-qa="action/gotoGoogle">Search at Google</a>
----
|===

==== Example

[source, html]
----
<ul>
    <li data-qa="section/animal/ape">
        <h1 data-qa="section/headline">Ape</h1>
        <p data-qa="section/description">Hairy and Goofy</p>
        <button data-qa="action/gotoDetails">Details</button>
    </li>
</ul>
----


== Always prefer Assertions

If you need to check several properties of a GuiElement, always prefer

. <<Assertions>> due to the human-readable and precise description
. over <<Waiters>> because of their fault tolerance
. over <<Checks>>

[source,java]
----
// Good practice
element.asserts().assertText("Search results");

// Bad practice
Assert.assertTrue(element.getText().contains("Search results"));
----


== Always describe your asserts

In that specific case where you can't use `asserts()`,
then use the extended <<Assert Utilities>> to more precise in your statement and pass a proper description text.

[source,java]
----
int actualSearchResultCount = Integer.parseInt(element.getText());

// Good practice
AssertUtils.assertGreaterThan(actualSearchResultCount, 5, "Search results count");

// Bad practice
Assert.assertTrue(actualSearchResultCount > 5);
----
