= Changes

== New API

=== Pages instantiation

The new standard way to instantiate Pages is now
```java
class MyTest extends TesterraTest {
    @Test
    public void test_MyPageTest() {
        MyPage page = pageFactory.create(MyPage.class);

        // Or with different WebDriver
        MyPage page = pageFactory.create(MyPage.class, WebDriverManager.getWebDriver());
    }
}
```
[NOTE]
.Using the static `PageFactory` is `@deprecated`
====
```java
MyPage page = PageFactory.create(MyPage.class, WebDriverManager.getWebDriver());
```
====

[CAUTION]
.Constructor instantiation of Pages is forbidden!
====
```java
MyPage page = new MyPage(WebDriverManager.getWebDriver());
```
====

=== Implicit Element checks

The standard way of implicit GuiElement checks is now
```java
class MyPage extends Page {
    @Check
    private IGuiElement guiElement = findById(42);
}
```

[CAUTION]
.Performing explicit page checks is forbidden!
====
```java
class MyPage extends Page {
    public MyPage(WebDriver webDriver) {
        super(webDriver);
        checkPage(); <1>
    }
}
```
<1> Calling `checkPage()` as `protected` member is forbidden
```java
MyPage page = pageFactory.create(MyPage.class);
page.checkPage(); <2>
```
<2> Calling `checkPage()` as `public` member is forbidden
====

=== Element instantiation

The new standard way to instantiate GuiElements is now
```java
class MyPage extends Page {
    private IGuiElement guiElement = findById(42);
    private IGuiElement guiElement = find(By.xpath("//div[1]"));
}
```

[NOTE]
.Constructor instantiation of GuiElements is now `@deprecated`
====
```java
class MyPage extends Page {
    private GuiElement guiElement = new GuiElement(By.id(42), driver);
    private GuiElement guiElement = new GuiElement(By.xpath("//div[1]"), driver);
}
```
====

For sub elements
```java
class MyPage extends Page {
    private IGuiElement guiElement = findById(42);
    private IGuiElement subElement = withAncestor(guiElement).find(By.xpath("//div[1]"));
}
```

[NOTE]
.Retrieving sub elements from GuiElement is now `@deprecated`
====
```java
class MyPage extends Page {
    private GuiElement guiElement = new GuiElement(By.id(42), driver);
    private GuiElement subElement = guiElement.getSubElement(By.xpath("//div[1]"));
}
```
====

For elements in frames
```java
class MyPage extends Page {
    private IGuiElement frame = find(By.tagName("frame"));
    private IGuiElement guiElement = inFrame(frame).findById(14);
}
```

[NOTE]
.Passing frames to the constructor is now `@deprecated`
====
```java
class MyPage extends Page {
    private GuiElement frame = new GuiElement(By.tagName("frame"), driver);
    private GuiElement guiElement = new GuiElement(By.id(14), driver, frame);
}
```
====

=== Assertions

The new standard way for performing assertions is now
```java
Assert.assertTrue(false);
```

=== Collected Assertions

The new standard way to collect assertions of GuiElements is now
```java
collectAssertions(() -> guiElement.displayed().isTrue());
```

For many GuiElements or Pages
```java
collectAssertions(() -> {
    MyPage page = pageFactory.create(MyPage.class);
    page.title().is("TestPage");

    page.element().value().contains("Hello");
});
```

For custom assertions
```java
collectAssertions(() -> {
    String data = loadSomeData();
    Assert.assertEquals(data, "Hello World", "some data");
});
```

For other test methods
```java
@Test
public void test_CollectEverything() {
    collectAssertions(() -> test_TestSomething());
}
```

[NOTE]
.Using the static `AssertCollector` is now `@deprecated`
====
```java
AssertCollector.assertTrue(false);
```
====

[NOTE]
.Using the GuiElement's assert collector is now `@deprecated`
====
```java
guiElement.assertCollector().assertIsDisplayed();
```
====

[NOTE]
.Forcing standard assertions is now `@deprecated`
====
```java
page.forceGuiElementStandardAsserts();
```
====

[NOTE]
.Setting collected assertions by default is now `@deprecated`
====
```properties
tt.guielement.default.assertcollector=true
```
====

=== Non Functional Assertions

The new standard way for non functional assertions works like <<Collected Assertions>>
```java
nonFunctional(() -> guiElement.displayed().isTrue());
```

[NOTE]
.Using the static `NonFunctionalAssert` is now `@deprecated`
====
```java
NonFunctionalAssert.assertTrue(false);
```
====

[NOTE]
.Using the GuiElement's non functional asserts are now `@deprecated`
====
```java
guiElement.nonFunctionalAsserts().assertIsDisplayed();
```
====

=== Timeouts

The new standard way for setting GuiElement timeouts is now

```java
withElementTimeout(1, () -> guiElement.displayed().isTrue());
```

For many GuiElements or Pages
```java
withElementTimeout(1, () -> {
    MyPage page = pageFactory.create(MyPage.class);
    page.title().is("TestPage");

    page.element().value().contains("Hello");
});
```

For the whole Page
```java
@PageOptions(elementTimeoutInSeconds = 1)
class MyPage extends Page {
}
```

For other test methods
```java
@Test
public void test_TestSomething_fast() {
    withElementTimeout(1, () -> test_TestSomething());
}
```

[NOTE]
.Setting explicit timeouts on the Page is now `@deprecated`
====
```java
page.setElementTimeoutInSeconds(1);
```
====

[NOTE]
.Setting and restoring explicit timeouts on the GuiElement is now `@deprecated`
====
```java
guiElement.setTimeoutInSeconds(1);
guiElement.restoreDefaultTimeout();
```
====

[NOTE]
.Setting timeouts using static `POConfig` is now `@deprecated`
====
```java
POConfig.setThreadLocalUiElementTimeoutInSeconds(1);
POConfig.setUiElementTimeoutInSeconds(1);
```
====

=== Sub Pages
The new standard way to implement Sub Pages aka Components is
```java
public class MyForm extends Component {
    public MyForm(IGuiElement rootElement) {
        super(rootElement);
    }
}
```
Instantiate components
```java
class MyPage extends Page {
    private MyForm form = withAncestor(find(By.tagName("form"))).createComponent(MyForm.class);
}
```



