= Create a new project
include::properties/property-attributes.adoc[]

== System requirements

* Testerra is based on Java. You need a *JDK 8* or later.
* Execute your tests with *Maven* or *Gradle*

== Mandatory steps

=== Testerra setup

The Testerra framework is deployed to https://bintray.com/bintray/jcenter.

For Testerra you need at least the following dependencies for Gradle or Maven.

.build.gradle
[source, gradle, role="primary"]
----
apply plugin: 'java'

// Its highly recommended to normalize your project to Unicode
compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = "UTF-8"

dependencies {
    compile 'eu.tsystems.mms.tic.testerra:driver-ui-desktop:1-SNAPSHOT'
}
----

.pom.xml
[source, xml, role="secondary"]
----
<project>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <!-- Its highly recommended to normalize your project to Unicode -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>eu.tsystems.mms.tic.testerra</groupId>
            <artifactId>driver-ui-desktop</artifactId>
            <version>1-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
----

=== Create project structure

Your project structure should comply with these simple constraints.

* `src/main` Contains all the code for your project like <<PageObjects>>, Models and language specific resources.
* `src/test` Contains all test related code like your Tests, Test-Suites, Test-Data and Testerra related setup.

=== Create test.properties

Create a new file at `src/test/resources` with the name `test.properties`.

.test.properties
[source, properties, subs="attributes"]
----
// Setting the browser
{browser}=firefox

// Setting the start page
{baseurl}=http://example.org
----

TIP: All defined properties can be overwritten later by adding system parameters to your command +
 (e.a `-D{browser}=chrome`)

All supported browsers are listed in <<WebdriverManager properties>>

=== Create Page Class

Now its time to create a first simple page class. It should be saved at path `src\main\java\<package>`. The following example represents the website example.org. It contains one possible link to click and one method to test.

.New page class
[source, java]
----
import eu.tsystems.mms.tic.testframework.pageobjects.Page;

public class ExamplePage extends Page {

    @Check
    private GuiElement moreInformationLink = new GuiElement(driver, By.partialLinkText("More information"));

    public ExamplePage(WebDriver driver) {
        super(driver);
    }

    public void clickOnMoreInformation() {
        moreInformationLink.click();
    }
}
----

[TIP]
======
The basic Page class added all the page object functionality of Testerra to your project. See <<PageObjects>> chapter for more details.

The GuiElement describes the elements like links, buttons, etc. on your page. Learn more about GuiElements in <<GuiElements>>.
======

=== Create Test Class and Test Method

The easiest way to create a new test, is by creating a new class in the path of `src\test\java\<package>` and let it extend from `TesterraTest`. If you already have test classes that extend, you can add the `TesterraListener` manually. Both ways do basically the same.
To stick to the example above, here is a very simple test class which navigates to example.org and clicks on the link defined on the example page. Again, probably imports must be made in IDE.

.TesterraTest
[source, java, role="primary"]
----
import eu.tsystems.mms.tic.testframework.testing.TesterraTest;

public class ExampleTest extends TesterraTest {

    @Test
    public void testT01_My_first_test() {
        WebDriver driver = WebDriverManager.getWebDriver();
        ExamplePage examplePage = PageFactory.create(ExamplePage.class, driver);
        examplePage.clickOnMoreInformation();
    }
}
----

.TesterraListener
[source, java, role="secondary"]
----
import eu.tsystems.mms.tic.testframework.report.TesterraListener;
import org.testng.annotations.Listeners;

@Listeners(TesterraListener.class)
public class ExampleTest {
}
----

=== Setup Selenium

If you don't have a remote selenium yet, you can easily install it by the package manager of your choice.

.https://chocolatey.org[chocolately] for Windows (recommended)
[source, cmd]
----
choco install selenium selenium-chrome-driver
----

Read here, if you want to setup <<WebDriver sessions,another Selenium configuration>>.

=== Setup a test suite

To customize the executing of your tests, you have to create a TestNG suite file `suite.xml` and locate it at `src/test/resources`

.suite.xml
[source, xml]
----
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Suite1" verbose="1" thread-count="10" configfailurepolicy="continue" parallel="false">
    <test name="Test1" parallel="methods">
        <classes>
            <class name="ExampleTest"/>
        </classes>
    </test>
</suite>
----

=== Setup test build target

In order to get tests to work, you need to setup a build target `test` in your project.

.build.gradle
[source, gradle, role="primary"]
----
test {
    useTestNG() {
        suites file('src/test/resources/suite.xml')
    }

    testLogging {
        outputs.upToDateWhen { false }
        showStandardStreams = true
    }

    // Important: Forward all JVM properties like proxy settings to TestNG
    options {
        systemProperties(System.getProperties())
    }

    // basically execution returns "GREEN" (framework exits with exit code > 0 if there were failures)
    ignoreFailures = true
}
----

.pom.xml
[source, xml, role="secondary"]
----
<project>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>mySuite</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skip>false</skip>
                            <suiteXmlFiles>
                                <suiteXmlFile>src/test/resources/suite.xml</suiteXmlFile>
                            </suiteXmlFiles>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
----

=== Run the tests
Finally you are good to run your very first test by entering the following command:

.Gradle
[source, bash, role="primary"]
----
gradle test
----

.Maven
[source, bash, role="secondary"]
----
mvn test
----

=== Testerra Report

The Testerra test report is automatically generated and can be found at `<project>/testerra-report/index.html`.


== Project extensions

=== Using a proxy

There are three ways for setting up a proxy for your test run environment.

- System proxy settings for Gradle and the JVM
- Testerra proxy settings for TestNG and JVM
- Browser proxy settings for the SUT set up by browser capabilities you can find here <<Browser capabilities,Proxy setup>>

==== System proxy (recommended)

To setup a proxy for the whole system, including Gradle, the JVM and Testerra, the recommended way is to pass it by command line arguments like
[source]
----
gradle test -Dhttps.proxyHost=your-proxy-host.com -Dhttps.proxyPort=8080
----
IMPORTANT: Setting the System proxy will override the Testerra proxy settings.

==== Testerra proxy

If you want to setup a proxy for Testerra, including TestNG and the JVM, just add `proxysettings.properties` to your resource bundle at `src/test/resources` with the following content

For example Testerra requires this setting to connect to a Selenium grid, if you are in a corporate network.

.Example of proxysettings.properties
[source,properties]
----
https.proxyHost=your-proxy-host.com
https.proxyPort=8080
https.proxyUser=
https.proxyPassword=
https.nonProxyHosts=localhost|192.168.0.1
----
These properties are automatically loaded by the `PropertyManager` and set up as System proxy settings during runtime with the following message
----
[main] [INFO ]: common.TesterraCommons - Setting system property proxy = http://your-proxy-host.com:8080
----

IMPORTANT: Setting up the Testerra proxy will not setup a proxy for Gradle nor a browser.

=== Customize Logging

The `TesterraLogger` logs to `System.out` by default.
If you want to have more control over several log levels of classes, add a `log4j.xml` to your `resources/`.

.log4j.xml
[source, xml]
----
include::../res/log4j.xml[]
----
