= UiElements

== Overview

UiElements are representations of elements of the tested website, like buttons, search fields, checkboxes or even just DOM elements.

UiElements are not, but based on the *Selenium WebElement* and add more functionality to them. Since a UiElement is just a pointer to a locator, it's using the same definition as WebElements `By` (https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/By.html[Selenium docs]).

UiElements are *self refreshing*: Every action on it will trigger a find call, so the current state is always up to date when the requested action takes place. There is de facto *no StaleElementReferenceException* on UiElements like it could be when using vanilla WebElements.

include::guielement/guielement-creation.adoc[leveloffset=+1]
include::guielement/xpath-builder.adoc[leveloffset=+1]
include::guielement/guielement-assertions.adoc[leveloffset=+1]
include::guielement/guielement-actions.adoc[leveloffset=+1]
include::guielement/guielement-waiters.adoc[leveloffset=+1]
include::guielement/guielement-properties.adoc[leveloffset=+1]

== Internals

The `find` mechanism for a `UiElement` in Testerra works different as in plain Selenium.
When using a constructor for a `UiElement` instantiation, Testerra internally will add some facades / decorators to make things easier.
The most important decorator that is added by default is the `GuiElementCoreSequenceDecorator` -which adds a sequence to all method calls against a `GuiElement`.

Example: When calling the `isPresent()` method on a `UiElement` the added `GuiElementSequenceDecorator` will fire up an internal `find()` call to the `GuiElement` and therefore a `find()` call to the underlying Selenium `WebElement`.
But instead of calling the `find()` method once, it will execute this call in a default sequence every 500ms.

Therefor the property {element_timeout_seconds} defined in `test.properties` will be used as a *hard* timeout for this sequence.
If the `find()` does not run successfully after the defined timeout it will fail.
