= Known issues

Because we depend on other frameworks and tools like TestNG and Selenium we may encounter issues that we want to fix, but are bound to releases and fixes in our dependencies.

Every known issue in our dependencies that will lead to an error, an unexpected or unsightly behaviour in Testerra framework will be documented here, as well as a solution or a workaround.

== Issues with Selenium

=== Closing `WebDriver` sessions without using Testerra `WebDriverManager`

When closing `WebDriver` sessions without using Testerra <<WebDriverManager>> you will may encounter problems or some kind of unexpected issues, because the session is not marked as closed in Testerra `WebDriverManager` session store.
Therefore we always suggest to use `WebDriverManager.shutdown()` instead of `WebDriverManager.getWebDriver().close()`.

== Issues with TestNG

=== RetryAnalyzer not set properly with Data Provider

|===
|Description| Currently the default RetryAnalyzer of Testerra is not set properly on TestNGs underlying method objects when using the TestNG  `@DataProvider`- or `@Parameters`-annotation.
|Result| Methods that are annotated with `@DataProvider` or `@Parameters` will not be retried if they are failed,  `{failed_tests_max_retries}` is set to 1 or higher and a matching retry cause was found.

|Issue valid in TestNG| 7.1.1
|Issue Link TestNG| https://github.com/cbeust/testng/issues/2267[GitHub]
|===



