// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.tap.model.framework;

/**
 * Protobuf type {@code data.ContextClip}
 */
public  final class ContextClip extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ContextClip)
    ContextClipOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContextClip.newBuilder() to construct.
  private ContextClip(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContextClip() {
    key_ = "";
    methodContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContextClip();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ContextClip(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              methodContextIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            methodContextIds_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        methodContextIds_ = methodContextIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.tsystems.mms.tic.tap.model.framework.Framework.internal_static_data_ContextClip_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.tsystems.mms.tic.tap.model.framework.Framework.internal_static_data_ContextClip_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.tsystems.mms.tic.tap.model.framework.ContextClip.class, eu.tsystems.mms.tic.tap.model.framework.ContextClip.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object key_;
  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_CONTEXT_IDS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList methodContextIds_;
  /**
   * <code>repeated string method_context_ids = 2;</code>
   * @return A list containing the methodContextIds.
   */
  public com.google.protobuf.ProtocolStringList
      getMethodContextIdsList() {
    return methodContextIds_;
  }
  /**
   * <code>repeated string method_context_ids = 2;</code>
   * @return The count of methodContextIds.
   */
  public int getMethodContextIdsCount() {
    return methodContextIds_.size();
  }
  /**
   * <code>repeated string method_context_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The methodContextIds at the given index.
   */
  public java.lang.String getMethodContextIds(int index) {
    return methodContextIds_.get(index);
  }
  /**
   * <code>repeated string method_context_ids = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the methodContextIds at the given index.
   */
  public com.google.protobuf.ByteString
      getMethodContextIdsBytes(int index) {
    return methodContextIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
    }
    for (int i = 0; i < methodContextIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodContextIds_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < methodContextIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(methodContextIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMethodContextIdsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.tsystems.mms.tic.tap.model.framework.ContextClip)) {
      return super.equals(obj);
    }
    eu.tsystems.mms.tic.tap.model.framework.ContextClip other = (eu.tsystems.mms.tic.tap.model.framework.ContextClip) obj;

    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getMethodContextIdsList()
        .equals(other.getMethodContextIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (getMethodContextIdsCount() > 0) {
      hash = (37 * hash) + METHOD_CONTEXT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getMethodContextIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.tsystems.mms.tic.tap.model.framework.ContextClip prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code data.ContextClip}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ContextClip)
      eu.tsystems.mms.tic.tap.model.framework.ContextClipOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.tsystems.mms.tic.tap.model.framework.Framework.internal_static_data_ContextClip_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.tsystems.mms.tic.tap.model.framework.Framework.internal_static_data_ContextClip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.tsystems.mms.tic.tap.model.framework.ContextClip.class, eu.tsystems.mms.tic.tap.model.framework.ContextClip.Builder.class);
    }

    // Construct using eu.tsystems.mms.tic.tap.model.framework.ContextClip.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      key_ = "";

      methodContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.tsystems.mms.tic.tap.model.framework.Framework.internal_static_data_ContextClip_descriptor;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.tap.model.framework.ContextClip getDefaultInstanceForType() {
      return eu.tsystems.mms.tic.tap.model.framework.ContextClip.getDefaultInstance();
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.tap.model.framework.ContextClip build() {
      eu.tsystems.mms.tic.tap.model.framework.ContextClip result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.tap.model.framework.ContextClip buildPartial() {
      eu.tsystems.mms.tic.tap.model.framework.ContextClip result = new eu.tsystems.mms.tic.tap.model.framework.ContextClip(this);
      int from_bitField0_ = bitField0_;
      result.key_ = key_;
      if (((bitField0_ & 0x00000001) != 0)) {
        methodContextIds_ = methodContextIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.methodContextIds_ = methodContextIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.tsystems.mms.tic.tap.model.framework.ContextClip) {
        return mergeFrom((eu.tsystems.mms.tic.tap.model.framework.ContextClip)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.tsystems.mms.tic.tap.model.framework.ContextClip other) {
      if (other == eu.tsystems.mms.tic.tap.model.framework.ContextClip.getDefaultInstance()) return this;
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      if (!other.methodContextIds_.isEmpty()) {
        if (methodContextIds_.isEmpty()) {
          methodContextIds_ = other.methodContextIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMethodContextIdsIsMutable();
          methodContextIds_.addAll(other.methodContextIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.tsystems.mms.tic.tap.model.framework.ContextClip parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.tsystems.mms.tic.tap.model.framework.ContextClip) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList methodContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMethodContextIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        methodContextIds_ = new com.google.protobuf.LazyStringArrayList(methodContextIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @return A list containing the methodContextIds.
     */
    public com.google.protobuf.ProtocolStringList
        getMethodContextIdsList() {
      return methodContextIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @return The count of methodContextIds.
     */
    public int getMethodContextIdsCount() {
      return methodContextIds_.size();
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The methodContextIds at the given index.
     */
    public java.lang.String getMethodContextIds(int index) {
      return methodContextIds_.get(index);
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the methodContextIds at the given index.
     */
    public com.google.protobuf.ByteString
        getMethodContextIdsBytes(int index) {
      return methodContextIds_.getByteString(index);
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @param index The index to set the value at.
     * @param value The methodContextIds to set.
     * @return This builder for chaining.
     */
    public Builder setMethodContextIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodContextIdsIsMutable();
      methodContextIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @param value The methodContextIds to add.
     * @return This builder for chaining.
     */
    public Builder addMethodContextIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodContextIdsIsMutable();
      methodContextIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @param values The methodContextIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllMethodContextIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureMethodContextIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, methodContextIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodContextIds() {
      methodContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string method_context_ids = 2;</code>
     * @param value The bytes of the methodContextIds to add.
     * @return This builder for chaining.
     */
    public Builder addMethodContextIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMethodContextIdsIsMutable();
      methodContextIds_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ContextClip)
  }

  // @@protoc_insertion_point(class_scope:data.ContextClip)
  private static final eu.tsystems.mms.tic.tap.model.framework.ContextClip DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.tsystems.mms.tic.tap.model.framework.ContextClip();
  }

  public static eu.tsystems.mms.tic.tap.model.framework.ContextClip getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContextClip>
      PARSER = new com.google.protobuf.AbstractParser<ContextClip>() {
    @java.lang.Override
    public ContextClip parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ContextClip(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ContextClip> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContextClip> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.tsystems.mms.tic.tap.model.framework.ContextClip getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

