= BrowserUp Proxy

https://github.com/browserup/browserup-proxy[BrowserUp Proxy (BUP)] is a simple HTTP proxy utility developed by https://browserup.com[browserup.com].
It offers functionality to track, manipulate and modify HTTP requests and responses, as well as capture HTTP traffic for analysis.

Testerra offers a simple integration to spin multiple local proxy servers or manage remote proxy servers via HTTP API.

== Project setup

.build.gradle
[source,groovy,role="primary",subs="attributes"]
----
compile 'io.testerra:bup:{revnumber}'
----

.pom.xml
[source,xml,role="secondary",subs="attributes+"]
----
<dependencies>
    <dependency>
        <groupId>io.testerra</groupId>
        <artifactId>bup</artifactId>
        <version>{revnumber}</version>
    </dependency>
</dependencies>
----

== External Proxy Server

Best practice for using a Testerra with an external proxy, is to use a dedicated BrowserUp Instance. To start these instance, please have a further read on the BrowserUp documentation.

To handle remote a BrowserUp proxy instance Testerra provides a simple REST client (see also https://github.com/browserup/browserup-proxy#rest-api).

[source,java]
----
import eu.tsystems.mms.tic.testerra.bup.BrowserUpRemoteProxyManager;
import eu.tsystems.mms.tic.testerra.bup.BrowserUpRemoteProxyServer;
import eu.tsystems.mms.tic.testframework.testing.TesterraTest;
import org.openqa.selenium.Proxy;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;

import java.net.MalformedURLException;
import java.net.URL;

public class AbstractTest extends TesterraTest {

    private static BrowserUpRemoteProxyServer bupProxy = new BrowserUpRemoteProxyServer();

    @BeforeSuite
    public void setupProxy() throws MalformedURLException {
        URL apiUrl = new URL("http://localhost:8080");
        BrowserUpRemoteProxyManager bupRemoteProxyManager = new BrowserUpRemoteProxyManager(apiUrl);
        bupProxybupRemoteProxyManager.startServer(bupProxy);

        /* Additional Proxy setup here */
        String bmpProxyAddress = String.format("%s:%d", apiUrl.getHost(), bupProxy.getPort());

        // For selenium usage.
        Proxy proxy = new Proxy();
        proxy.setHttpProxy(bmpProxyAddress).setSslProxy(bmpProxyAddress);

        WebDriverManager.setGlobalExtraCapability(CapabilityType.PROXY, proxy);
    }

    @AfterSuite
    public void tearDownProxy() throws MalformedURLException {

        URL apiBaseUrl = new URL("http://localhost:8080");
        BrowserUpRemoteProxyManager browserUpRemoteProxyManager = new BrowserUpRemoteProxyManager(apiBaseUrl);

        for (Integer proxyPort : browserUpRemoteProxyManager.getProxies()) {
            BrowserUpRemoteProxyServer bupToStop = new BrowserUpRemoteProxyServer();
            bupToStop.setPort(proxyPort);
            browserUpRemoteProxyManager.stopServer(bupToStop);
        }
    }
}
----

BrowserUp creates a new proxy server at the next free port beginning with port 8081 (BrowserUp default).

If you need a dedicated port, use `startServer(BrowserUpRemoteProxyServer proxyServer)` method the following way.

[source,java]
----
BrowserUpRemoteProxyServer browserUpRemoteProxyServer = new BrowserUpRemoteProxyServer();
browserUpRemoteProxyServer.setPort(8088);

browserUpRemoteProxyManager.startServer(browserUpRemoteProxyServer);
----

If the port already used, the `BrowserUpRemoteProxyManager` will do nothing, and just return the given config-object of type `BrowserUpRemoteProxyServer`.

=== Basic Auth

If your SUT is protected by HTTP basic auth, you can set up these credentials as following.

[source,java]
----
URL baseUrl = new URL(PropertyManager.getProperty("tt.baseurl"));
String basicAuthUser;
String basicAuthPassword;

URL apiBaseUrl = new URL(LOCAL_PROXY_FOR_TEST);
BrowserUpRemoteProxyManager browserUpRemoteProxyManager = new BrowserUpRemoteProxyManager(apiBaseUrl);
BrowserUpRemoteProxyServer bup1 = new BrowserUpRemoteProxyServer();
browserUpRemoteProxyManager.startServer(bup1);

browserUpRemoteProxyManager.setBasicAuth(bup1, baseUrl.getHost(), basicAuthUser, basicAuthPassword);
----

=== Upstream proxy

If you need to use a proxy to reach your SUT, you can set up BrowserUp proxy instance to use an upstream proxy.

[source,java]
----
BrowserUpRemoteProxyServer bup1 = new BrowserUpRemoteProxyServer();
bup1.setUpstreamProxy(ProxyUtils.getSystemHttpProxyUrl());

// Setup non-proxy for your upstream proxy, if needed
bup1.setUpstreamNonProxy(".internal.example.org|.mystuff.example.org");

BrowserUpRemoteProxyManager browserUpRemoteProxyManager = new BrowserUpRemoteProxyManager(apiBaseUrl);
browserUpRemoteProxyManager.startServer(bup1);
----

NOTE: User info like `username:password` is supported in your upstream proxy URL.

=== Setup bind address

If running BrowserUp Proxy in a multi-homed environment, you can specify a desired server bind address.

[source,java]
----
BrowserUpRemoteProxyServer bup1 = new BrowserUpRemoteProxyServer();

// Setup a bind address, default is '0.0.0.0'
bup1.setBindAddress("192.168.100.1");

BrowserUpRemoteProxyManager browserUpRemoteProxyManager = new BrowserUpRemoteProxyManager(apiBaseUrl);
browserUpRemoteProxyManager.startServer(bup1);
----

=== Other features

[source,java]
----
/*
 Check if proxy alread runs on port...
 */
BrowserUpRemoteProxyManager browserUpRemoteProxyManager = new BrowserUpRemoteProxyManager(apiBaseUrl);

BrowserUpRemoteProxyServer bup1 = new BrowserUpRemoteProxyServer();
bup1.setPort(8088);

browserUpRemoteProxyManager.startServer(bup1);
boolean isRunning = browserUpRemoteProxyManager.isRunning(nup1);

/*
 Maps specific host names to another host names or IP adresses
 */
browserUpRemoteProxyManager.setHostMapping(BrowserUpRemoteProxyServer proxyServer, Map<String, String> hostMap);

/*
 Capture the traffic and return it as a JsonElement
 You can choose, if you want to capture only the headers, the content or both via the boolean flags.
 */
browserUpRemoteProxyManager.startCapture(
    BrowserUpRemoteProxyServer proxyServer,
    String initialPageRef,
    boolean isCaptureHeaders,
    boolean isCaptureContent
);
JsonElement stopCapture(BrowserUpRemoteProxyServer proxyServer);

/*
 Adds additional key-value pairs to the headers.
*/
browserUpRemoteProxyManager.addHeader(BrowserUpRemoteProxyServer proxyServer, String key, String value);
----

== Local browser instances

If you want to quickly spin up a proxy isntance on your local system while testing, you can use the `BrowserUpLocalProxyManager`.

[source,java]
----
List<Integer> portPool = new ArrayList<>();
ports.add(8090);
ports.add(8091);
ports.add(8092);
ports.add(8093);
ports.add(8094);
ports.add(8095);

BrowserUpLocalProxyManager bupLocalManager = new BrowserUpLocalProxyManager(ports);

// Start instance
BrowserUpProxyServer browserUpProxyServer = new BrowserUpProxyServer();
bupLocalManager.startServer(browserUpProxyServer);

// assert that a port of given port pool was used.
Assert.assertTrue(portPool.contains(port), "Port of range was used.");

// assert proxy is started.
Assert.assertTrue(bup1.isStarted(), "Proxy started");

----

The local proxy manager works with a defined port pool, which has to be declared on instantiation of the manager class.
This port pool will be used to spin up multiple proxy servers for a multi threading test execution.

The port pool has to be declared by yourself, respectively your code, because, only you can know which ports are currently free to use on your local test execution machine.

To use upstream proxies, add headers or do other things on the local proxy server, please take a closer look on https://github.com/browserup/browserup-proxy[BrowserUp] documentation.
