= Connectors

include::../properties/property-attributes.adoc[]

While using the framework some external connectors could be useful.
The maintainers provide some of them in separate repositories.
Please take a look at the following list if there is a connector mapping your need.

[cols="2,5a",options="header"]
|===
| Name | Description
// | Ai4test Connector | https://github.com/telekom/testerra-ai4test-connector/[GitHub] | Experimental AI augmented testing for Testerra
| https://github.com/telekom/testerra-appium-connector[Appium Connector] | Uses the open source standard Appium to run web tests based on Testerra on mobile devices. +
image:https://img.shields.io/maven-central/v/io.testerra/appium?label=Latest%20release[Maven Central]
| https://github.com/telekom/testerra-azure-devops-connector[Azure DevOps Connector]  |
Automatic test result synchronization for Microsoft AzureDevOps platform. +
image:https://img.shields.io/maven-central/v/io.testerra/azure-devops-connector?label=Latest%20release[Maven Central]
| https://github.com/telekom/testerra-cucumber-connector[Cucumber Connector] | Provides the opportunity to use Cucumber and Gherkin to specify `.feature` files and combine it with the advantages of Testerra. +
image:https://img.shields.io/maven-central/v/io.testerra/cucumber-connector?label=Latest%20release[Maven Central]
| https://github.com/telekom/testerra-hpqc-connector[HPQC Connector] | Automatic test result synchronization to HP Application Lifecycle Management, former called HP QualityCenter. +
image:https://img.shields.io/maven-central/v/io.testerra/qc11-connector?label=Latest%20release[Maven Central]
| https://github.com/telekom/testerra-selenoid-connector[Selenoid Connector] | Using a Selenium Grid based on https://github.com/aerokube/selenoid[Selenoid] this module provides access to videos and VNC streams. +
image:https://img.shields.io/maven-central/v/io.testerra/selenoid-connector?label=Latest%20release[Maven Central]
| https://github.com/telekom/testerra-teamcity-connector[TeamCity Connector] | A simple notification service for Jetbrains TeamCity. +
image:https://img.shields.io/maven-central/v/io.testerra/teamcity-connector?label=Latest%20release[Maven Central]
| https://github.com/telekom/testerra-xray-connector[Xray Connector] | Automatic test result synchronization Jira XRay. +
image:https://img.shields.io/maven-central/v/io.testerra/xray-connector?label=Latest%20release[Maven Central]
|===
