= Layout Check

Layout tests always mean checking whether a GUI is designed according to the guidelines.

== Introduction

Are the position, size, color and shape of the elements correct? Are distances maintained? Perhaps even certain elements are missing? In test automation, functionality is primarily tested. Here it is actually irrelevant how a button is designed and where it is positioned. The main thing is that the element can be uniquely recognized via XPath or CSS selectors.

However, in some frontends such as content management systems with a high level of relevance to end users (certain portal solutions, shops) the management is also extremely important. However, testing this with Selenium's previous means is not in any relation between effort and benefit. Manual visual inspection is usually still the fastest way to do this.

Although, manual inspection can never be pixel-accurate. An inspection of perhaps more than 100 elements is too costly. Smaller shifts or colour deviations are easily overlooked.

At this point an automatic comparison of reference screenshots can help. This test is to be seen in addition to the functional tests, but cannot replace them. In a test case, it would also be conceivable to combine the check of function and layout.

== Description

A layout test with the Testerra utilities is actually a comparison between a reference and the actual state. This is done via the screenshot functionality of Selenium, in which both screenshots (reference and actual) are compared pixel by pixel from top to bottom. In this comparison, a third image is created in which differences (ReferencePixel != ActualPixel) are marked in red.
The LayoutCheck can perform a check in two ways:

- PIXEL: Pixel-based image comparison of the entire reference image without exception. You get a quantified value for pixel displacement in percent (0-100%)
- ANNOTATED: The image comparison is based on annotations in the reference image. The annotations are rectangles in a certain color, which include the areas to be checked. You get a quantified value for displaced annotations in percent.

=== Prerequisites
The following prerequisites must be met

. Concrete execution environment: Layout tests should run in a concrete browser environment to ensure the comparability of the screenshots.
** Size of browser window: Define fixed size to exclude different sizes of the images at different VM resolutions
** Screen resolution and scaling: Make sure you have the same screen resolution and scaling on each presentation device (ea. {taf} uses a resolution of {default_resolution} with a scaling of 1 per default in headless environments)
. Build Server: The library underlying ANNOTATED mode supports the operating systems
** Windows 32 - and 64 - Bit
** Linux Debian 32 - and 64 - Bit (glibc >= 2.15; Jenkins)
** MacOSX (untested)

== Configuration

In order to get the layout check to work, you need at least a reference image and a place where it's located.

.test.properties
[source, properties, subs="attributes"]
----
{layoutcheck_reference_path}=src/test/resources/layout-references/{tt.browser}
{layoutcheck_reference_nametemplate}=%s.png

# Highly recommended to disable full screen for browser
{browser_maximize}=false

# Highly recommended to switch of the demo mode for layout tests
{demomode}=false
----
The directory for reference image may result in `src/test/resources/layout-references/chrome/WelcomePage.png` for example.

== PIXEL Mode

The comparison is generally carried out over the entire reference image. In this case, it is a prerequisite that the reference screenshot and the screenshot created during the test runtime have the same resolution (height and width are identical).

Mostly the website consists of many more elements than should be checked. Ingredients such as the header, menus or footer may falsify the test result if there are deviations from the reference, but these are not currently the subject of the test. For this reason, the {layoutcheck_ignore_color} property can be used to determine that a particular color in the image can be excluded from comparison. In the reference image, certain areas can be colored. {taf} recognizes the color at the top leftmost pixel in the image (x=1, y=1). This must be dyed additionally.

To validate the layout in Pixel Mode, you can check the whole page or a single <<GuiElements,GuiElement>>.

=== Check the whole Page

[source, java]
----
import eu.tsystems.mms.tic.testframework.layout.LayoutCheck;
import eu.tsystems.mms.tic.testframework.utils.AssertUtils;

final String pageImage = "WelcomePage";
float dist = LayoutCheck.run(driver, pageImage);
AssertUtils.assertLowerEqualThan(new BigDecimal(dist), new BigDecimal(10), String.format("Pixel distance of page %s", pageImage));
----

=== Check a single GuiElement

To check the layout of a single GuiElement only, you can use the standard asserts implementation.

[source, java]
----
import eu.tsystems.mms.tic.testframework.pageobjects.GuiElement;

final String guiElementImage = "HeaderComponent";
final GuiElement guiElement;
guiElement.asserts().assertScreenshot(guiElementImage, 10);
----

=== Take reference screenshots on first run

When you have configured the reference screenshots location and implemented the tests, you can now set the option

[source, properties, subs="attributes"]
----
{layoutcheck_takereference}=true
----
to enable taking automatically screenshots based on the current browser and size configuration and storing them to the reference image's location.

WARNING: All concrete distance values in this {layoutcheck_takereference}-mode will return `0` (zero) and always pass the tests.

== ANNOTATED Mode

For this mode, an arbitrary number of rectangles with a line width of one pixel are defined in the reference images. The color of the rectangles is to be communicated to {taf} via the upper left pixel (x=1, y=1). In the current screenshot, {taf} searches for the area within the annotated selection. The resolution of the current screenshot is irrelevant.

*tbd*
