= Mail-Connector

The module  mail-connector allows you to send and receive/read emails. The AbstractMailConnector superclass with protocol-independent methods for this purpose
Protocol-specific methods to access POP3 server are provided with the POP3MailConnector. Whilst sending emails via the SMTP protocol is possible with the SMTPMailConnector.
A MailUtils class provides utility methods and the XetaSSLSocketFactory allows SSLSocket connections.

== Project setup

.build.gradle
[source,gradle,role="primary"]
----
compile 'eu.tsystems.mms.tic.testerra:mail-connoctor:1-SNAPSHOT'
----

.pom.xml
[source,xml,role="secondary"]
----
<dependencies>
    <dependency>
        <groupId>eu.tsystems.mms.tic.testerra</groupId>
        <artifactId>mail-connector</artifactId>
        <version>1-SNAPSHOT</version>
    </dependency>
</dependencies>
----

.mailconnection.properties

The MailConnector classes need the server parameters, which need to be provided within a property file named 'mailconnection.properties'- This file has the following keys
If you want to use an SSL-encrypted connection, set the SMTP_SSL_ENABLED/POP3_SSL_ENABLED property to true. The ports must then be adjusted according to the server.
The actual connection to the mailserver is implicitly opened within each MailConnector class.

[source, properties,role="primary"]
----
#SMTP
SMTP_SERVER=smtp.mailserver.com
SMTP_SERVER_PORT=25
SMTP_USERNAME=user
SMTP_PASSWORD=password
SMTP_SSL_ENABLED=false

#POP3
POP3_SERVER=pop.mailserver.com
POP3_SERVER_PORT=110
POP3_FOLDER_INBOX=inbox
POP3_USERNAME=user
POP3_PASSWORD=password
POP3_SSL_ENABLED=false
DEBUG_SETTING=false

# IMAP
IMAP_SERVER=imap.mailserver.com
IMAP_SERVER_PORT=143
IMAP_FOLDER_INBOX=INBOX
IMAP_USERNAME=user
IMAP_PASSWORD=password
IMAP_SSL_ENABLED=false

# TIMING
POLLING_TIMER_SECONDS=10
MAX_READ_TRIES=20
----

== AbstractMailConnector
This abtstract class provides some general methods for working with mailboxes. There are getter and setter methods for accessing and adjusting the server parameters,
reading, moving and deleting messages from the inbox as well as means to poll the inbox until an email is received. The default maximum nummber of polls is 20 or set by MAX_READ_TRIES
The default timeout between polls is 50s or set by POLLING_TIMER_SECONDS.

== POP3MailConnector
The POP3MailConnector provides access to a POP3 server. Emails are read and processed by using methods of the superclass AbstractMailConnector.

.Reading and Deleting Mails
[source,java,role="secondary"]
----
POP3MailConnector pop3MailConnector = new POP3MailConnector();
// fetch all emails from Server
MimeMessage[] messages = pop3MailConnector.getMessages();

// wait until the email with subject 'test' arrived
final List<SearchCriteria> searchCriteria = new ArrayList<>();
searchCriteria.add(new SearchCriteria(SearchCriteriaType.SUBJECT, "test"));

Email email = pop3MailConnector.waitForMails(searchCriteria).get(0));

// delete all emails with this subject from the server while setting timeout and max number of polls explicitly
int maxPolls = 5;
int timeoutInSeconds = 2

Email email = pop3MailConnector.waitForMails(searchCriteria).get(0), maxPolls, timeoutInSeconds);

String recipient = email.getRecipients().get(0));

String subject = email.getSubject();
String messageId = null;

pop3MailConnector.deleteMessage(recipient, RecipientType.TO, subject, messageId);
----

.Working with attachments
[source,java,role="secondary"]
----
final List<SearchCriteria> searchCriteria = new ArrayList<>();
searchCriteria.add(new SearchCriteria(SearchCriteriaType.SUBJECT, "test"));
Email email = pop3MailConnector.waitForMails(searchCriteria).get(0);

try {
    Multipart content = (Multipart) email.getMessage().getContent();
    int contentCnt = content.getCount();
    String attachmentFileName = null;

    for (int i = 0; i < contentCnt; i++) {
        Part part = content.getBodyPart(i);

        // Retrieve attachment
        if (part.getDisposition().equals(Part.ATTACHMENT)) {
            attachmentFileName = part.getFileName();
        }
    }
} catch (IOException e) {
    e.printStackTrace();
} catch (MessagingException e) {
    e.printStackTrace();
}
----

== SMTPMailConnector
This entity allows sending emails via the SMTP protocol. Server name, port and, if applicable, username, password must be set in mailconnection.properties.
Due to the fact that the class inherits from AbstractMailConnector, it also has all functions of the MailConnector class.

.Sending Mails
[source,java,role="secondary"]
----
SMTPMailConnector smtpMailConnector = new SMTPMailConnector();

// send a created message
MimeMessage createdMessage = new MimeMessage(session);
try {
    msg.addRecipients(RecipientType.TO, RECIPIENT);
    msg.addFrom(new Address[]{new InternetAddress(SENDER)});
    msg.setSubject("testerra");
    msg.setText("mail text");
} catch (MessagingException e) {
    LOGGER.error(e.toString());
}
smtpMailConnector.sendMessage(createdMessage);

// send an existing message
MimeMessage existingMessage = MailUtils.loadEmailFile("test-mail.eml");
smtpMailConnector.sendMessage(existingMessage);
----

== ImapMailConnector
The IMAPMailConnector operates as the POP3MailConnector with an additional method to mark all mails as seen.

== MailUtils
This helper class contains methods which facilitate reoccurring task when working with mails, e.g. encoding, encrypting, decrypting, saving to file and comparing.