= PropertyManager

The `PropertyManager` provides a static interfaces for reading properties.

[source, java]
----
String property = PropertyManager.getProperty("my.property", "default");
----

It will look for the property definition appearance in the following order.

- `PropertyManager.getThreadLocalProperties()`
- `PropertyManager.getGlobalProperties()`
- `system.properties`
- `System.getProperties()`
- `test.properties`

When it's still not defined, in will fall back to the given `default` value.

== Property files

Testerra supports and loads automatically `.properties` files located under  `test/resources`.

The `test.properties` is called the Test Configuration and  contains everything required by the test, like Browser setup, SUT credentials or Layout test thresholds.

On the other hand, the `system.properties` file contains everything required by the testing environment like Selenium configuration. Tapas is using this file for passing infrastructure related settings.

NOTE: Properties defined in `system.properties` override `System.getProperties()`. That means you cannot override these Java system properties as command line parameters `-D[...]`.
