= PropertyManager

The `PropertyManagerProvider` interface provides a `PROPERTY_MANAGER` instance of `IPropertyManager`

[source, java]
----
String property = PROPERTY_MANAGER.getProperty("my.property", "default");
Long long = PROPERTY_MANAGER.getLongProperty("my.long", 200L);
Double doubleProperty = PROPERTY_MANAGER.getDoubleProperty("my.double", 200.0);
Boolean booleanProperty = PROPERTY_MANAGER.getBooleanProperty("my.boolean", false);
----

It will look for the property definition appearance in the following order:

- <<Test local properties>>
- `System.getProperties()` (`system.properties`)
- <<Property files>> (`test.properties`)

When it's still not defined, in will fall back to the given `default` value.

== Property files

include::../properties/property-attributes.adoc[]

Testerra supports and loads automatically `.properties` files located under  `test/resources`.

The `test.properties` is called the Test Configuration and contains everything required by the test, like Browser setup, SUT credentials or Layout test thresholds.

You can load additional properties files at any time.

[source,java]
----
PROPERTY_MANAGER.loadProperties("my.property.file");
----

== System properties


When a `system.properties` exists, Testerra loads and sets the given properties via `System.setProperty()` if they are not present already.

NOTE: This will not override system properties given by thte command line.

The path of this file can be changed by `{system_settings_file}` and will be automatically loaded with the following message

----
common.PropertyManager - Load system properties: /path/to/your/system.properties
----

== Test local properties

If you want to set properties for a test method only, you can use

[source,java]
----
PROPERTY_MANAGER.setTestLocalProperty("myproperty", "myvalue");
----

This property will be removed after every test method.
