= Testerra Xray connector

include::../properties/property-attributes.adoc[]

== Project setup

Current release

.Gradle
[source,gradle,role="primary"]
----
// build.gradle
implementation 'eu.tsystems.mms.tic.testerra:xray-connector:1.0'
----

.Maven
[source,xml,role="secondary"]
----
<!-- pom.xml -->
<dependencies>
    <dependency>
        <groupId>eu.tsystems.mms.tic.testerra</groupId>
        <artifactId>xray-connector</artifactId>
        <version>1.0</version>
    </dependency>
</dependencies>
----

=== Add property file

To use the X-Ray Connector plugin you have to provide multiple properties in your test project.
The easiest way is to create a file `xray.properties` in `src/test/resources` directory of your project.

.xray.properties
[source,properties]
----
# Enable synchronization and define strategy
xray.sync.enabled=true
xray.sync.skipped=true
xray.sync.strategy=adhoc
# Connection details
xray.rest.service.uri=https://jira.example.com/rest
xray.project.key=EXAMPLE
xray.user=jira-sync-user
xray.password=password
# Test Execution details
xray.test.execution.start.time.field.id=
xray.test.execution.finish.time.field.id=
xray.test.execution.revision.field.id=
xray.test.execution.test-environments.field.id=
# Validations to avoid unintend opertations
xray.validation.revision.regexp=.*
xray.validation.summary.regexp=.*
xray.validation.description.regexp=.*
# Automatically transitions when state reached
xray.transitions.on.created=
xray.transitions.on.updated=Test beginnen,Testdurchf端hrung beenden,Testdurchf端hrung zur端cksetzen
xray.transitions.on.done=An Test 端bergeben
# Store previous results, when Updated test Execution is used.
xray.previous.result.filename=
# Debugging / Logging features
xray.webresource.filter.logging.enabled=true
xray.webresource.filter.getrequestsonly.enabled=false
xray.webresource.filter.getrequestsonly.fake.response.key=EXAMPLE-1
----

With this property file included and filled up with your user account and credentials you should be able to synchronize your test results with the adhoc-strategy.

==== Synchronization strategies

===== Adhoc

When property `xray.sync.strategy` is set to `adhoc` your test results will be synchronized directly after a test method finished.
This will ensure, that you can track the current progress of your test execution in real-time in JIRA.

Please note that uploads and attachments for test execution will be uploaded after the execution finished.

===== Posthoc

When property `xray.sync.strategy` is set to `posthoc` your test results will be synchronized after the *complete* test execution ends.
The X-Ray connector will store every test result internally and then progress a bulk-upload of all test results.

=== Implement interfaces

For full control at runtime the X-Ray connector provide interfaces, that you have to implement before getting started.
This approach let you configure nearly everything that can be configured - at run time!

The easiest way is, to start with this example.
This implementation will provide static `XrayTestExecutionInfo`, but in practice you should determine these values at runtime.

With this configuration X-Ray connector will lookup for an JIRA issue of type `Test Execution` with matching attributes for:
- summary - description - revision - assignee

If you provide `null` values, the connector will ignore these fields.
The default implementations `EmptyMapper` and `EmptyTestExecutionUpdates` can be replaced by your own implementations and will be explained later.

.FooXrayResultsSynchronizer
[source,java]
----
public class FooXrayResultsSynchronizer extends AbstractXrayResultsSynchronizer {

    @Override
    XrayTestExecutionInfo getExecutionInfo() {
        return new XrayTestExecutionInfo() {

            @Override
            public String getSummary(final ISuite iSuite) {
                 return "My Test Execution";
            }

            @Override
            public String getDescription(final ISuite iSuite) {
                return "Automated test run";
            }

            @Override
            public String getRevision(final ISuite iSuite) {
                return "1.0-RC1";
            }

            @Override
            public String getAssignee(ISuite iSuite) {
                return "jira-sync-user";
            }

            @Override
            public String getFixVersion(ISuite iSuite) {
                return null;
            }
        };
    }

    @Override
    public XrayMapper getXrayMapper() {
        return new EmptyMapper();
    }

    @Override
    public XrayTestExecutionUpdates getExecutionUpdates() {
        return new EmptyTestExecutionUpdates();
    }
}
----

=== Mapping

To synchronize your test results to a specific JIRA issue, the X-Ray connector will use some mapping.
Basically there are two ways of mapping, both of them are instructed and controlled by annotations.

==== Test method mapping

To create a one-to-one mapping between your test methods and your JIRA issues of type `Test` you just have to set up the `XrayTest` annotation on your method.

.MethodsAnnotatedTest
[source,java]
----
public class MethodsAnnotatedTest extends TesterraTest {

    @Test
    @XrayTest(key = "EXAMPLE-2")
    public void passes() {
        Assert.assertTrue(true);
    }
}
----

==== Test class mapping

Instead of annotating each method by itself, you can annotate just the test class with the `XrayTestSet` annotation and the X-Ray connector will do the rest for you by searching JIRA issues itself with the provided query on your implementation of `XrayMapper.methodToXrayTestQuery`.

For example, you can provide the following simple mapper, that will just grab the test method name and search JIRA issues by matching summary.

.AnnotatedClassTest
----
@XrayTestSet(key = "EXAMPLE-5")
public class AnnotatedClassTest extends TesterraTest {
    //...
}
----

.TestMethodNameMapper
----
public class TestMethodNameMapper implements XrayMapper {

    @Override
    public JqlQuery resultToXrayTest(ITestResult testNgResult) {
        final Object[] parameters = testNgResult.getParameters();
        if (parameters.length > 0) {
            final String summary = String.format("%s with %s", testNgResult.getMethod().getMethodName(), parameters[0]);
            return JqlQuery.create()
                    .addCondition(new SummaryContainsExact(summary))
                    .build();
        } else {
            return JqlQuery.create()
                    .addCondition(new SummaryContainsExact(testNgResult.getMethod().getMethodName()))
                    .build();
        }
    }

    @Override
    public JqlQuery classToXrayTestSet(ITestClass testNgClass) {return null;}
}
----

> Note : The default `EmptyMapper` will return `null`.
This will lead in a synchronization error, because no matching JIRA issue was found.

==== Generic mapping

If you don't want to annotate your class with `XrayTestSet` and neither your test methods with `XrayTest` you can use a full generic way by implementing the `XrayMapper.classToXrayTestSet()` method as well as the already known `methodToXrayTestQuery()`.

.GenericMapper
[source,java]
----
public class GenericMapper implements XrayMapper {

    @Override
    public JqlQuery resultToXrayTest(ITestResult testNgResult) {
        final Object[] parameters = testNgResult.getParameters();
        if (parameters.length > 0) {
            final String summary = String.format("%s with %s", testNgResult.getMethod().getMethodName(), parameters[0]);
            return JqlQuery.create()
                    .addCondition(new SummaryContainsExact(summary))
                    .build();
        } else {
            return JqlQuery.create()
                    .addCondition(new SummaryContainsExact(testNgResult.getMethod().getMethodName()))
                    .build();

        }
    }

    @Override
    public JqlQuery classToXrayTestSet(ITestClass testNgClass) {
        return JqlQuery.create()
                .addCondition(new SummaryContainsExact("My Tests"))
                .build();
    }
}
----

In this case the X-ray connector will search JIRA issues for an issue of type `TestSet` with matching summary `My Tests`.
Then the connector will run a search for all associated test methods for this test set to find an issue of type `Test` and a summary equal the test method name.

==== Test execution updates on transition

As you may noticed in the cod examples above we provided a `EmptyTestExecutionUpdates` as implementation for `XrayTestExecutionUpdates` in our `FooXrayResultsSynchronizer`.
Test execution updates should be defined to add metadata to associated JIRA issue of type `Test Execution`.

The X-ray connector will lookup JIRA for Test execution matching your criteria provided as `XrayTestExecutionInfo`.
But if no matching Test Execution was found, it will create a new one by using the JIRA API.

To add labels, revision, summary, fix versions, associated version or other execution info you can use your own implementation of `XrayTestExecutionUpdates`.

.DefaultTestExecutionUpdates
----
public class DefaultTestExecutionUpdates implements XrayTestExecutionUpdates {

    @Override
    public JiraIssueUpdate updateOnNewExecutionCreated() {
        return JiraIssueUpdate.create()
                .field(new SetLabels("Test Automation"))
                .build();
    }

    @Override
    public JiraIssueUpdate updateOnExistingExecutionUpdated() {
        return JiraIssueUpdate.create()
                .field(new SetLabels("Test Automation"))
                .build();
    }

    @Override
    public JiraIssueUpdate updateOnExecutionDone() {
        return JiraIssueUpdate.create()
                .field(new SetAffectedVersions("1.0-RC"))
                .build();
    }
}
----

For example, this simple implementation will add the label "Test Automation" to your "updated" or freshly created test execution and set the "affected version" to "1.0-RC".

== Properties

.Overview about all properties allowed in xray.properties
[cols="2,^1,4",options="header"]
|===
| Property | default | Description
| {xray_sync_enabled} | false | Enable synchronization
| {xray_sync_skipped} | false | Enable synchronization of test methods in state SKIPPED
| {xray_sync_strategy} | adhoc | Enable `adhoc` or `posthoc` synchronization
| {xray_rest_service_uri} |  | URI of the JIRA REST service (with Xray-Plugin installed)
| {xray_project_key} |  | JIRA project key
| {xray_user} |  | JIRA user to sync test execution
| {xray_password} |  | Associated password for user
| {xray_test_execution_start_time_field_id} |  | The JIRA custom field for test execution start time.
| {xray_test_execution_finish_time_field_id} |  | The JIRA custom field for test execution finish time.
| {xray_test_execution_revision_field_id} |  | The JIRA custom field for test execution revision.
| {xray_test_execution_test_environments_field_id} |  | The JIRA custom field for test execution test-environments.
| {xray_validation_revision_regexp} | .* | Revision is validated against this regular expression to prevent unintended creation of test executions.
| {xray_validation_summary_regexp} | .* | Summary is validated against this regular expression to prevent unintended creation of test executions.
| {xray_validation_description_regexp} | .* | Description is validated against this regular expression to prevent unintended creation of test executions.
| {xray_previous_result_filename} | .* | When updating test execution, previous results are attached as json files using the defined file name. Default: No file created.
| {xray_transitions_on_created} |  | Transitions made on JIRA issue of type "Test Execution" when a status 'created' is reached (comma separated)
| {xray_transitions_on_updated} |  | Transitions made on JIRA issue of type "Test Execution" when a status 'updated' is reached (comma separated)
| {xray_transitions_on_done} |  | Transitions made on JIRA issue of type "Test Execution" when a status 'done' is reached (comma separated)
| {xray_webresource_filterlogging_enabled} | false | Enable logging of all web requests and response sent/received to/from JIRA
| {xray_webresource_filter_getrequestonly_enabled} | false | Enable this for debugging to avoid PUT/POST/DELETE requests sent to JIRA
| {xray_webresource_filter_getrequestonly_fake_response_key} | FAKE-666666 | This key will returned, when `xray.webresource.filter.getrequestsonly.enabled` set to `true` and PUT/POST/DELETE request was sent.
|===
