= Working with HTML elements

== Radio buttons

Since radio buttons share the same name, as the following example shows

[source,html]
----
<input type="radio" name="beverage" value="tee">
<input type="radio" name="beverage" value="coffee">
----

It's not a good practice to select it `By.name`.
Its better to select both options separately.

[source,java]
----
// Good practice
Locate locator = Locate.prepare("//input[@name='%s' and @value='%s']").unique();
UiElement teeOption = find(locator.with("beverage", "tee"));
UiElement coffeeOption = find(locator.with("beverage", "coffee"));

// Bad practice
UiElement options = find(By.name("beverage"));
----

== Shadow Roots

IMPORTANT: Working with Shadow Roots and Shadow DOM elements is not supported by Selenium.
It's a highly-experimental feature and not all browsers can work well with these elements in browser automation.
The best browser by our experience is a chromium-based browser.

Modern web applications are allowed to use some third-party components, which can be integrated with Shadow DOM.
This is the modern art of an iframe, because the components will be loaded via asynchronous JavaScript.

Each embedded Shadow DOM component will have its own shadow root.
To work with shadow root elements Testerra provide the method `shadowRoot()` on the `UiElement` class.

Given the following HTML code snippet it will be easier how to get the corresponding `UiElement` of the Shadow DOM component.

.HTML Code
[source,html]
----
<body>
    <div id="wrapper">
    <!-- HTML code-->
    <my-custom-shadow-root-element>
    <!-- #shadowRoot -->
        <div class="custom-component">
            <input id="custom-component-login-name" name="name">
        </div>
    </my-custom-shadow-root-element>
    </div>
    <!-- HTML code-->
</body>
----

.Java Code
[source,java]
----
UiElement shadowRootElement = find(By.cssSelector("my-custom-shadow-root-element")).shadowRoot();
UiElement inputName = shadowRootElement.find(By.xpath("./custom-component-login-name"));
----

IMPORTANT: Calling `displayed(boolean)` on `shadowRoot()`-notated UiElement will always return false, but `present(boolean)` will work as designed.

IMPORTANT: Because of technical limitations and internal handling of browser-different access to Shadow DOM elements, it is not possible to use any other `By` Selector-type than `By.xpath()` working with `find()` on a shadow root.

