plugins {
    id 'java'
}

def protobufVersion = '3.14.0'

dependencies {
    implementation core
    implementation project(':report-model')
    implementation "com.google.protobuf:protobuf-java:$protobufVersion"
}

def appReact = project(':report-ng:app-react')

tasks.named('processResources') {
    dependsOn(appReact.tasks.named('buildReport'))

    from(appReact.layout.projectDirectory.dir('dist')) {
        into 'report-ng'
        exclude 'model/**'
    }
}
