= Creation

== Create default UiElement

For every UiElement you need an implementation of the `UiElementFinder` interface (like <<PageObjects>>) and a locator (https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/By.html[Selenium docs]).

[source,java]
----
UiElement myElement = find(By.id("elementId"));
UiElement button1 = find(By.name("button"));
UiElement textOutputField = find(By.xpath("//p[@id='99']"));
----

== Create SubElements

The `UiElement` also implements `UiElementFinder`. Elements will only be searched in the DOM tree below the given parent element on which the method was called.

[source,java]
----
UiElement upper = find(By.name("upperElement"));

// Create the sub elements
UiElement lower = upper.find(By.name("lowerElement"));
UiElement lower = upper.find(By.xpath(".//p[@id='element']")); <1>
UiElement lower = upper.find(By.xpath("//p[@id='element']")); <2>
UiElement lower = upper.find(By.xpath("./p[@id='element']")); <3>
----
<1> Find any matching descendant
<2> Corrects the selector prefix to './/'
<3> Find any matching child


== Implement UiElementFinder

When you don't want to use the PageObject pattern, you can instantiate an `UiElementFinder` on your own.

[source,java]
----
import eu.tsystems.mms.tic.testframework.pageobjects.UiElementFinder;
import eu.tsystems.mms.tic.testframework.testing.TesterraTest;
import eu.tsystems.mms.tic.testframework.testing.UiElementFinderFactoryProvider;
import eu.tsystems.mms.tic.testframework.testing.WebDriverManagerProvider;

class MyTest extends TesterraTest implements UiElementFinderFactoryProvider, WebDriverManagerProvider {
    private UiElementFinder finder = uiElementFinderFactory.create(webDriverManager.getWebDriver());

    @Test
    public void test() {
        UiElement myElement = finder.find(By.id("elementId"));
        UiElement button1 = finder.find(By.name("button"));
        UiElement textOutputField = finder.find(By.xpath("//p[@id='99']"));
    }
}
----

== Advanced UiElement locating

The `UiElementFinder` interface also provides a `Locate` factory which provides more features than standard Selenium `By`.

=== Locate unique elements

If you want to make sure, that your element is unique.

[source,java]
----
UiElement myElement = find(Locate.by(By.id("elementId")).unique());
----

This will throw an exception, if not one WebElement has been found.

=== Locate displayed items only

[source,java]
----
UiElement myElement = find(Locate.by(By.xpath(".//button")).displayed());
----

=== Prepared xpath expressions

Using prepared expressions makes your selectors more readable.

[source,java]
----
Locate byText = Locate.prepare("//button[text()='%s'])");
Locate byClass = Locate.prepare("//%s[contains(@class, '%s')][%d]");

UiElement loginButton = find(byText.with("Login"));
UiElement logoutButton = find(byClass.with("button", "btn-logout", 1));
----

=== Filtering elements

You can also filter elements during find.

[source,java]
----
Locate byText = Locate.by(By.xpath("//button")).filter(webElement -> webElement.getText().equals("Open again"));

UiElement buttonContainsText = find(byText);
----

=== UiElements inside frames

Accessing WebElements inside frames requires changing the active frame before any action. UiElements do that automatically as long you identify every `<frame>` or `<iframe>` as own element.

[source,java]
----
UiElement frame1 = find(By.id("frame1"));

// frame2 is child of frame1
UiElement frame2 = frame1.find(By.id("frame2"));

// target is child of frame2 which is child of frame1,
UiElement target = frame2.find(By.id("target"));
----

And easier way is to use the `findDeep` method, which search for the element recursive in the frame hierarchy every time.
[source,java]
----
// in this case the frames are searched recurse automatically
UiElement target = findDeep(By.id("target"));
----

//
//== GuiElement by image
//
//You can also define GuiElements defined by a snippet from a screenshot. Testerra tries to locator the image on the viewport and looking for the surrounding webelement.
//
//[source,java]
//----
//
// //The second parameter for TesterraBy.image() needs a Url object to the image
//GuiElement byimage = new GuiElement(driver,
//        TesterraBy.image(driver, ClassLoader.getSystemResource("gui-elements/button.png")));
//----
//
//It is recommended to locator the images in `src/main/resources` and create the Url object via `ClassLoader.getSystemResource()`.



== Sensible Data

Sensible data, such as passwords, can be displayed obfuscated in the logs during the actions type and sendKeys.

[source,java]
GuiElement myElement = new GuiElement(driver, By..).sensibleData();

Only the placeholder * is logged in the report instead of the real value.
