= Checks

Similar to the assertion methods GuiElement provides so called check methods.

== Visibility checks

Checks if the element is present in the DOM
[source,java]
----
element.isPresent();
----

Checks if the element is present in the Viewport,
if it is visible by it's `display` and `visibility` style properties
and if it's `width` and `height` are both greater than 0.
[source,java]
----
element.isDisplayed();
----

Checks if the element is displayed and if it's partially or fully visible
in the scroll area of the viewport.

[source,java]
----
element.isVisible(boolean fullyVisible);
----

NOTE: It doesn't relate to `opacity` or `z-index` style properties. If you need to test the perceptual visibility to the human eye, you should consider implementing <<Layout Check>>.

[IMPORTANT]
======
It is not recommended to use these methods for assertions because they return the current state of the element without observing changes of the element or the page.

The assertion `element.asserts().assertIsDisplayed()` always uses the default GuiElement timeout until it fails. This should always be used for verifications.
======

== Standard WebElement checks

[source,java]
----
// The following methods are calling the standard webelement method
element.inEnabled();
element.isSelected();

// Tries to find out if an element could be selected.
element.isSelectable();
----
