= Actions

An UiElement provides a variety of action methods.
Beside the known WebElement methods there are some more useful methods to interact with the web site.

== Click on elements

[source,java]
----
UiElement element = find(By.id("button"));

element.click();
element.doubleClick();
element.contextClick();
----

NOTE: If you have troubles using these methods, take a look to the fallback solution <<Desktop WebDriver utilities>>.

== Enter text

[source,java]
----
UiElement element = find(By.id("input"));

// Enters the given text in a input or textfield.
// Any old values are automatically deleted before input.
// The type method has a value check. If the given string is NULL or empty, the method does nothing.
element.type("my text");

// The standard Selenium method is used.
// You can also use the Selenim Keys class to enter special keys.
element.sendKeys("my text");
element.sendKeys("my text" + Keys.ENTER);

// Delete the content of an input field.
element.clear();
----

== Use select boxes

[source,java]
----
UiElement element = find(By.id("select"));

// Get the Select WebElement of a UiElement
element.findWebElement(webElement -> {
    Select selectElement = new Select(webElement);

    // You can use all Selenium Select methods to interact.
    select.selectByIndex(2);
    select.selectByVisibleText("option");
    List<WebElements> list = select.getAllSelectedOptions();
});

----

== Use check boxes

[source,java]
----
UiElement element = find(By.id("checkbox"));

// Only check boxes returns true, all other elements return false
boolean check = element.waitFor().selectable(true);

// Check and uncheck the check box
element.select();
element.deselect();

// true = check, false = uncheck
element.select(true);
----

== Scrolling

You can scroll the browser viewport until the element is in the middle viewport if possible.

[source,java]
----
UiElement element = find(By.id("image"));

element.scrollIntoView();

// Lets offset pixel distance from the top of the viewport
element.scrollIntoView(new Point(0, -20))
----

== Mouse over

You can simulate the mouse pointer is moved over an element.

[source,java]
----
UiElement element = find(By.id("label"));

element.hover();
----

NOTE: If you have troubles using this method, take a look to the fallback solution <<Desktop WebDriver utilities>>.

== Drag and drop actions

With the utils class `MouseActions` you can execute a drag-and-drop actions.
Source and target GuiElements can be located in different frames.

[source,java]
----

UiElement source = find(By.id("elem1"));
UiElement target = find(By.id("elem2"));

MouseActions.dragAndDropJS(source, target);

// You can add one or more DragAndDropActions
MouseActions.dragAndDropJS(source, target, DragAndDropOption.CLICK_AFTER_RELEASE);

// This method provides a swipe of an element to a relative position from the element.
int offsetX = 50;   // Pixel
int offsetY = 125;  // Pixel
MouseActions.swipeElement(source, offsetX, offsetY);
----

== Highlight elements

This method draws a coloured frame around the UiElement.

[source,java]
----
UiElement element = find(By.id("button"));

element.highlight();
----
