= Groups of GuiElements

== GuiElementGroup

Purpose of GuiElementGroup is to manage GuiElements in groups to support layout checks on these groups and to simplify iterating over a set of GuiElements.

A typical use case is the assertion that the GuiElements in one GuiElementGroup are, for example, all located left from another group of GuiElements. In this manner a GuiElementGroup defines a bounding box for layout comparisions.

.Usage:
[source,java]
----
// Creates a GuiElement Group
GuiElementGroup myGuiElementGroup = new GuiElementGroup("example1");

// Adds the specified element.
myGuiElementGroup.add(GuiElement guiElement);

// Returns a Selenium Dimension object of the group.
// This contains the widh and height of the group.
// This is a rectangle which contains all the elements which were added.
Dimension myDimension = myGuiElementGroup.getSize();

// Returns a Selenium Point object containing a x and y coordinate.
// This point is the top left point of the rectangle which contains
// all the elements of the group.
Point myPoint = myGuiElementGroup.getPosition();

// Returns the name of the group as String.
String groupName = myGuiElementGroup.getName();

// Returns a list with the contained GuiElements.
List<GuiElement> myElements = myGuiElementGroup.elements();

// Call this if the website has changed.
// The GuiElementGroup will then be updated before the next use.
myGuiElementGroup.goupSizeOrLocationChanged();
----

== GuiElementGroups on pages

#Annoation @Groups(groupName = "groupname") -> getGuiElementGroups returns these GuiElements as group#

The class GuiElementGroups provides a way to manage multiple GuiElementGroup instances
on a page. It is basically a map of a String as key to a GuiElementGroup.

This map can be accessed via getGuiElementGroups() on the page objects.

.Usage:
[source,java]
----
// Get the GuiElementGroups Map.
GuiElementGroups guiElementGroups = pageObject.getGuiElementGroups();

// Add a GuiElement to a specified group.
// The group is created if it does not exist already.
guiElementGroups.addGuiElementToGroup(GuiElement element, String groupName)

// Retrieve a GuiElementGroup with the specified name.
GuiElementGroup myGroup = guiElementGroups.getGuiElementGroup(String groupName);
----

