// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package eu.tsystems.mms.tic.testframework.report.model;

/**
 * Protobuf type {@code data.ClassContextAggregate}
 */
public  final class ClassContextAggregate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ClassContextAggregate)
    ClassContextAggregateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClassContextAggregate.newBuilder() to construct.
  private ClassContextAggregate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClassContextAggregate() {
    methodContexts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClassContextAggregate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClassContextAggregate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            eu.tsystems.mms.tic.testframework.report.model.ClassContext.Builder subBuilder = null;
            if (classContext_ != null) {
              subBuilder = classContext_.toBuilder();
            }
            classContext_ = input.readMessage(eu.tsystems.mms.tic.testframework.report.model.ClassContext.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(classContext_);
              classContext_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              methodContexts_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.MethodContext>();
              mutable_bitField0_ |= 0x00000001;
            }
            methodContexts_.add(
                input.readMessage(eu.tsystems.mms.tic.testframework.report.model.MethodContext.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        methodContexts_ = java.util.Collections.unmodifiableList(methodContexts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ClassContextAggregate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ClassContextAggregate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate.class, eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate.Builder.class);
  }

  public static final int CLASS_CONTEXT_FIELD_NUMBER = 1;
  private eu.tsystems.mms.tic.testframework.report.model.ClassContext classContext_;
  /**
   * <code>.data.ClassContext class_context = 1;</code>
   * @return Whether the classContext field is set.
   */
  public boolean hasClassContext() {
    return classContext_ != null;
  }
  /**
   * <code>.data.ClassContext class_context = 1;</code>
   * @return The classContext.
   */
  public eu.tsystems.mms.tic.testframework.report.model.ClassContext getClassContext() {
    return classContext_ == null ? eu.tsystems.mms.tic.testframework.report.model.ClassContext.getDefaultInstance() : classContext_;
  }
  /**
   * <code>.data.ClassContext class_context = 1;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.ClassContextOrBuilder getClassContextOrBuilder() {
    return getClassContext();
  }

  public static final int METHOD_CONTEXTS_FIELD_NUMBER = 2;
  private java.util.List<eu.tsystems.mms.tic.testframework.report.model.MethodContext> methodContexts_;
  /**
   * <code>repeated .data.MethodContext method_contexts = 2;</code>
   */
  public java.util.List<eu.tsystems.mms.tic.testframework.report.model.MethodContext> getMethodContextsList() {
    return methodContexts_;
  }
  /**
   * <code>repeated .data.MethodContext method_contexts = 2;</code>
   */
  public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.MethodContextOrBuilder> 
      getMethodContextsOrBuilderList() {
    return methodContexts_;
  }
  /**
   * <code>repeated .data.MethodContext method_contexts = 2;</code>
   */
  public int getMethodContextsCount() {
    return methodContexts_.size();
  }
  /**
   * <code>repeated .data.MethodContext method_contexts = 2;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.MethodContext getMethodContexts(int index) {
    return methodContexts_.get(index);
  }
  /**
   * <code>repeated .data.MethodContext method_contexts = 2;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.MethodContextOrBuilder getMethodContextsOrBuilder(
      int index) {
    return methodContexts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (classContext_ != null) {
      output.writeMessage(1, getClassContext());
    }
    for (int i = 0; i < methodContexts_.size(); i++) {
      output.writeMessage(2, methodContexts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (classContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClassContext());
    }
    for (int i = 0; i < methodContexts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, methodContexts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate)) {
      return super.equals(obj);
    }
    eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate other = (eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate) obj;

    if (hasClassContext() != other.hasClassContext()) return false;
    if (hasClassContext()) {
      if (!getClassContext()
          .equals(other.getClassContext())) return false;
    }
    if (!getMethodContextsList()
        .equals(other.getMethodContextsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClassContext()) {
      hash = (37 * hash) + CLASS_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getClassContext().hashCode();
    }
    if (getMethodContextsCount() > 0) {
      hash = (37 * hash) + METHOD_CONTEXTS_FIELD_NUMBER;
      hash = (53 * hash) + getMethodContextsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code data.ClassContextAggregate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ClassContextAggregate)
      eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ClassContextAggregate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ClassContextAggregate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate.class, eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate.Builder.class);
    }

    // Construct using eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMethodContextsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (classContextBuilder_ == null) {
        classContext_ = null;
      } else {
        classContext_ = null;
        classContextBuilder_ = null;
      }
      if (methodContextsBuilder_ == null) {
        methodContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        methodContextsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ClassContextAggregate_descriptor;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate getDefaultInstanceForType() {
      return eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate.getDefaultInstance();
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate build() {
      eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate buildPartial() {
      eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate result = new eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate(this);
      int from_bitField0_ = bitField0_;
      if (classContextBuilder_ == null) {
        result.classContext_ = classContext_;
      } else {
        result.classContext_ = classContextBuilder_.build();
      }
      if (methodContextsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          methodContexts_ = java.util.Collections.unmodifiableList(methodContexts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.methodContexts_ = methodContexts_;
      } else {
        result.methodContexts_ = methodContextsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate) {
        return mergeFrom((eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate other) {
      if (other == eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate.getDefaultInstance()) return this;
      if (other.hasClassContext()) {
        mergeClassContext(other.getClassContext());
      }
      if (methodContextsBuilder_ == null) {
        if (!other.methodContexts_.isEmpty()) {
          if (methodContexts_.isEmpty()) {
            methodContexts_ = other.methodContexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMethodContextsIsMutable();
            methodContexts_.addAll(other.methodContexts_);
          }
          onChanged();
        }
      } else {
        if (!other.methodContexts_.isEmpty()) {
          if (methodContextsBuilder_.isEmpty()) {
            methodContextsBuilder_.dispose();
            methodContextsBuilder_ = null;
            methodContexts_ = other.methodContexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            methodContextsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMethodContextsFieldBuilder() : null;
          } else {
            methodContextsBuilder_.addAllMessages(other.methodContexts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private eu.tsystems.mms.tic.testframework.report.model.ClassContext classContext_;
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.ClassContext, eu.tsystems.mms.tic.testframework.report.model.ClassContext.Builder, eu.tsystems.mms.tic.testframework.report.model.ClassContextOrBuilder> classContextBuilder_;
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     * @return Whether the classContext field is set.
     */
    public boolean hasClassContext() {
      return classContextBuilder_ != null || classContext_ != null;
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     * @return The classContext.
     */
    public eu.tsystems.mms.tic.testframework.report.model.ClassContext getClassContext() {
      if (classContextBuilder_ == null) {
        return classContext_ == null ? eu.tsystems.mms.tic.testframework.report.model.ClassContext.getDefaultInstance() : classContext_;
      } else {
        return classContextBuilder_.getMessage();
      }
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     */
    public Builder setClassContext(eu.tsystems.mms.tic.testframework.report.model.ClassContext value) {
      if (classContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        classContext_ = value;
        onChanged();
      } else {
        classContextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     */
    public Builder setClassContext(
        eu.tsystems.mms.tic.testframework.report.model.ClassContext.Builder builderForValue) {
      if (classContextBuilder_ == null) {
        classContext_ = builderForValue.build();
        onChanged();
      } else {
        classContextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     */
    public Builder mergeClassContext(eu.tsystems.mms.tic.testframework.report.model.ClassContext value) {
      if (classContextBuilder_ == null) {
        if (classContext_ != null) {
          classContext_ =
            eu.tsystems.mms.tic.testframework.report.model.ClassContext.newBuilder(classContext_).mergeFrom(value).buildPartial();
        } else {
          classContext_ = value;
        }
        onChanged();
      } else {
        classContextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     */
    public Builder clearClassContext() {
      if (classContextBuilder_ == null) {
        classContext_ = null;
        onChanged();
      } else {
        classContext_ = null;
        classContextBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.ClassContext.Builder getClassContextBuilder() {
      
      onChanged();
      return getClassContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.ClassContextOrBuilder getClassContextOrBuilder() {
      if (classContextBuilder_ != null) {
        return classContextBuilder_.getMessageOrBuilder();
      } else {
        return classContext_ == null ?
            eu.tsystems.mms.tic.testframework.report.model.ClassContext.getDefaultInstance() : classContext_;
      }
    }
    /**
     * <code>.data.ClassContext class_context = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.ClassContext, eu.tsystems.mms.tic.testframework.report.model.ClassContext.Builder, eu.tsystems.mms.tic.testframework.report.model.ClassContextOrBuilder> 
        getClassContextFieldBuilder() {
      if (classContextBuilder_ == null) {
        classContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.ClassContext, eu.tsystems.mms.tic.testframework.report.model.ClassContext.Builder, eu.tsystems.mms.tic.testframework.report.model.ClassContextOrBuilder>(
                getClassContext(),
                getParentForChildren(),
                isClean());
        classContext_ = null;
      }
      return classContextBuilder_;
    }

    private java.util.List<eu.tsystems.mms.tic.testframework.report.model.MethodContext> methodContexts_ =
      java.util.Collections.emptyList();
    private void ensureMethodContextsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        methodContexts_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.MethodContext>(methodContexts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.MethodContext, eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder, eu.tsystems.mms.tic.testframework.report.model.MethodContextOrBuilder> methodContextsBuilder_;

    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.MethodContext> getMethodContextsList() {
      if (methodContextsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(methodContexts_);
      } else {
        return methodContextsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public int getMethodContextsCount() {
      if (methodContextsBuilder_ == null) {
        return methodContexts_.size();
      } else {
        return methodContextsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.MethodContext getMethodContexts(int index) {
      if (methodContextsBuilder_ == null) {
        return methodContexts_.get(index);
      } else {
        return methodContextsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder setMethodContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.MethodContext value) {
      if (methodContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodContextsIsMutable();
        methodContexts_.set(index, value);
        onChanged();
      } else {
        methodContextsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder setMethodContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder builderForValue) {
      if (methodContextsBuilder_ == null) {
        ensureMethodContextsIsMutable();
        methodContexts_.set(index, builderForValue.build());
        onChanged();
      } else {
        methodContextsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder addMethodContexts(eu.tsystems.mms.tic.testframework.report.model.MethodContext value) {
      if (methodContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodContextsIsMutable();
        methodContexts_.add(value);
        onChanged();
      } else {
        methodContextsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder addMethodContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.MethodContext value) {
      if (methodContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodContextsIsMutable();
        methodContexts_.add(index, value);
        onChanged();
      } else {
        methodContextsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder addMethodContexts(
        eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder builderForValue) {
      if (methodContextsBuilder_ == null) {
        ensureMethodContextsIsMutable();
        methodContexts_.add(builderForValue.build());
        onChanged();
      } else {
        methodContextsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder addMethodContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder builderForValue) {
      if (methodContextsBuilder_ == null) {
        ensureMethodContextsIsMutable();
        methodContexts_.add(index, builderForValue.build());
        onChanged();
      } else {
        methodContextsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder addAllMethodContexts(
        java.lang.Iterable<? extends eu.tsystems.mms.tic.testframework.report.model.MethodContext> values) {
      if (methodContextsBuilder_ == null) {
        ensureMethodContextsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methodContexts_);
        onChanged();
      } else {
        methodContextsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder clearMethodContexts() {
      if (methodContextsBuilder_ == null) {
        methodContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        methodContextsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public Builder removeMethodContexts(int index) {
      if (methodContextsBuilder_ == null) {
        ensureMethodContextsIsMutable();
        methodContexts_.remove(index);
        onChanged();
      } else {
        methodContextsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder getMethodContextsBuilder(
        int index) {
      return getMethodContextsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.MethodContextOrBuilder getMethodContextsOrBuilder(
        int index) {
      if (methodContextsBuilder_ == null) {
        return methodContexts_.get(index);  } else {
        return methodContextsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.MethodContextOrBuilder> 
         getMethodContextsOrBuilderList() {
      if (methodContextsBuilder_ != null) {
        return methodContextsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(methodContexts_);
      }
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder addMethodContextsBuilder() {
      return getMethodContextsFieldBuilder().addBuilder(
          eu.tsystems.mms.tic.testframework.report.model.MethodContext.getDefaultInstance());
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder addMethodContextsBuilder(
        int index) {
      return getMethodContextsFieldBuilder().addBuilder(
          index, eu.tsystems.mms.tic.testframework.report.model.MethodContext.getDefaultInstance());
    }
    /**
     * <code>repeated .data.MethodContext method_contexts = 2;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder> 
         getMethodContextsBuilderList() {
      return getMethodContextsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.MethodContext, eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder, eu.tsystems.mms.tic.testframework.report.model.MethodContextOrBuilder> 
        getMethodContextsFieldBuilder() {
      if (methodContextsBuilder_ == null) {
        methodContextsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.MethodContext, eu.tsystems.mms.tic.testframework.report.model.MethodContext.Builder, eu.tsystems.mms.tic.testframework.report.model.MethodContextOrBuilder>(
                methodContexts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        methodContexts_ = null;
      }
      return methodContextsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ClassContextAggregate)
  }

  // @@protoc_insertion_point(class_scope:data.ClassContextAggregate)
  private static final eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate();
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClassContextAggregate>
      PARSER = new com.google.protobuf.AbstractParser<ClassContextAggregate>() {
    @java.lang.Override
    public ClassContextAggregate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClassContextAggregate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClassContextAggregate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClassContextAggregate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.ClassContextAggregate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

