// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

public interface ClassContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.ClassContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.data.ContextValues context_values = 1;</code>
   * @return Whether the contextValues field is set.
   */
  boolean hasContextValues();
  /**
   * <code>.data.ContextValues context_values = 1;</code>
   * @return The contextValues.
   */
  eu.tsystems.mms.tic.testframework.report.model.ContextValues getContextValues();
  /**
   * <code>.data.ContextValues context_values = 1;</code>
   */
  eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder getContextValuesOrBuilder();

  /**
   * <pre>
   *repeated string method_context_ids = 6 [deprecated = true];
   * </pre>
   *
   * <code>string full_class_name = 7;</code>
   * @return The fullClassName.
   */
  java.lang.String getFullClassName();
  /**
   * <pre>
   *repeated string method_context_ids = 6 [deprecated = true];
   * </pre>
   *
   * <code>string full_class_name = 7;</code>
   * @return The bytes for fullClassName.
   */
  com.google.protobuf.ByteString
      getFullClassNameBytes();

  /**
   * <pre>
   *string simple_class_name = 8 [deprecated = true];
   * </pre>
   *
   * <code>string test_context_id = 9;</code>
   * @return The testContextId.
   */
  java.lang.String getTestContextId();
  /**
   * <pre>
   *string simple_class_name = 8 [deprecated = true];
   * </pre>
   *
   * <code>string test_context_id = 9;</code>
   * @return The bytes for testContextId.
   */
  com.google.protobuf.ByteString
      getTestContextIdBytes();

  /**
   * <pre>
   *string execution_context_id = 10 [deprecated = true];
   * </pre>
   *
   * <code>string test_context_name = 11;</code>
   * @return The testContextName.
   */
  java.lang.String getTestContextName();
  /**
   * <pre>
   *string execution_context_id = 10 [deprecated = true];
   * </pre>
   *
   * <code>string test_context_name = 11;</code>
   * @return The bytes for testContextName.
   */
  com.google.protobuf.ByteString
      getTestContextNameBytes();
}
