// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

public interface ClickPathEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.ClickPathEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.data.ClickPathEventType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.data.ClickPathEventType type = 1;</code>
   * @return The type.
   */
  eu.tsystems.mms.tic.testframework.report.model.ClickPathEventType getType();

  /**
   * <code>string subject = 2;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 2;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string session_id = 3;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 3;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
