// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

/**
 * Protobuf type {@code data.ContextValues}
 */
public  final class ContextValues extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ContextValues)
    ContextValuesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContextValues.newBuilder() to construct.
  private ContextValues(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContextValues() {
    id_ = "";
    name_ = "";
    resultStatus_ = 0;
    execStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContextValues();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ContextValues(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 16: {

            created_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 32: {

            startTime_ = input.readInt64();
            break;
          }
          case 40: {

            endTime_ = input.readInt64();
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            resultStatus_ = rawValue;
            break;
          }
          case 64: {
            int rawValue = input.readEnum();

            execStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ContextValues_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ContextValues_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.tsystems.mms.tic.testframework.report.model.ContextValues.class, eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_FIELD_NUMBER = 2;
  private long created_;
  /**
   * <code>int64 created = 2;</code>
   * @return The created.
   */
  public long getCreated() {
    return created_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_TIME_FIELD_NUMBER = 4;
  private long startTime_;
  /**
   * <code>int64 start_time = 4;</code>
   * @return The startTime.
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 5;
  private long endTime_;
  /**
   * <pre>
   *    string swi = 6 [deprecated = true];
   * </pre>
   *
   * <code>int64 end_time = 5;</code>
   * @return The endTime.
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int RESULT_STATUS_FIELD_NUMBER = 7;
  private int resultStatus_;
  /**
   * <code>.data.ResultStatusType result_status = 7;</code>
   * @return The enum numeric value on the wire for resultStatus.
   */
  public int getResultStatusValue() {
    return resultStatus_;
  }
  /**
   * <code>.data.ResultStatusType result_status = 7;</code>
   * @return The resultStatus.
   */
  public eu.tsystems.mms.tic.testframework.report.model.ResultStatusType getResultStatus() {
    @SuppressWarnings("deprecation")
    eu.tsystems.mms.tic.testframework.report.model.ResultStatusType result = eu.tsystems.mms.tic.testframework.report.model.ResultStatusType.valueOf(resultStatus_);
    return result == null ? eu.tsystems.mms.tic.testframework.report.model.ResultStatusType.UNRECOGNIZED : result;
  }

  public static final int EXEC_STATUS_FIELD_NUMBER = 8;
  private int execStatus_;
  /**
   * <code>.data.ExecStatusType exec_status = 8;</code>
   * @return The enum numeric value on the wire for execStatus.
   */
  public int getExecStatusValue() {
    return execStatus_;
  }
  /**
   * <code>.data.ExecStatusType exec_status = 8;</code>
   * @return The execStatus.
   */
  public eu.tsystems.mms.tic.testframework.report.model.ExecStatusType getExecStatus() {
    @SuppressWarnings("deprecation")
    eu.tsystems.mms.tic.testframework.report.model.ExecStatusType result = eu.tsystems.mms.tic.testframework.report.model.ExecStatusType.valueOf(execStatus_);
    return result == null ? eu.tsystems.mms.tic.testframework.report.model.ExecStatusType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (created_ != 0L) {
      output.writeInt64(2, created_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(4, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(5, endTime_);
    }
    if (resultStatus_ != eu.tsystems.mms.tic.testframework.report.model.ResultStatusType.RST_NOT_SET.getNumber()) {
      output.writeEnum(7, resultStatus_);
    }
    if (execStatus_ != eu.tsystems.mms.tic.testframework.report.model.ExecStatusType.EST_NOT_SET.getNumber()) {
      output.writeEnum(8, execStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (created_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, created_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, endTime_);
    }
    if (resultStatus_ != eu.tsystems.mms.tic.testframework.report.model.ResultStatusType.RST_NOT_SET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, resultStatus_);
    }
    if (execStatus_ != eu.tsystems.mms.tic.testframework.report.model.ExecStatusType.EST_NOT_SET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, execStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.tsystems.mms.tic.testframework.report.model.ContextValues)) {
      return super.equals(obj);
    }
    eu.tsystems.mms.tic.testframework.report.model.ContextValues other = (eu.tsystems.mms.tic.testframework.report.model.ContextValues) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (getCreated()
        != other.getCreated()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (resultStatus_ != other.resultStatus_) return false;
    if (execStatus_ != other.execStatus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CREATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreated());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + END_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + RESULT_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + resultStatus_;
    hash = (37 * hash) + EXEC_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + execStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.tsystems.mms.tic.testframework.report.model.ContextValues prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code data.ContextValues}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ContextValues)
      eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ContextValues_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ContextValues_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.tsystems.mms.tic.testframework.report.model.ContextValues.class, eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder.class);
    }

    // Construct using eu.tsystems.mms.tic.testframework.report.model.ContextValues.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      created_ = 0L;

      name_ = "";

      startTime_ = 0L;

      endTime_ = 0L;

      resultStatus_ = 0;

      execStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ContextValues_descriptor;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ContextValues getDefaultInstanceForType() {
      return eu.tsystems.mms.tic.testframework.report.model.ContextValues.getDefaultInstance();
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ContextValues build() {
      eu.tsystems.mms.tic.testframework.report.model.ContextValues result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ContextValues buildPartial() {
      eu.tsystems.mms.tic.testframework.report.model.ContextValues result = new eu.tsystems.mms.tic.testframework.report.model.ContextValues(this);
      result.id_ = id_;
      result.created_ = created_;
      result.name_ = name_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.resultStatus_ = resultStatus_;
      result.execStatus_ = execStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.tsystems.mms.tic.testframework.report.model.ContextValues) {
        return mergeFrom((eu.tsystems.mms.tic.testframework.report.model.ContextValues)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.tsystems.mms.tic.testframework.report.model.ContextValues other) {
      if (other == eu.tsystems.mms.tic.testframework.report.model.ContextValues.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getCreated() != 0L) {
        setCreated(other.getCreated());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.resultStatus_ != 0) {
        setResultStatusValue(other.getResultStatusValue());
      }
      if (other.execStatus_ != 0) {
        setExecStatusValue(other.getExecStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.tsystems.mms.tic.testframework.report.model.ContextValues parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.tsystems.mms.tic.testframework.report.model.ContextValues) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private long created_ ;
    /**
     * <code>int64 created = 2;</code>
     * @return The created.
     */
    public long getCreated() {
      return created_;
    }
    /**
     * <code>int64 created = 2;</code>
     * @param value The created to set.
     * @return This builder for chaining.
     */
    public Builder setCreated(long value) {
      
      created_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 created = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreated() {
      
      created_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>int64 start_time = 4;</code>
     * @return The startTime.
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 start_time = 4;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <pre>
     *    string swi = 6 [deprecated = true];
     * </pre>
     *
     * <code>int64 end_time = 5;</code>
     * @return The endTime.
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <pre>
     *    string swi = 6 [deprecated = true];
     * </pre>
     *
     * <code>int64 end_time = 5;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    string swi = 6 [deprecated = true];
     * </pre>
     *
     * <code>int64 end_time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int resultStatus_ = 0;
    /**
     * <code>.data.ResultStatusType result_status = 7;</code>
     * @return The enum numeric value on the wire for resultStatus.
     */
    public int getResultStatusValue() {
      return resultStatus_;
    }
    /**
     * <code>.data.ResultStatusType result_status = 7;</code>
     * @param value The enum numeric value on the wire for resultStatus to set.
     * @return This builder for chaining.
     */
    public Builder setResultStatusValue(int value) {
      resultStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.data.ResultStatusType result_status = 7;</code>
     * @return The resultStatus.
     */
    public eu.tsystems.mms.tic.testframework.report.model.ResultStatusType getResultStatus() {
      @SuppressWarnings("deprecation")
      eu.tsystems.mms.tic.testframework.report.model.ResultStatusType result = eu.tsystems.mms.tic.testframework.report.model.ResultStatusType.valueOf(resultStatus_);
      return result == null ? eu.tsystems.mms.tic.testframework.report.model.ResultStatusType.UNRECOGNIZED : result;
    }
    /**
     * <code>.data.ResultStatusType result_status = 7;</code>
     * @param value The resultStatus to set.
     * @return This builder for chaining.
     */
    public Builder setResultStatus(eu.tsystems.mms.tic.testframework.report.model.ResultStatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      resultStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.data.ResultStatusType result_status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultStatus() {
      
      resultStatus_ = 0;
      onChanged();
      return this;
    }

    private int execStatus_ = 0;
    /**
     * <code>.data.ExecStatusType exec_status = 8;</code>
     * @return The enum numeric value on the wire for execStatus.
     */
    public int getExecStatusValue() {
      return execStatus_;
    }
    /**
     * <code>.data.ExecStatusType exec_status = 8;</code>
     * @param value The enum numeric value on the wire for execStatus to set.
     * @return This builder for chaining.
     */
    public Builder setExecStatusValue(int value) {
      execStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.data.ExecStatusType exec_status = 8;</code>
     * @return The execStatus.
     */
    public eu.tsystems.mms.tic.testframework.report.model.ExecStatusType getExecStatus() {
      @SuppressWarnings("deprecation")
      eu.tsystems.mms.tic.testframework.report.model.ExecStatusType result = eu.tsystems.mms.tic.testframework.report.model.ExecStatusType.valueOf(execStatus_);
      return result == null ? eu.tsystems.mms.tic.testframework.report.model.ExecStatusType.UNRECOGNIZED : result;
    }
    /**
     * <code>.data.ExecStatusType exec_status = 8;</code>
     * @param value The execStatus to set.
     * @return This builder for chaining.
     */
    public Builder setExecStatus(eu.tsystems.mms.tic.testframework.report.model.ExecStatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      execStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.data.ExecStatusType exec_status = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecStatus() {
      
      execStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ContextValues)
  }

  // @@protoc_insertion_point(class_scope:data.ContextValues)
  private static final eu.tsystems.mms.tic.testframework.report.model.ContextValues DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.tsystems.mms.tic.testframework.report.model.ContextValues();
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ContextValues getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContextValues>
      PARSER = new com.google.protobuf.AbstractParser<ContextValues>() {
    @java.lang.Override
    public ContextValues parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ContextValues(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ContextValues> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContextValues> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.ContextValues getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

