// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

/**
 * Protobuf type {@code data.ExecutionContext}
 */
public final class ExecutionContext extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ExecutionContext)
    ExecutionContextOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutionContext.newBuilder() to construct.
  private ExecutionContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutionContext() {
    suiteContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    projectId_ = "";
    jobId_ = "";
    runId_ = "";
    taskId_ = "";
    exclusiveSessionContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    logMessages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecutionContext();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecutionContext(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder subBuilder = null;
            if (contextValues_ != null) {
              subBuilder = contextValues_.toBuilder();
            }
            contextValues_ = input.readMessage(eu.tsystems.mms.tic.testframework.report.model.ContextValues.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(contextValues_);
              contextValues_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              suiteContextIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            suiteContextIds_.add(s);
            break;
          }
          case 58: {
            eu.tsystems.mms.tic.testframework.report.model.RunConfig.Builder subBuilder = null;
            if (runConfig_ != null) {
              subBuilder = runConfig_.toBuilder();
            }
            runConfig_ = input.readMessage(eu.tsystems.mms.tic.testframework.report.model.RunConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(runConfig_);
              runConfig_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            projectId_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            jobId_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            runId_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              exclusiveSessionContextIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            exclusiveSessionContextIds_.add(s);
            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              logMessages_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.LogMessage>();
              mutable_bitField0_ |= 0x00000004;
            }
            logMessages_.add(
                input.readMessage(eu.tsystems.mms.tic.testframework.report.model.LogMessage.parser(), extensionRegistry));
            break;
          }
          case 120: {

            estimatedTestsCount_ = input.readInt32();
            break;
          }
          case 130: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              failureCorridorLimits_ = com.google.protobuf.MapField.newMapField(
                  FailureCorridorLimitsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            failureCorridorLimits__ = input.readMessage(
                FailureCorridorLimitsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            failureCorridorLimits_.getMutableMap().put(
                failureCorridorLimits__.getKey(), failureCorridorLimits__.getValue());
            break;
          }
          case 138: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              failureCorridorCounts_ = com.google.protobuf.MapField.newMapField(
                  FailureCorridorCountsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            failureCorridorCounts__ = input.readMessage(
                FailureCorridorCountsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            failureCorridorCounts_.getMutableMap().put(
                failureCorridorCounts__.getKey(), failureCorridorCounts__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        suiteContextIds_ = suiteContextIds_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        exclusiveSessionContextIds_ = exclusiveSessionContextIds_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        logMessages_ = java.util.Collections.unmodifiableList(logMessages_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ExecutionContext_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 16:
        return internalGetFailureCorridorLimits();
      case 17:
        return internalGetFailureCorridorCounts();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ExecutionContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.class, eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder.class);
  }

  public static final int CONTEXT_VALUES_FIELD_NUMBER = 1;
  private eu.tsystems.mms.tic.testframework.report.model.ContextValues contextValues_;
  /**
   * <code>.data.ContextValues context_values = 1;</code>
   * @return Whether the contextValues field is set.
   */
  @java.lang.Override
  public boolean hasContextValues() {
    return contextValues_ != null;
  }
  /**
   * <code>.data.ContextValues context_values = 1;</code>
   * @return The contextValues.
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.ContextValues getContextValues() {
    return contextValues_ == null ? eu.tsystems.mms.tic.testframework.report.model.ContextValues.getDefaultInstance() : contextValues_;
  }
  /**
   * <code>.data.ContextValues context_values = 1;</code>
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder getContextValuesOrBuilder() {
    return getContextValues();
  }

  public static final int SUITE_CONTEXT_IDS_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList suiteContextIds_;
  /**
   * <pre>
   *    repeated string merged_class_context_ids = 3 [deprecated = true];
   *    repeated ContextClip exit_points = 4 [deprecated = true];
   *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
   * </pre>
   *
   * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
   * @return A list containing the suiteContextIds.
   */
  @java.lang.Deprecated public com.google.protobuf.ProtocolStringList
      getSuiteContextIdsList() {
    return suiteContextIds_;
  }
  /**
   * <pre>
   *    repeated string merged_class_context_ids = 3 [deprecated = true];
   *    repeated ContextClip exit_points = 4 [deprecated = true];
   *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
   * </pre>
   *
   * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
   * @return The count of suiteContextIds.
   */
  @java.lang.Deprecated public int getSuiteContextIdsCount() {
    return suiteContextIds_.size();
  }
  /**
   * <pre>
   *    repeated string merged_class_context_ids = 3 [deprecated = true];
   *    repeated ContextClip exit_points = 4 [deprecated = true];
   *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
   * </pre>
   *
   * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
   * @param index The index of the element to return.
   * @return The suiteContextIds at the given index.
   */
  @java.lang.Deprecated public java.lang.String getSuiteContextIds(int index) {
    return suiteContextIds_.get(index);
  }
  /**
   * <pre>
   *    repeated string merged_class_context_ids = 3 [deprecated = true];
   *    repeated ContextClip exit_points = 4 [deprecated = true];
   *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
   * </pre>
   *
   * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
   * @param index The index of the value to return.
   * @return The bytes of the suiteContextIds at the given index.
   */
  @java.lang.Deprecated public com.google.protobuf.ByteString
      getSuiteContextIdsBytes(int index) {
    return suiteContextIds_.getByteString(index);
  }

  public static final int RUN_CONFIG_FIELD_NUMBER = 7;
  private eu.tsystems.mms.tic.testframework.report.model.RunConfig runConfig_;
  /**
   * <code>.data.RunConfig run_config = 7;</code>
   * @return Whether the runConfig field is set.
   */
  @java.lang.Override
  public boolean hasRunConfig() {
    return runConfig_ != null;
  }
  /**
   * <code>.data.RunConfig run_config = 7;</code>
   * @return The runConfig.
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.RunConfig getRunConfig() {
    return runConfig_ == null ? eu.tsystems.mms.tic.testframework.report.model.RunConfig.getDefaultInstance() : runConfig_;
  }
  /**
   * <code>.data.RunConfig run_config = 7;</code>
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.RunConfigOrBuilder getRunConfigOrBuilder() {
    return getRunConfig();
  }

  public static final int PROJECT_ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object projectId_;
  /**
   * <code>string project_Id = 8;</code>
   * @return The projectId.
   */
  @java.lang.Override
  public java.lang.String getProjectId() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectId_ = s;
      return s;
    }
  }
  /**
   * <code>string project_Id = 8;</code>
   * @return The bytes for projectId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectIdBytes() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_ID_FIELD_NUMBER = 9;
  private volatile java.lang.Object jobId_;
  /**
   * <code>string job_Id = 9;</code>
   * @return The jobId.
   */
  @java.lang.Override
  public java.lang.String getJobId() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobId_ = s;
      return s;
    }
  }
  /**
   * <code>string job_Id = 9;</code>
   * @return The bytes for jobId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobIdBytes() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUN_ID_FIELD_NUMBER = 10;
  private volatile java.lang.Object runId_;
  /**
   * <code>string run_Id = 10;</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runId_ = s;
      return s;
    }
  }
  /**
   * <code>string run_Id = 10;</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_ID_FIELD_NUMBER = 11;
  private volatile java.lang.Object taskId_;
  /**
   * <code>string task_Id = 11;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_Id = 11;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCLUSIVE_SESSION_CONTEXT_IDS_FIELD_NUMBER = 12;
  private com.google.protobuf.LazyStringList exclusiveSessionContextIds_;
  /**
   * <code>repeated string exclusive_session_context_ids = 12;</code>
   * @return A list containing the exclusiveSessionContextIds.
   */
  public com.google.protobuf.ProtocolStringList
      getExclusiveSessionContextIdsList() {
    return exclusiveSessionContextIds_;
  }
  /**
   * <code>repeated string exclusive_session_context_ids = 12;</code>
   * @return The count of exclusiveSessionContextIds.
   */
  public int getExclusiveSessionContextIdsCount() {
    return exclusiveSessionContextIds_.size();
  }
  /**
   * <code>repeated string exclusive_session_context_ids = 12;</code>
   * @param index The index of the element to return.
   * @return The exclusiveSessionContextIds at the given index.
   */
  public java.lang.String getExclusiveSessionContextIds(int index) {
    return exclusiveSessionContextIds_.get(index);
  }
  /**
   * <code>repeated string exclusive_session_context_ids = 12;</code>
   * @param index The index of the value to return.
   * @return The bytes of the exclusiveSessionContextIds at the given index.
   */
  public com.google.protobuf.ByteString
      getExclusiveSessionContextIdsBytes(int index) {
    return exclusiveSessionContextIds_.getByteString(index);
  }

  public static final int LOG_MESSAGES_FIELD_NUMBER = 14;
  private java.util.List<eu.tsystems.mms.tic.testframework.report.model.LogMessage> logMessages_;
  /**
   * <code>repeated .data.LogMessage log_messages = 14;</code>
   */
  @java.lang.Override
  public java.util.List<eu.tsystems.mms.tic.testframework.report.model.LogMessage> getLogMessagesList() {
    return logMessages_;
  }
  /**
   * <code>repeated .data.LogMessage log_messages = 14;</code>
   */
  @java.lang.Override
  public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder> 
      getLogMessagesOrBuilderList() {
    return logMessages_;
  }
  /**
   * <code>repeated .data.LogMessage log_messages = 14;</code>
   */
  @java.lang.Override
  public int getLogMessagesCount() {
    return logMessages_.size();
  }
  /**
   * <code>repeated .data.LogMessage log_messages = 14;</code>
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.LogMessage getLogMessages(int index) {
    return logMessages_.get(index);
  }
  /**
   * <code>repeated .data.LogMessage log_messages = 14;</code>
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder getLogMessagesOrBuilder(
      int index) {
    return logMessages_.get(index);
  }

  public static final int ESTIMATED_TESTS_COUNT_FIELD_NUMBER = 15;
  private int estimatedTestsCount_;
  /**
   * <code>int32 estimated_tests_count = 15;</code>
   * @return The estimatedTestsCount.
   */
  @java.lang.Override
  public int getEstimatedTestsCount() {
    return estimatedTestsCount_;
  }

  public static final int FAILURE_CORRIDOR_LIMITS_FIELD_NUMBER = 16;
  private static final class FailureCorridorLimitsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ExecutionContext_FailureCorridorLimitsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> failureCorridorLimits_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetFailureCorridorLimits() {
    if (failureCorridorLimits_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FailureCorridorLimitsDefaultEntryHolder.defaultEntry);
    }
    return failureCorridorLimits_;
  }

  public int getFailureCorridorLimitsCount() {
    return internalGetFailureCorridorLimits().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
   */

  @java.lang.Override
  public boolean containsFailureCorridorLimits(
      int key) {
    
    return internalGetFailureCorridorLimits().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFailureCorridorLimitsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorLimits() {
    return getFailureCorridorLimitsMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorLimitsMap() {
    return internalGetFailureCorridorLimits().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
   */
  @java.lang.Override

  public int getFailureCorridorLimitsOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetFailureCorridorLimits().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
   */
  @java.lang.Override

  public int getFailureCorridorLimitsOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetFailureCorridorLimits().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int FAILURE_CORRIDOR_COUNTS_FIELD_NUMBER = 17;
  private static final class FailureCorridorCountsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ExecutionContext_FailureCorridorCountsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> failureCorridorCounts_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetFailureCorridorCounts() {
    if (failureCorridorCounts_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FailureCorridorCountsDefaultEntryHolder.defaultEntry);
    }
    return failureCorridorCounts_;
  }

  public int getFailureCorridorCountsCount() {
    return internalGetFailureCorridorCounts().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
   */

  @java.lang.Override
  public boolean containsFailureCorridorCounts(
      int key) {
    
    return internalGetFailureCorridorCounts().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFailureCorridorCountsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorCounts() {
    return getFailureCorridorCountsMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorCountsMap() {
    return internalGetFailureCorridorCounts().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
   */
  @java.lang.Override

  public int getFailureCorridorCountsOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetFailureCorridorCounts().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
   */
  @java.lang.Override

  public int getFailureCorridorCountsOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetFailureCorridorCounts().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (contextValues_ != null) {
      output.writeMessage(1, getContextValues());
    }
    for (int i = 0; i < suiteContextIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, suiteContextIds_.getRaw(i));
    }
    if (runConfig_ != null) {
      output.writeMessage(7, getRunConfig());
    }
    if (!getProjectIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, projectId_);
    }
    if (!getJobIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, jobId_);
    }
    if (!getRunIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, runId_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, taskId_);
    }
    for (int i = 0; i < exclusiveSessionContextIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, exclusiveSessionContextIds_.getRaw(i));
    }
    for (int i = 0; i < logMessages_.size(); i++) {
      output.writeMessage(14, logMessages_.get(i));
    }
    if (estimatedTestsCount_ != 0) {
      output.writeInt32(15, estimatedTestsCount_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetFailureCorridorLimits(),
        FailureCorridorLimitsDefaultEntryHolder.defaultEntry,
        16);
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetFailureCorridorCounts(),
        FailureCorridorCountsDefaultEntryHolder.defaultEntry,
        17);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (contextValues_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getContextValues());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < suiteContextIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(suiteContextIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSuiteContextIdsList().size();
    }
    if (runConfig_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getRunConfig());
    }
    if (!getProjectIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, projectId_);
    }
    if (!getJobIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, jobId_);
    }
    if (!getRunIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, runId_);
    }
    if (!getTaskIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, taskId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < exclusiveSessionContextIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(exclusiveSessionContextIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getExclusiveSessionContextIdsList().size();
    }
    for (int i = 0; i < logMessages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, logMessages_.get(i));
    }
    if (estimatedTestsCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, estimatedTestsCount_);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetFailureCorridorLimits().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      failureCorridorLimits__ = FailureCorridorLimitsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, failureCorridorLimits__);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetFailureCorridorCounts().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      failureCorridorCounts__ = FailureCorridorCountsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, failureCorridorCounts__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.tsystems.mms.tic.testframework.report.model.ExecutionContext)) {
      return super.equals(obj);
    }
    eu.tsystems.mms.tic.testframework.report.model.ExecutionContext other = (eu.tsystems.mms.tic.testframework.report.model.ExecutionContext) obj;

    if (hasContextValues() != other.hasContextValues()) return false;
    if (hasContextValues()) {
      if (!getContextValues()
          .equals(other.getContextValues())) return false;
    }
    if (!getSuiteContextIdsList()
        .equals(other.getSuiteContextIdsList())) return false;
    if (hasRunConfig() != other.hasRunConfig()) return false;
    if (hasRunConfig()) {
      if (!getRunConfig()
          .equals(other.getRunConfig())) return false;
    }
    if (!getProjectId()
        .equals(other.getProjectId())) return false;
    if (!getJobId()
        .equals(other.getJobId())) return false;
    if (!getRunId()
        .equals(other.getRunId())) return false;
    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (!getExclusiveSessionContextIdsList()
        .equals(other.getExclusiveSessionContextIdsList())) return false;
    if (!getLogMessagesList()
        .equals(other.getLogMessagesList())) return false;
    if (getEstimatedTestsCount()
        != other.getEstimatedTestsCount()) return false;
    if (!internalGetFailureCorridorLimits().equals(
        other.internalGetFailureCorridorLimits())) return false;
    if (!internalGetFailureCorridorCounts().equals(
        other.internalGetFailureCorridorCounts())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContextValues()) {
      hash = (37 * hash) + CONTEXT_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getContextValues().hashCode();
    }
    if (getSuiteContextIdsCount() > 0) {
      hash = (37 * hash) + SUITE_CONTEXT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getSuiteContextIdsList().hashCode();
    }
    if (hasRunConfig()) {
      hash = (37 * hash) + RUN_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getRunConfig().hashCode();
    }
    hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProjectId().hashCode();
    hash = (37 * hash) + JOB_ID_FIELD_NUMBER;
    hash = (53 * hash) + getJobId().hashCode();
    hash = (37 * hash) + RUN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRunId().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    if (getExclusiveSessionContextIdsCount() > 0) {
      hash = (37 * hash) + EXCLUSIVE_SESSION_CONTEXT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getExclusiveSessionContextIdsList().hashCode();
    }
    if (getLogMessagesCount() > 0) {
      hash = (37 * hash) + LOG_MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getLogMessagesList().hashCode();
    }
    hash = (37 * hash) + ESTIMATED_TESTS_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getEstimatedTestsCount();
    if (!internalGetFailureCorridorLimits().getMap().isEmpty()) {
      hash = (37 * hash) + FAILURE_CORRIDOR_LIMITS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFailureCorridorLimits().hashCode();
    }
    if (!internalGetFailureCorridorCounts().getMap().isEmpty()) {
      hash = (37 * hash) + FAILURE_CORRIDOR_COUNTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFailureCorridorCounts().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.tsystems.mms.tic.testframework.report.model.ExecutionContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code data.ExecutionContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ExecutionContext)
      eu.tsystems.mms.tic.testframework.report.model.ExecutionContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ExecutionContext_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 16:
          return internalGetFailureCorridorLimits();
        case 17:
          return internalGetFailureCorridorCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 16:
          return internalGetMutableFailureCorridorLimits();
        case 17:
          return internalGetMutableFailureCorridorCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ExecutionContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.class, eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder.class);
    }

    // Construct using eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLogMessagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (contextValuesBuilder_ == null) {
        contextValues_ = null;
      } else {
        contextValues_ = null;
        contextValuesBuilder_ = null;
      }
      suiteContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (runConfigBuilder_ == null) {
        runConfig_ = null;
      } else {
        runConfig_ = null;
        runConfigBuilder_ = null;
      }
      projectId_ = "";

      jobId_ = "";

      runId_ = "";

      taskId_ = "";

      exclusiveSessionContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (logMessagesBuilder_ == null) {
        logMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        logMessagesBuilder_.clear();
      }
      estimatedTestsCount_ = 0;

      internalGetMutableFailureCorridorLimits().clear();
      internalGetMutableFailureCorridorCounts().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_ExecutionContext_descriptor;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionContext getDefaultInstanceForType() {
      return eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.getDefaultInstance();
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionContext build() {
      eu.tsystems.mms.tic.testframework.report.model.ExecutionContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionContext buildPartial() {
      eu.tsystems.mms.tic.testframework.report.model.ExecutionContext result = new eu.tsystems.mms.tic.testframework.report.model.ExecutionContext(this);
      int from_bitField0_ = bitField0_;
      if (contextValuesBuilder_ == null) {
        result.contextValues_ = contextValues_;
      } else {
        result.contextValues_ = contextValuesBuilder_.build();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        suiteContextIds_ = suiteContextIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.suiteContextIds_ = suiteContextIds_;
      if (runConfigBuilder_ == null) {
        result.runConfig_ = runConfig_;
      } else {
        result.runConfig_ = runConfigBuilder_.build();
      }
      result.projectId_ = projectId_;
      result.jobId_ = jobId_;
      result.runId_ = runId_;
      result.taskId_ = taskId_;
      if (((bitField0_ & 0x00000002) != 0)) {
        exclusiveSessionContextIds_ = exclusiveSessionContextIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.exclusiveSessionContextIds_ = exclusiveSessionContextIds_;
      if (logMessagesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          logMessages_ = java.util.Collections.unmodifiableList(logMessages_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.logMessages_ = logMessages_;
      } else {
        result.logMessages_ = logMessagesBuilder_.build();
      }
      result.estimatedTestsCount_ = estimatedTestsCount_;
      result.failureCorridorLimits_ = internalGetFailureCorridorLimits();
      result.failureCorridorLimits_.makeImmutable();
      result.failureCorridorCounts_ = internalGetFailureCorridorCounts();
      result.failureCorridorCounts_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.tsystems.mms.tic.testframework.report.model.ExecutionContext) {
        return mergeFrom((eu.tsystems.mms.tic.testframework.report.model.ExecutionContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.tsystems.mms.tic.testframework.report.model.ExecutionContext other) {
      if (other == eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.getDefaultInstance()) return this;
      if (other.hasContextValues()) {
        mergeContextValues(other.getContextValues());
      }
      if (!other.suiteContextIds_.isEmpty()) {
        if (suiteContextIds_.isEmpty()) {
          suiteContextIds_ = other.suiteContextIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSuiteContextIdsIsMutable();
          suiteContextIds_.addAll(other.suiteContextIds_);
        }
        onChanged();
      }
      if (other.hasRunConfig()) {
        mergeRunConfig(other.getRunConfig());
      }
      if (!other.getProjectId().isEmpty()) {
        projectId_ = other.projectId_;
        onChanged();
      }
      if (!other.getJobId().isEmpty()) {
        jobId_ = other.jobId_;
        onChanged();
      }
      if (!other.getRunId().isEmpty()) {
        runId_ = other.runId_;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (!other.exclusiveSessionContextIds_.isEmpty()) {
        if (exclusiveSessionContextIds_.isEmpty()) {
          exclusiveSessionContextIds_ = other.exclusiveSessionContextIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureExclusiveSessionContextIdsIsMutable();
          exclusiveSessionContextIds_.addAll(other.exclusiveSessionContextIds_);
        }
        onChanged();
      }
      if (logMessagesBuilder_ == null) {
        if (!other.logMessages_.isEmpty()) {
          if (logMessages_.isEmpty()) {
            logMessages_ = other.logMessages_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureLogMessagesIsMutable();
            logMessages_.addAll(other.logMessages_);
          }
          onChanged();
        }
      } else {
        if (!other.logMessages_.isEmpty()) {
          if (logMessagesBuilder_.isEmpty()) {
            logMessagesBuilder_.dispose();
            logMessagesBuilder_ = null;
            logMessages_ = other.logMessages_;
            bitField0_ = (bitField0_ & ~0x00000004);
            logMessagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLogMessagesFieldBuilder() : null;
          } else {
            logMessagesBuilder_.addAllMessages(other.logMessages_);
          }
        }
      }
      if (other.getEstimatedTestsCount() != 0) {
        setEstimatedTestsCount(other.getEstimatedTestsCount());
      }
      internalGetMutableFailureCorridorLimits().mergeFrom(
          other.internalGetFailureCorridorLimits());
      internalGetMutableFailureCorridorCounts().mergeFrom(
          other.internalGetFailureCorridorCounts());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.tsystems.mms.tic.testframework.report.model.ExecutionContext parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.tsystems.mms.tic.testframework.report.model.ExecutionContext) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private eu.tsystems.mms.tic.testframework.report.model.ContextValues contextValues_;
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.ContextValues, eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder, eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder> contextValuesBuilder_;
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     * @return Whether the contextValues field is set.
     */
    public boolean hasContextValues() {
      return contextValuesBuilder_ != null || contextValues_ != null;
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     * @return The contextValues.
     */
    public eu.tsystems.mms.tic.testframework.report.model.ContextValues getContextValues() {
      if (contextValuesBuilder_ == null) {
        return contextValues_ == null ? eu.tsystems.mms.tic.testframework.report.model.ContextValues.getDefaultInstance() : contextValues_;
      } else {
        return contextValuesBuilder_.getMessage();
      }
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     */
    public Builder setContextValues(eu.tsystems.mms.tic.testframework.report.model.ContextValues value) {
      if (contextValuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contextValues_ = value;
        onChanged();
      } else {
        contextValuesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     */
    public Builder setContextValues(
        eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder builderForValue) {
      if (contextValuesBuilder_ == null) {
        contextValues_ = builderForValue.build();
        onChanged();
      } else {
        contextValuesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     */
    public Builder mergeContextValues(eu.tsystems.mms.tic.testframework.report.model.ContextValues value) {
      if (contextValuesBuilder_ == null) {
        if (contextValues_ != null) {
          contextValues_ =
            eu.tsystems.mms.tic.testframework.report.model.ContextValues.newBuilder(contextValues_).mergeFrom(value).buildPartial();
        } else {
          contextValues_ = value;
        }
        onChanged();
      } else {
        contextValuesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     */
    public Builder clearContextValues() {
      if (contextValuesBuilder_ == null) {
        contextValues_ = null;
        onChanged();
      } else {
        contextValues_ = null;
        contextValuesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder getContextValuesBuilder() {
      
      onChanged();
      return getContextValuesFieldBuilder().getBuilder();
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder getContextValuesOrBuilder() {
      if (contextValuesBuilder_ != null) {
        return contextValuesBuilder_.getMessageOrBuilder();
      } else {
        return contextValues_ == null ?
            eu.tsystems.mms.tic.testframework.report.model.ContextValues.getDefaultInstance() : contextValues_;
      }
    }
    /**
     * <code>.data.ContextValues context_values = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.ContextValues, eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder, eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder> 
        getContextValuesFieldBuilder() {
      if (contextValuesBuilder_ == null) {
        contextValuesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.ContextValues, eu.tsystems.mms.tic.testframework.report.model.ContextValues.Builder, eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder>(
                getContextValues(),
                getParentForChildren(),
                isClean());
        contextValues_ = null;
      }
      return contextValuesBuilder_;
    }

    private com.google.protobuf.LazyStringList suiteContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSuiteContextIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        suiteContextIds_ = new com.google.protobuf.LazyStringArrayList(suiteContextIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @return A list containing the suiteContextIds.
     */
    @java.lang.Deprecated public com.google.protobuf.ProtocolStringList
        getSuiteContextIdsList() {
      return suiteContextIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @return The count of suiteContextIds.
     */
    @java.lang.Deprecated public int getSuiteContextIdsCount() {
      return suiteContextIds_.size();
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @param index The index of the element to return.
     * @return The suiteContextIds at the given index.
     */
    @java.lang.Deprecated public java.lang.String getSuiteContextIds(int index) {
      return suiteContextIds_.get(index);
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @param index The index of the value to return.
     * @return The bytes of the suiteContextIds at the given index.
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getSuiteContextIdsBytes(int index) {
      return suiteContextIds_.getByteString(index);
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @param index The index to set the value at.
     * @param value The suiteContextIds to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setSuiteContextIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSuiteContextIdsIsMutable();
      suiteContextIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @param value The suiteContextIds to add.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder addSuiteContextIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSuiteContextIdsIsMutable();
      suiteContextIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @param values The suiteContextIds to add.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder addAllSuiteContextIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureSuiteContextIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, suiteContextIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearSuiteContextIds() {
      suiteContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    repeated string merged_class_context_ids = 3 [deprecated = true];
     *    repeated ContextClip exit_points = 4 [deprecated = true];
     *    repeated ContextClip failure_ascpects = 5 [deprecated = true];
     * </pre>
     *
     * <code>repeated string suite_context_ids = 6 [deprecated = true];</code>
     * @param value The bytes of the suiteContextIds to add.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder addSuiteContextIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSuiteContextIdsIsMutable();
      suiteContextIds_.add(value);
      onChanged();
      return this;
    }

    private eu.tsystems.mms.tic.testframework.report.model.RunConfig runConfig_;
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.RunConfig, eu.tsystems.mms.tic.testframework.report.model.RunConfig.Builder, eu.tsystems.mms.tic.testframework.report.model.RunConfigOrBuilder> runConfigBuilder_;
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     * @return Whether the runConfig field is set.
     */
    public boolean hasRunConfig() {
      return runConfigBuilder_ != null || runConfig_ != null;
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     * @return The runConfig.
     */
    public eu.tsystems.mms.tic.testframework.report.model.RunConfig getRunConfig() {
      if (runConfigBuilder_ == null) {
        return runConfig_ == null ? eu.tsystems.mms.tic.testframework.report.model.RunConfig.getDefaultInstance() : runConfig_;
      } else {
        return runConfigBuilder_.getMessage();
      }
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     */
    public Builder setRunConfig(eu.tsystems.mms.tic.testframework.report.model.RunConfig value) {
      if (runConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        runConfig_ = value;
        onChanged();
      } else {
        runConfigBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     */
    public Builder setRunConfig(
        eu.tsystems.mms.tic.testframework.report.model.RunConfig.Builder builderForValue) {
      if (runConfigBuilder_ == null) {
        runConfig_ = builderForValue.build();
        onChanged();
      } else {
        runConfigBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     */
    public Builder mergeRunConfig(eu.tsystems.mms.tic.testframework.report.model.RunConfig value) {
      if (runConfigBuilder_ == null) {
        if (runConfig_ != null) {
          runConfig_ =
            eu.tsystems.mms.tic.testframework.report.model.RunConfig.newBuilder(runConfig_).mergeFrom(value).buildPartial();
        } else {
          runConfig_ = value;
        }
        onChanged();
      } else {
        runConfigBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     */
    public Builder clearRunConfig() {
      if (runConfigBuilder_ == null) {
        runConfig_ = null;
        onChanged();
      } else {
        runConfig_ = null;
        runConfigBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.RunConfig.Builder getRunConfigBuilder() {
      
      onChanged();
      return getRunConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.RunConfigOrBuilder getRunConfigOrBuilder() {
      if (runConfigBuilder_ != null) {
        return runConfigBuilder_.getMessageOrBuilder();
      } else {
        return runConfig_ == null ?
            eu.tsystems.mms.tic.testframework.report.model.RunConfig.getDefaultInstance() : runConfig_;
      }
    }
    /**
     * <code>.data.RunConfig run_config = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.RunConfig, eu.tsystems.mms.tic.testframework.report.model.RunConfig.Builder, eu.tsystems.mms.tic.testframework.report.model.RunConfigOrBuilder> 
        getRunConfigFieldBuilder() {
      if (runConfigBuilder_ == null) {
        runConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.RunConfig, eu.tsystems.mms.tic.testframework.report.model.RunConfig.Builder, eu.tsystems.mms.tic.testframework.report.model.RunConfigOrBuilder>(
                getRunConfig(),
                getParentForChildren(),
                isClean());
        runConfig_ = null;
      }
      return runConfigBuilder_;
    }

    private java.lang.Object projectId_ = "";
    /**
     * <code>string project_Id = 8;</code>
     * @return The projectId.
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string project_Id = 8;</code>
     * @return The bytes for projectId.
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string project_Id = 8;</code>
     * @param value The projectId to set.
     * @return This builder for chaining.
     */
    public Builder setProjectId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string project_Id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectId() {
      
      projectId_ = getDefaultInstance().getProjectId();
      onChanged();
      return this;
    }
    /**
     * <code>string project_Id = 8;</code>
     * @param value The bytes for projectId to set.
     * @return This builder for chaining.
     */
    public Builder setProjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobId_ = "";
    /**
     * <code>string job_Id = 9;</code>
     * @return The jobId.
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string job_Id = 9;</code>
     * @return The bytes for jobId.
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_Id = 9;</code>
     * @param value The jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string job_Id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobId() {
      
      jobId_ = getDefaultInstance().getJobId();
      onChanged();
      return this;
    }
    /**
     * <code>string job_Id = 9;</code>
     * @param value The bytes for jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object runId_ = "";
    /**
     * <code>string run_Id = 10;</code>
     * @return The runId.
     */
    public java.lang.String getRunId() {
      java.lang.Object ref = runId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string run_Id = 10;</code>
     * @return The bytes for runId.
     */
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      java.lang.Object ref = runId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string run_Id = 10;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      runId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string run_Id = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      
      runId_ = getDefaultInstance().getRunId();
      onChanged();
      return this;
    }
    /**
     * <code>string run_Id = 10;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      runId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <code>string task_Id = 11;</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_Id = 11;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_Id = 11;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task_Id = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <code>string task_Id = 11;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList exclusiveSessionContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureExclusiveSessionContextIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        exclusiveSessionContextIds_ = new com.google.protobuf.LazyStringArrayList(exclusiveSessionContextIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @return A list containing the exclusiveSessionContextIds.
     */
    public com.google.protobuf.ProtocolStringList
        getExclusiveSessionContextIdsList() {
      return exclusiveSessionContextIds_.getUnmodifiableView();
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @return The count of exclusiveSessionContextIds.
     */
    public int getExclusiveSessionContextIdsCount() {
      return exclusiveSessionContextIds_.size();
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @param index The index of the element to return.
     * @return The exclusiveSessionContextIds at the given index.
     */
    public java.lang.String getExclusiveSessionContextIds(int index) {
      return exclusiveSessionContextIds_.get(index);
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @param index The index of the value to return.
     * @return The bytes of the exclusiveSessionContextIds at the given index.
     */
    public com.google.protobuf.ByteString
        getExclusiveSessionContextIdsBytes(int index) {
      return exclusiveSessionContextIds_.getByteString(index);
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @param index The index to set the value at.
     * @param value The exclusiveSessionContextIds to set.
     * @return This builder for chaining.
     */
    public Builder setExclusiveSessionContextIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureExclusiveSessionContextIdsIsMutable();
      exclusiveSessionContextIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @param value The exclusiveSessionContextIds to add.
     * @return This builder for chaining.
     */
    public Builder addExclusiveSessionContextIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureExclusiveSessionContextIdsIsMutable();
      exclusiveSessionContextIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @param values The exclusiveSessionContextIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllExclusiveSessionContextIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureExclusiveSessionContextIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, exclusiveSessionContextIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearExclusiveSessionContextIds() {
      exclusiveSessionContextIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string exclusive_session_context_ids = 12;</code>
     * @param value The bytes of the exclusiveSessionContextIds to add.
     * @return This builder for chaining.
     */
    public Builder addExclusiveSessionContextIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureExclusiveSessionContextIdsIsMutable();
      exclusiveSessionContextIds_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<eu.tsystems.mms.tic.testframework.report.model.LogMessage> logMessages_ =
      java.util.Collections.emptyList();
    private void ensureLogMessagesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        logMessages_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.LogMessage>(logMessages_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.LogMessage, eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder, eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder> logMessagesBuilder_;

    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.LogMessage> getLogMessagesList() {
      if (logMessagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(logMessages_);
      } else {
        return logMessagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public int getLogMessagesCount() {
      if (logMessagesBuilder_ == null) {
        return logMessages_.size();
      } else {
        return logMessagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.LogMessage getLogMessages(int index) {
      if (logMessagesBuilder_ == null) {
        return logMessages_.get(index);
      } else {
        return logMessagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder setLogMessages(
        int index, eu.tsystems.mms.tic.testframework.report.model.LogMessage value) {
      if (logMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogMessagesIsMutable();
        logMessages_.set(index, value);
        onChanged();
      } else {
        logMessagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder setLogMessages(
        int index, eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder builderForValue) {
      if (logMessagesBuilder_ == null) {
        ensureLogMessagesIsMutable();
        logMessages_.set(index, builderForValue.build());
        onChanged();
      } else {
        logMessagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder addLogMessages(eu.tsystems.mms.tic.testframework.report.model.LogMessage value) {
      if (logMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogMessagesIsMutable();
        logMessages_.add(value);
        onChanged();
      } else {
        logMessagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder addLogMessages(
        int index, eu.tsystems.mms.tic.testframework.report.model.LogMessage value) {
      if (logMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogMessagesIsMutable();
        logMessages_.add(index, value);
        onChanged();
      } else {
        logMessagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder addLogMessages(
        eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder builderForValue) {
      if (logMessagesBuilder_ == null) {
        ensureLogMessagesIsMutable();
        logMessages_.add(builderForValue.build());
        onChanged();
      } else {
        logMessagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder addLogMessages(
        int index, eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder builderForValue) {
      if (logMessagesBuilder_ == null) {
        ensureLogMessagesIsMutable();
        logMessages_.add(index, builderForValue.build());
        onChanged();
      } else {
        logMessagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder addAllLogMessages(
        java.lang.Iterable<? extends eu.tsystems.mms.tic.testframework.report.model.LogMessage> values) {
      if (logMessagesBuilder_ == null) {
        ensureLogMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, logMessages_);
        onChanged();
      } else {
        logMessagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder clearLogMessages() {
      if (logMessagesBuilder_ == null) {
        logMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        logMessagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public Builder removeLogMessages(int index) {
      if (logMessagesBuilder_ == null) {
        ensureLogMessagesIsMutable();
        logMessages_.remove(index);
        onChanged();
      } else {
        logMessagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder getLogMessagesBuilder(
        int index) {
      return getLogMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder getLogMessagesOrBuilder(
        int index) {
      if (logMessagesBuilder_ == null) {
        return logMessages_.get(index);  } else {
        return logMessagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder> 
         getLogMessagesOrBuilderList() {
      if (logMessagesBuilder_ != null) {
        return logMessagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(logMessages_);
      }
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder addLogMessagesBuilder() {
      return getLogMessagesFieldBuilder().addBuilder(
          eu.tsystems.mms.tic.testframework.report.model.LogMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder addLogMessagesBuilder(
        int index) {
      return getLogMessagesFieldBuilder().addBuilder(
          index, eu.tsystems.mms.tic.testframework.report.model.LogMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .data.LogMessage log_messages = 14;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder> 
         getLogMessagesBuilderList() {
      return getLogMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.LogMessage, eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder, eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder> 
        getLogMessagesFieldBuilder() {
      if (logMessagesBuilder_ == null) {
        logMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.LogMessage, eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder, eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder>(
                logMessages_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        logMessages_ = null;
      }
      return logMessagesBuilder_;
    }

    private int estimatedTestsCount_ ;
    /**
     * <code>int32 estimated_tests_count = 15;</code>
     * @return The estimatedTestsCount.
     */
    @java.lang.Override
    public int getEstimatedTestsCount() {
      return estimatedTestsCount_;
    }
    /**
     * <code>int32 estimated_tests_count = 15;</code>
     * @param value The estimatedTestsCount to set.
     * @return This builder for chaining.
     */
    public Builder setEstimatedTestsCount(int value) {
      
      estimatedTestsCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 estimated_tests_count = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearEstimatedTestsCount() {
      
      estimatedTestsCount_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> failureCorridorLimits_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetFailureCorridorLimits() {
      if (failureCorridorLimits_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FailureCorridorLimitsDefaultEntryHolder.defaultEntry);
      }
      return failureCorridorLimits_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableFailureCorridorLimits() {
      onChanged();;
      if (failureCorridorLimits_ == null) {
        failureCorridorLimits_ = com.google.protobuf.MapField.newMapField(
            FailureCorridorLimitsDefaultEntryHolder.defaultEntry);
      }
      if (!failureCorridorLimits_.isMutable()) {
        failureCorridorLimits_ = failureCorridorLimits_.copy();
      }
      return failureCorridorLimits_;
    }

    public int getFailureCorridorLimitsCount() {
      return internalGetFailureCorridorLimits().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
     */

    @java.lang.Override
    public boolean containsFailureCorridorLimits(
        int key) {
      
      return internalGetFailureCorridorLimits().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFailureCorridorLimitsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorLimits() {
      return getFailureCorridorLimitsMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorLimitsMap() {
      return internalGetFailureCorridorLimits().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
     */
    @java.lang.Override

    public int getFailureCorridorLimitsOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetFailureCorridorLimits().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
     */
    @java.lang.Override

    public int getFailureCorridorLimitsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetFailureCorridorLimits().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFailureCorridorLimits() {
      internalGetMutableFailureCorridorLimits().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
     */

    public Builder removeFailureCorridorLimits(
        int key) {
      
      internalGetMutableFailureCorridorLimits().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableFailureCorridorLimits() {
      return internalGetMutableFailureCorridorLimits().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
     */
    public Builder putFailureCorridorLimits(
        int key,
        int value) {
      
      
      internalGetMutableFailureCorridorLimits().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_limits = 16;</code>
     */

    public Builder putAllFailureCorridorLimits(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableFailureCorridorLimits().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> failureCorridorCounts_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetFailureCorridorCounts() {
      if (failureCorridorCounts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FailureCorridorCountsDefaultEntryHolder.defaultEntry);
      }
      return failureCorridorCounts_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableFailureCorridorCounts() {
      onChanged();;
      if (failureCorridorCounts_ == null) {
        failureCorridorCounts_ = com.google.protobuf.MapField.newMapField(
            FailureCorridorCountsDefaultEntryHolder.defaultEntry);
      }
      if (!failureCorridorCounts_.isMutable()) {
        failureCorridorCounts_ = failureCorridorCounts_.copy();
      }
      return failureCorridorCounts_;
    }

    public int getFailureCorridorCountsCount() {
      return internalGetFailureCorridorCounts().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
     */

    @java.lang.Override
    public boolean containsFailureCorridorCounts(
        int key) {
      
      return internalGetFailureCorridorCounts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFailureCorridorCountsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorCounts() {
      return getFailureCorridorCountsMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Integer> getFailureCorridorCountsMap() {
      return internalGetFailureCorridorCounts().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
     */
    @java.lang.Override

    public int getFailureCorridorCountsOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetFailureCorridorCounts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
     */
    @java.lang.Override

    public int getFailureCorridorCountsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetFailureCorridorCounts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFailureCorridorCounts() {
      internalGetMutableFailureCorridorCounts().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
     */

    public Builder removeFailureCorridorCounts(
        int key) {
      
      internalGetMutableFailureCorridorCounts().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableFailureCorridorCounts() {
      return internalGetMutableFailureCorridorCounts().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
     */
    public Builder putFailureCorridorCounts(
        int key,
        int value) {
      
      
      internalGetMutableFailureCorridorCounts().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; failure_corridor_counts = 17;</code>
     */

    public Builder putAllFailureCorridorCounts(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableFailureCorridorCounts().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ExecutionContext)
  }

  // @@protoc_insertion_point(class_scope:data.ExecutionContext)
  private static final eu.tsystems.mms.tic.testframework.report.model.ExecutionContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.tsystems.mms.tic.testframework.report.model.ExecutionContext();
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutionContext>
      PARSER = new com.google.protobuf.AbstractParser<ExecutionContext>() {
    @java.lang.Override
    public ExecutionContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecutionContext(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecutionContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutionContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.ExecutionContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

