// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package eu.tsystems.mms.tic.testframework.report.model;

/**
 * Protobuf type {@code data.ExecutionAggregate}
 */
public  final class ExecutionAggregate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.ExecutionAggregate)
    ExecutionAggregateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutionAggregate.newBuilder() to construct.
  private ExecutionAggregate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutionAggregate() {
    suiteContexts_ = java.util.Collections.emptyList();
    testContexts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecutionAggregate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecutionAggregate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder subBuilder = null;
            if (executionContext_ != null) {
              subBuilder = executionContext_.toBuilder();
            }
            executionContext_ = input.readMessage(eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(executionContext_);
              executionContext_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              suiteContexts_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.SuiteContext>();
              mutable_bitField0_ |= 0x00000001;
            }
            suiteContexts_.add(
                input.readMessage(eu.tsystems.mms.tic.testframework.report.model.SuiteContext.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              testContexts_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.TestContext>();
              mutable_bitField0_ |= 0x00000002;
            }
            testContexts_.add(
                input.readMessage(eu.tsystems.mms.tic.testframework.report.model.TestContext.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        suiteContexts_ = java.util.Collections.unmodifiableList(suiteContexts_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        testContexts_ = java.util.Collections.unmodifiableList(testContexts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ExecutionAggregate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ExecutionAggregate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate.class, eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate.Builder.class);
  }

  public static final int EXECUTION_CONTEXT_FIELD_NUMBER = 1;
  private eu.tsystems.mms.tic.testframework.report.model.ExecutionContext executionContext_;
  /**
   * <code>.data.ExecutionContext execution_context = 1;</code>
   * @return Whether the executionContext field is set.
   */
  public boolean hasExecutionContext() {
    return executionContext_ != null;
  }
  /**
   * <code>.data.ExecutionContext execution_context = 1;</code>
   * @return The executionContext.
   */
  public eu.tsystems.mms.tic.testframework.report.model.ExecutionContext getExecutionContext() {
    return executionContext_ == null ? eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.getDefaultInstance() : executionContext_;
  }
  /**
   * <code>.data.ExecutionContext execution_context = 1;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.ExecutionContextOrBuilder getExecutionContextOrBuilder() {
    return getExecutionContext();
  }

  public static final int SUITE_CONTEXTS_FIELD_NUMBER = 2;
  private java.util.List<eu.tsystems.mms.tic.testframework.report.model.SuiteContext> suiteContexts_;
  /**
   * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
   */
  public java.util.List<eu.tsystems.mms.tic.testframework.report.model.SuiteContext> getSuiteContextsList() {
    return suiteContexts_;
  }
  /**
   * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
   */
  public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.SuiteContextOrBuilder> 
      getSuiteContextsOrBuilderList() {
    return suiteContexts_;
  }
  /**
   * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
   */
  public int getSuiteContextsCount() {
    return suiteContexts_.size();
  }
  /**
   * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.SuiteContext getSuiteContexts(int index) {
    return suiteContexts_.get(index);
  }
  /**
   * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.SuiteContextOrBuilder getSuiteContextsOrBuilder(
      int index) {
    return suiteContexts_.get(index);
  }

  public static final int TEST_CONTEXTS_FIELD_NUMBER = 3;
  private java.util.List<eu.tsystems.mms.tic.testframework.report.model.TestContext> testContexts_;
  /**
   * <code>repeated .data.TestContext test_contexts = 3;</code>
   */
  public java.util.List<eu.tsystems.mms.tic.testframework.report.model.TestContext> getTestContextsList() {
    return testContexts_;
  }
  /**
   * <code>repeated .data.TestContext test_contexts = 3;</code>
   */
  public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.TestContextOrBuilder> 
      getTestContextsOrBuilderList() {
    return testContexts_;
  }
  /**
   * <code>repeated .data.TestContext test_contexts = 3;</code>
   */
  public int getTestContextsCount() {
    return testContexts_.size();
  }
  /**
   * <code>repeated .data.TestContext test_contexts = 3;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.TestContext getTestContexts(int index) {
    return testContexts_.get(index);
  }
  /**
   * <code>repeated .data.TestContext test_contexts = 3;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.TestContextOrBuilder getTestContextsOrBuilder(
      int index) {
    return testContexts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (executionContext_ != null) {
      output.writeMessage(1, getExecutionContext());
    }
    for (int i = 0; i < suiteContexts_.size(); i++) {
      output.writeMessage(2, suiteContexts_.get(i));
    }
    for (int i = 0; i < testContexts_.size(); i++) {
      output.writeMessage(3, testContexts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (executionContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getExecutionContext());
    }
    for (int i = 0; i < suiteContexts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, suiteContexts_.get(i));
    }
    for (int i = 0; i < testContexts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, testContexts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate)) {
      return super.equals(obj);
    }
    eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate other = (eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate) obj;

    if (hasExecutionContext() != other.hasExecutionContext()) return false;
    if (hasExecutionContext()) {
      if (!getExecutionContext()
          .equals(other.getExecutionContext())) return false;
    }
    if (!getSuiteContextsList()
        .equals(other.getSuiteContextsList())) return false;
    if (!getTestContextsList()
        .equals(other.getTestContextsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasExecutionContext()) {
      hash = (37 * hash) + EXECUTION_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getExecutionContext().hashCode();
    }
    if (getSuiteContextsCount() > 0) {
      hash = (37 * hash) + SUITE_CONTEXTS_FIELD_NUMBER;
      hash = (53 * hash) + getSuiteContextsList().hashCode();
    }
    if (getTestContextsCount() > 0) {
      hash = (37 * hash) + TEST_CONTEXTS_FIELD_NUMBER;
      hash = (53 * hash) + getTestContextsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code data.ExecutionAggregate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.ExecutionAggregate)
      eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ExecutionAggregate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ExecutionAggregate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate.class, eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate.Builder.class);
    }

    // Construct using eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSuiteContextsFieldBuilder();
        getTestContextsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (executionContextBuilder_ == null) {
        executionContext_ = null;
      } else {
        executionContext_ = null;
        executionContextBuilder_ = null;
      }
      if (suiteContextsBuilder_ == null) {
        suiteContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        suiteContextsBuilder_.clear();
      }
      if (testContextsBuilder_ == null) {
        testContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        testContextsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.tsystems.mms.tic.testframework.report.model.Report.internal_static_data_ExecutionAggregate_descriptor;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate getDefaultInstanceForType() {
      return eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate.getDefaultInstance();
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate build() {
      eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate buildPartial() {
      eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate result = new eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate(this);
      int from_bitField0_ = bitField0_;
      if (executionContextBuilder_ == null) {
        result.executionContext_ = executionContext_;
      } else {
        result.executionContext_ = executionContextBuilder_.build();
      }
      if (suiteContextsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          suiteContexts_ = java.util.Collections.unmodifiableList(suiteContexts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.suiteContexts_ = suiteContexts_;
      } else {
        result.suiteContexts_ = suiteContextsBuilder_.build();
      }
      if (testContextsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          testContexts_ = java.util.Collections.unmodifiableList(testContexts_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.testContexts_ = testContexts_;
      } else {
        result.testContexts_ = testContextsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate) {
        return mergeFrom((eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate other) {
      if (other == eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate.getDefaultInstance()) return this;
      if (other.hasExecutionContext()) {
        mergeExecutionContext(other.getExecutionContext());
      }
      if (suiteContextsBuilder_ == null) {
        if (!other.suiteContexts_.isEmpty()) {
          if (suiteContexts_.isEmpty()) {
            suiteContexts_ = other.suiteContexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSuiteContextsIsMutable();
            suiteContexts_.addAll(other.suiteContexts_);
          }
          onChanged();
        }
      } else {
        if (!other.suiteContexts_.isEmpty()) {
          if (suiteContextsBuilder_.isEmpty()) {
            suiteContextsBuilder_.dispose();
            suiteContextsBuilder_ = null;
            suiteContexts_ = other.suiteContexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            suiteContextsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSuiteContextsFieldBuilder() : null;
          } else {
            suiteContextsBuilder_.addAllMessages(other.suiteContexts_);
          }
        }
      }
      if (testContextsBuilder_ == null) {
        if (!other.testContexts_.isEmpty()) {
          if (testContexts_.isEmpty()) {
            testContexts_ = other.testContexts_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTestContextsIsMutable();
            testContexts_.addAll(other.testContexts_);
          }
          onChanged();
        }
      } else {
        if (!other.testContexts_.isEmpty()) {
          if (testContextsBuilder_.isEmpty()) {
            testContextsBuilder_.dispose();
            testContextsBuilder_ = null;
            testContexts_ = other.testContexts_;
            bitField0_ = (bitField0_ & ~0x00000002);
            testContextsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTestContextsFieldBuilder() : null;
          } else {
            testContextsBuilder_.addAllMessages(other.testContexts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private eu.tsystems.mms.tic.testframework.report.model.ExecutionContext executionContext_;
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.ExecutionContext, eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder, eu.tsystems.mms.tic.testframework.report.model.ExecutionContextOrBuilder> executionContextBuilder_;
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     * @return Whether the executionContext field is set.
     */
    public boolean hasExecutionContext() {
      return executionContextBuilder_ != null || executionContext_ != null;
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     * @return The executionContext.
     */
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionContext getExecutionContext() {
      if (executionContextBuilder_ == null) {
        return executionContext_ == null ? eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.getDefaultInstance() : executionContext_;
      } else {
        return executionContextBuilder_.getMessage();
      }
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     */
    public Builder setExecutionContext(eu.tsystems.mms.tic.testframework.report.model.ExecutionContext value) {
      if (executionContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        executionContext_ = value;
        onChanged();
      } else {
        executionContextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     */
    public Builder setExecutionContext(
        eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder builderForValue) {
      if (executionContextBuilder_ == null) {
        executionContext_ = builderForValue.build();
        onChanged();
      } else {
        executionContextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     */
    public Builder mergeExecutionContext(eu.tsystems.mms.tic.testframework.report.model.ExecutionContext value) {
      if (executionContextBuilder_ == null) {
        if (executionContext_ != null) {
          executionContext_ =
            eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.newBuilder(executionContext_).mergeFrom(value).buildPartial();
        } else {
          executionContext_ = value;
        }
        onChanged();
      } else {
        executionContextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     */
    public Builder clearExecutionContext() {
      if (executionContextBuilder_ == null) {
        executionContext_ = null;
        onChanged();
      } else {
        executionContext_ = null;
        executionContextBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder getExecutionContextBuilder() {
      
      onChanged();
      return getExecutionContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.ExecutionContextOrBuilder getExecutionContextOrBuilder() {
      if (executionContextBuilder_ != null) {
        return executionContextBuilder_.getMessageOrBuilder();
      } else {
        return executionContext_ == null ?
            eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.getDefaultInstance() : executionContext_;
      }
    }
    /**
     * <code>.data.ExecutionContext execution_context = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.ExecutionContext, eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder, eu.tsystems.mms.tic.testframework.report.model.ExecutionContextOrBuilder> 
        getExecutionContextFieldBuilder() {
      if (executionContextBuilder_ == null) {
        executionContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.ExecutionContext, eu.tsystems.mms.tic.testframework.report.model.ExecutionContext.Builder, eu.tsystems.mms.tic.testframework.report.model.ExecutionContextOrBuilder>(
                getExecutionContext(),
                getParentForChildren(),
                isClean());
        executionContext_ = null;
      }
      return executionContextBuilder_;
    }

    private java.util.List<eu.tsystems.mms.tic.testframework.report.model.SuiteContext> suiteContexts_ =
      java.util.Collections.emptyList();
    private void ensureSuiteContextsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        suiteContexts_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.SuiteContext>(suiteContexts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.SuiteContext, eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder, eu.tsystems.mms.tic.testframework.report.model.SuiteContextOrBuilder> suiteContextsBuilder_;

    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.SuiteContext> getSuiteContextsList() {
      if (suiteContextsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(suiteContexts_);
      } else {
        return suiteContextsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public int getSuiteContextsCount() {
      if (suiteContextsBuilder_ == null) {
        return suiteContexts_.size();
      } else {
        return suiteContextsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.SuiteContext getSuiteContexts(int index) {
      if (suiteContextsBuilder_ == null) {
        return suiteContexts_.get(index);
      } else {
        return suiteContextsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder setSuiteContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.SuiteContext value) {
      if (suiteContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuiteContextsIsMutable();
        suiteContexts_.set(index, value);
        onChanged();
      } else {
        suiteContextsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder setSuiteContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder builderForValue) {
      if (suiteContextsBuilder_ == null) {
        ensureSuiteContextsIsMutable();
        suiteContexts_.set(index, builderForValue.build());
        onChanged();
      } else {
        suiteContextsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder addSuiteContexts(eu.tsystems.mms.tic.testframework.report.model.SuiteContext value) {
      if (suiteContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuiteContextsIsMutable();
        suiteContexts_.add(value);
        onChanged();
      } else {
        suiteContextsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder addSuiteContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.SuiteContext value) {
      if (suiteContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuiteContextsIsMutable();
        suiteContexts_.add(index, value);
        onChanged();
      } else {
        suiteContextsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder addSuiteContexts(
        eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder builderForValue) {
      if (suiteContextsBuilder_ == null) {
        ensureSuiteContextsIsMutable();
        suiteContexts_.add(builderForValue.build());
        onChanged();
      } else {
        suiteContextsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder addSuiteContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder builderForValue) {
      if (suiteContextsBuilder_ == null) {
        ensureSuiteContextsIsMutable();
        suiteContexts_.add(index, builderForValue.build());
        onChanged();
      } else {
        suiteContextsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder addAllSuiteContexts(
        java.lang.Iterable<? extends eu.tsystems.mms.tic.testframework.report.model.SuiteContext> values) {
      if (suiteContextsBuilder_ == null) {
        ensureSuiteContextsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, suiteContexts_);
        onChanged();
      } else {
        suiteContextsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder clearSuiteContexts() {
      if (suiteContextsBuilder_ == null) {
        suiteContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        suiteContextsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public Builder removeSuiteContexts(int index) {
      if (suiteContextsBuilder_ == null) {
        ensureSuiteContextsIsMutable();
        suiteContexts_.remove(index);
        onChanged();
      } else {
        suiteContextsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder getSuiteContextsBuilder(
        int index) {
      return getSuiteContextsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.SuiteContextOrBuilder getSuiteContextsOrBuilder(
        int index) {
      if (suiteContextsBuilder_ == null) {
        return suiteContexts_.get(index);  } else {
        return suiteContextsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.SuiteContextOrBuilder> 
         getSuiteContextsOrBuilderList() {
      if (suiteContextsBuilder_ != null) {
        return suiteContextsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(suiteContexts_);
      }
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder addSuiteContextsBuilder() {
      return getSuiteContextsFieldBuilder().addBuilder(
          eu.tsystems.mms.tic.testframework.report.model.SuiteContext.getDefaultInstance());
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder addSuiteContextsBuilder(
        int index) {
      return getSuiteContextsFieldBuilder().addBuilder(
          index, eu.tsystems.mms.tic.testframework.report.model.SuiteContext.getDefaultInstance());
    }
    /**
     * <code>repeated .data.SuiteContext suite_contexts = 2;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder> 
         getSuiteContextsBuilderList() {
      return getSuiteContextsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.SuiteContext, eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder, eu.tsystems.mms.tic.testframework.report.model.SuiteContextOrBuilder> 
        getSuiteContextsFieldBuilder() {
      if (suiteContextsBuilder_ == null) {
        suiteContextsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.SuiteContext, eu.tsystems.mms.tic.testframework.report.model.SuiteContext.Builder, eu.tsystems.mms.tic.testframework.report.model.SuiteContextOrBuilder>(
                suiteContexts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        suiteContexts_ = null;
      }
      return suiteContextsBuilder_;
    }

    private java.util.List<eu.tsystems.mms.tic.testframework.report.model.TestContext> testContexts_ =
      java.util.Collections.emptyList();
    private void ensureTestContextsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        testContexts_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.TestContext>(testContexts_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.TestContext, eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder, eu.tsystems.mms.tic.testframework.report.model.TestContextOrBuilder> testContextsBuilder_;

    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.TestContext> getTestContextsList() {
      if (testContextsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(testContexts_);
      } else {
        return testContextsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public int getTestContextsCount() {
      if (testContextsBuilder_ == null) {
        return testContexts_.size();
      } else {
        return testContextsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.TestContext getTestContexts(int index) {
      if (testContextsBuilder_ == null) {
        return testContexts_.get(index);
      } else {
        return testContextsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder setTestContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.TestContext value) {
      if (testContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestContextsIsMutable();
        testContexts_.set(index, value);
        onChanged();
      } else {
        testContextsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder setTestContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder builderForValue) {
      if (testContextsBuilder_ == null) {
        ensureTestContextsIsMutable();
        testContexts_.set(index, builderForValue.build());
        onChanged();
      } else {
        testContextsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder addTestContexts(eu.tsystems.mms.tic.testframework.report.model.TestContext value) {
      if (testContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestContextsIsMutable();
        testContexts_.add(value);
        onChanged();
      } else {
        testContextsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder addTestContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.TestContext value) {
      if (testContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestContextsIsMutable();
        testContexts_.add(index, value);
        onChanged();
      } else {
        testContextsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder addTestContexts(
        eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder builderForValue) {
      if (testContextsBuilder_ == null) {
        ensureTestContextsIsMutable();
        testContexts_.add(builderForValue.build());
        onChanged();
      } else {
        testContextsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder addTestContexts(
        int index, eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder builderForValue) {
      if (testContextsBuilder_ == null) {
        ensureTestContextsIsMutable();
        testContexts_.add(index, builderForValue.build());
        onChanged();
      } else {
        testContextsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder addAllTestContexts(
        java.lang.Iterable<? extends eu.tsystems.mms.tic.testframework.report.model.TestContext> values) {
      if (testContextsBuilder_ == null) {
        ensureTestContextsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, testContexts_);
        onChanged();
      } else {
        testContextsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder clearTestContexts() {
      if (testContextsBuilder_ == null) {
        testContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        testContextsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public Builder removeTestContexts(int index) {
      if (testContextsBuilder_ == null) {
        ensureTestContextsIsMutable();
        testContexts_.remove(index);
        onChanged();
      } else {
        testContextsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder getTestContextsBuilder(
        int index) {
      return getTestContextsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.TestContextOrBuilder getTestContextsOrBuilder(
        int index) {
      if (testContextsBuilder_ == null) {
        return testContexts_.get(index);  } else {
        return testContextsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.TestContextOrBuilder> 
         getTestContextsOrBuilderList() {
      if (testContextsBuilder_ != null) {
        return testContextsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(testContexts_);
      }
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder addTestContextsBuilder() {
      return getTestContextsFieldBuilder().addBuilder(
          eu.tsystems.mms.tic.testframework.report.model.TestContext.getDefaultInstance());
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder addTestContextsBuilder(
        int index) {
      return getTestContextsFieldBuilder().addBuilder(
          index, eu.tsystems.mms.tic.testframework.report.model.TestContext.getDefaultInstance());
    }
    /**
     * <code>repeated .data.TestContext test_contexts = 3;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder> 
         getTestContextsBuilderList() {
      return getTestContextsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.TestContext, eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder, eu.tsystems.mms.tic.testframework.report.model.TestContextOrBuilder> 
        getTestContextsFieldBuilder() {
      if (testContextsBuilder_ == null) {
        testContextsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.TestContext, eu.tsystems.mms.tic.testframework.report.model.TestContext.Builder, eu.tsystems.mms.tic.testframework.report.model.TestContextOrBuilder>(
                testContexts_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        testContexts_ = null;
      }
      return testContextsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.ExecutionAggregate)
  }

  // @@protoc_insertion_point(class_scope:data.ExecutionAggregate)
  private static final eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate();
  }

  public static eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutionAggregate>
      PARSER = new com.google.protobuf.AbstractParser<ExecutionAggregate>() {
    @java.lang.Override
    public ExecutionAggregate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecutionAggregate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecutionAggregate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutionAggregate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.ExecutionAggregate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

