// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

public final class Framework {
  private Framework() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_SuiteContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_SuiteContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ClassContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ClassContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_TestContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_TestContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ExecutionContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ExecutionContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_MethodContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_MethodContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ContextValues_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ContextValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_TestStep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_TestStep_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_TestStepAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_TestStepAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ClickPathEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ClickPathEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_LogMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_LogMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ErrorContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ErrorContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_SessionContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_SessionContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_SessionContext_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_SessionContext_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_RunConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_RunConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_BuildInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_BuildInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_StackTraceCause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_StackTraceCause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ScriptSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ScriptSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ScriptSourceLine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_ScriptSourceLine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_File_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_File_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_data_File_MetaEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_data_File_MetaEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017framework.proto\022\004data\"w\n\014SuiteContext\022" +
      "+\n\016context_values\030\001 \001(\0132\023.data.ContextVa" +
      "lues\022\034\n\020test_context_ids\030\006 \003(\tB\002\030\001\022\034\n\024ex" +
      "ecution_context_id\030\007 \001(\t\"\312\001\n\014ClassContex" +
      "t\022+\n\016context_values\030\001 \001(\0132\023.data.Context" +
      "Values\022\036\n\022method_context_ids\030\006 \003(\tB\002\030\001\022\027" +
      "\n\017full_class_name\030\007 \001(\t\022\027\n\017test_context_" +
      "id\030\t \001(\t\022 \n\024execution_context_id\030\n \001(\tB\002" +
      "\030\001\022\031\n\021test_context_name\030\013 \001(\t\"\225\001\n\013TestCo" +
      "ntext\022+\n\016context_values\030\001 \001(\0132\023.data.Con" +
      "textValues\022\035\n\021class_context_ids\030\006 \003(\tB\002\030" +
      "\001\022\030\n\020suite_context_id\030\007 \001(\t\022 \n\024execution" +
      "_context_id\030\010 \001(\tB\002\030\001\"\266\002\n\020ExecutionConte" +
      "xt\022+\n\016context_values\030\001 \001(\0132\023.data.Contex" +
      "tValues\022\035\n\021suite_context_ids\030\006 \003(\tB\002\030\001\022#" +
      "\n\nrun_config\030\007 \001(\0132\017.data.RunConfig\022\022\n\np" +
      "roject_Id\030\010 \001(\t\022\016\n\006job_Id\030\t \001(\t\022\016\n\006run_I" +
      "d\030\n \001(\t\022\017\n\007task_Id\030\013 \001(\t\022%\n\035exclusive_se" +
      "ssion_context_ids\030\014 \003(\t\022&\n\014log_messages\030" +
      "\016 \003(\0132\020.data.LogMessage\022\035\n\025estimated_tes" +
      "ts_count\030\017 \001(\005\"\224\005\n\rMethodContext\022+\n\016cont" +
      "ext_values\030\001 \001(\0132\023.data.ContextValues\022%\n" +
      "\013method_type\030\007 \001(\0162\020.data.MethodType\022\022\n\n" +
      "parameters\030\010 \003(\t\022\023\n\013method_tags\030\t \003(\t\022\024\n" +
      "\014retry_number\030\n \001(\005\022\030\n\020method_run_index\030" +
      "\013 \001(\005\022\023\n\013thread_name\030\014 \001(\t\022:\n\026failure_co" +
      "rridor_value\030\016 \001(\0162\032.data.FailureCorrido" +
      "rValue\022\030\n\020class_context_id\030\017 \001(\t\022 \n\024exec" +
      "ution_context_id\030\020 \001(\tB\002\030\001\022\r\n\005infos\030\023 \003(" +
      "\t\022\030\n\020priority_message\030\025 \001(\t\022\"\n\032related_m" +
      "ethod_context_ids\030\027 \003(\t\022%\n\035depends_on_me" +
      "thod_context_ids\030\030 \003(\t\022)\n\rerror_context\030" +
      "\031 \001(\0132\022.data.ErrorContext\022\"\n\ntest_steps\030" +
      "\032 \003(\0132\016.data.TestStep\022\033\n\017test_context_id" +
      "\030\033 \001(\tB\002\030\001\022\034\n\020suite_context_id\030\034 \001(\tB\002\030\001" +
      "\022\033\n\023session_context_ids\030\035 \003(\t\022\021\n\tvideo_i" +
      "ds\030\036 \003(\t\022\033\n\023custom_context_json\030  \001(\t\"\272\001" +
      "\n\rContextValues\022\n\n\002id\030\001 \001(\t\022\017\n\007created\030\002" +
      " \001(\003\022\014\n\004name\030\003 \001(\t\022\022\n\nstart_time\030\004 \001(\003\022\020" +
      "\n\010end_time\030\005 \001(\003\022-\n\rresult_status\030\007 \001(\0162" +
      "\026.data.ResultStatusType\022)\n\013exec_status\030\010" +
      " \001(\0162\024.data.ExecStatusType\"I\n\010TestStep\022\014" +
      "\n\004name\030\001 \001(\t\022/\n\021test_step_actions\030\003 \003(\0132" +
      "\024.data.TestStepAction\"\204\002\n\016TestStepAction" +
      "\022\014\n\004name\030\001 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\022.\n\020cli" +
      "ckpath_events\030\005 \003(\0132\024.data.ClickPathEven" +
      "t\022\026\n\016screenshot_ids\030\006 \003(\t\022&\n\014log_message" +
      "s\030\007 \003(\0132\020.data.LogMessage\022/\n\023optional_as" +
      "sertions\030\010 \003(\0132\022.data.ErrorContext\0220\n\024co" +
      "llected_assertions\030\t \003(\0132\022.data.ErrorCon" +
      "text\"]\n\016ClickPathEvent\022&\n\004type\030\001 \001(\0162\030.d" +
      "ata.ClickPathEventType\022\017\n\007subject\030\002 \001(\t\022" +
      "\022\n\nsession_id\030\003 \001(\t\"\252\001\n\nLogMessage\022\"\n\004ty" +
      "pe\030\001 \001(\0162\024.data.LogMessageType\022\023\n\013logger" +
      "_name\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022\021\n\ttimestam" +
      "p\030\004 \001(\003\022\023\n\013thread_name\030\005 \001(\t\022*\n\013stack_tr" +
      "ace\030\006 \003(\0132\025.data.StackTraceCause\"\301\001\n\014Err" +
      "orContext\022)\n\rscript_source\030\007 \001(\0132\022.data." +
      "ScriptSource\0223\n\027execution_object_source\030" +
      "\010 \001(\0132\022.data.ScriptSource\022\020\n\010ticketId\030\t " +
      "\001(\t\022\023\n\013description\030\n \001(\t\022*\n\013stack_trace\030" +
      "\013 \003(\0132\025.data.StackTraceCause\"\337\001\n\016Session" +
      "Context\022+\n\016context_values\030\001 \001(\0132\023.data.C" +
      "ontextValues\022\023\n\013session_key\030\002 \001(\t\022\020\n\010pro" +
      "vider\030\003 \001(\t\0224\n\010metadata\030\004 \003(\0132\".data.Ses" +
      "sionContext.MetadataEntry\022\022\n\nsession_id\030" +
      "\006 \001(\t\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\"c\n\tRunConfig\022\016\n\006runcfg\030\001 " +
      "\001(\t\0221\n\021build_information\030\002 \001(\0132\026.data.Bu" +
      "ildInformation\022\023\n\013report_name\030\003 \001(\t\"\250\001\n\020" +
      "BuildInformation\022\032\n\022build_java_version\030\001" +
      " \001(\t\022\025\n\rbuild_os_name\030\002 \001(\t\022\030\n\020build_os_" +
      "version\030\003 \001(\t\022\027\n\017build_user_name\030\004 \001(\t\022\025" +
      "\n\rbuild_version\030\005 \001(\t\022\027\n\017build_timestamp" +
      "\030\006 \001(\t\"T\n\017StackTraceCause\022\022\n\nclass_name\030" +
      "\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\034\n\024stack_trace_el" +
      "ements\030\003 \003(\t\"k\n\014ScriptSource\022\021\n\tfile_nam" +
      "e\030\001 \001(\t\022\023\n\013method_name\030\002 \001(\t\022%\n\005lines\030\003 " +
      "\003(\0132\026.data.ScriptSourceLine\022\014\n\004mark\030\004 \001(" +
      "\005\"5\n\020ScriptSourceLine\022\014\n\004line\030\001 \001(\t\022\023\n\013l" +
      "ine_number\030\002 \001(\005\"\253\002\n\004File\022\n\n\002id\030\001 \001(\t\022\014\n" +
      "\004size\030\002 \001(\003\022\020\n\010mimetype\030\003 \001(\t\022\025\n\rrelativ" +
      "e_path\030\004 \001(\t\022\031\n\021created_timestamp\030\005 \001(\003\022" +
      "\025\n\rsha1_checksum\030\006 \001(\014\022\"\n\004meta\030\007 \003(\0132\024.d" +
      "ata.File.MetaEntry\022\025\n\rlast_modified\030\t \001(" +
      "\003\022\022\n\nproject_id\030\n \001(\t\022\016\n\006job_id\030\013 \001(\t\022\024\n" +
      "\014is_directory\030\014 \001(\010\022\014\n\004name\030\r \001(\t\032+\n\tMet" +
      "aEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*t" +
      "\n\022ClickPathEventType\022\020\n\014CPET_NOT_SET\020\000\022\017" +
      "\n\013CPET_WINDOW\020\001\022\016\n\nCPET_CLICK\020\002\022\016\n\nCPET_" +
      "VALUE\020\003\022\r\n\tCPET_PAGE\020\004\022\014\n\010CPET_URL\020\005*W\n\016" +
      "LogMessageType\022\013\n\007LMT_OFF\020\000\022\r\n\tLMT_ERROR" +
      "\020\001\022\014\n\010LMT_WARN\020\002\022\014\n\010LMT_INFO\020\003\022\r\n\tLMT_DE" +
      "BUG\020\004*O\n\024FailureCorridorValue\022\017\n\013FCV_NOT" +
      "_SET\020\000\022\014\n\010FCV_HIGH\020\001\022\013\n\007FCV_MID\020\002\022\013\n\007FCV" +
      "_LOW\020\003*G\n\nMethodType\022\016\n\nMT_NOT_SET\020\000\022\017\n\013" +
      "TEST_METHOD\020\001\022\030\n\024CONFIGURATION_METHOD\020\002*" +
      "\252\001\n\016ExecStatusType\022\017\n\013EST_NOT_SET\020\000\022\007\n\003N" +
      "EW\020\001\022\013\n\007PENDING\020\002\022\020\n\014PROVISIONING\020\003\022\013\n\007R" +
      "UNNING\020\004\022\014\n\010FINISHED\020\005\022\013\n\007ABORTED\020\006\022\013\n\007C" +
      "RASHED\020\007\022\013\n\007INVALID\020\010\022\010\n\004VOID\020\t\022\023\n\017ARTIF" +
      "ACT_UPLOAD\020\n*\323\001\n\020ResultStatusType\022\017\n\013RST" +
      "_NOT_SET\020\000\022\n\n\006NO_RUN\020\001\022\010\n\004INFO\020\002\022\013\n\007SKIP" +
      "PED\020\003\022\n\n\006PASSED\020\004\022\r\n\005MINOR\020\005\032\002\010\001\022\n\n\006FAIL" +
      "ED\020\007\022\024\n\014FAILED_MINOR\020\010\032\002\010\001\022\022\n\016FAILED_RET" +
      "RIED\020\t\022\023\n\017FAILED_EXPECTED\020\n\022\020\n\014PASSED_RE" +
      "TRY\020\013\022\023\n\013MINOR_RETRY\020\014\032\002\010\001B2\n.eu.tsystem" +
      "s.mms.tic.testframework.report.modelP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_data_SuiteContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_SuiteContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_SuiteContext_descriptor,
        new java.lang.String[] { "ContextValues", "TestContextIds", "ExecutionContextId", });
    internal_static_data_ClassContext_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_data_ClassContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ClassContext_descriptor,
        new java.lang.String[] { "ContextValues", "MethodContextIds", "FullClassName", "TestContextId", "ExecutionContextId", "TestContextName", });
    internal_static_data_TestContext_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_data_TestContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_TestContext_descriptor,
        new java.lang.String[] { "ContextValues", "ClassContextIds", "SuiteContextId", "ExecutionContextId", });
    internal_static_data_ExecutionContext_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_data_ExecutionContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ExecutionContext_descriptor,
        new java.lang.String[] { "ContextValues", "SuiteContextIds", "RunConfig", "ProjectId", "JobId", "RunId", "TaskId", "ExclusiveSessionContextIds", "LogMessages", "EstimatedTestsCount", });
    internal_static_data_MethodContext_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_data_MethodContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_MethodContext_descriptor,
        new java.lang.String[] { "ContextValues", "MethodType", "Parameters", "MethodTags", "RetryNumber", "MethodRunIndex", "ThreadName", "FailureCorridorValue", "ClassContextId", "ExecutionContextId", "Infos", "PriorityMessage", "RelatedMethodContextIds", "DependsOnMethodContextIds", "ErrorContext", "TestSteps", "TestContextId", "SuiteContextId", "SessionContextIds", "VideoIds", "CustomContextJson", });
    internal_static_data_ContextValues_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_data_ContextValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ContextValues_descriptor,
        new java.lang.String[] { "Id", "Created", "Name", "StartTime", "EndTime", "ResultStatus", "ExecStatus", });
    internal_static_data_TestStep_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_data_TestStep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_TestStep_descriptor,
        new java.lang.String[] { "Name", "TestStepActions", });
    internal_static_data_TestStepAction_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_data_TestStepAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_TestStepAction_descriptor,
        new java.lang.String[] { "Name", "Timestamp", "ClickpathEvents", "ScreenshotIds", "LogMessages", "OptionalAssertions", "CollectedAssertions", });
    internal_static_data_ClickPathEvent_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_data_ClickPathEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ClickPathEvent_descriptor,
        new java.lang.String[] { "Type", "Subject", "SessionId", });
    internal_static_data_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_data_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_LogMessage_descriptor,
        new java.lang.String[] { "Type", "LoggerName", "Message", "Timestamp", "ThreadName", "StackTrace", });
    internal_static_data_ErrorContext_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_data_ErrorContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ErrorContext_descriptor,
        new java.lang.String[] { "ScriptSource", "ExecutionObjectSource", "TicketId", "Description", "StackTrace", });
    internal_static_data_SessionContext_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_data_SessionContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_SessionContext_descriptor,
        new java.lang.String[] { "ContextValues", "SessionKey", "Provider", "Metadata", "SessionId", });
    internal_static_data_SessionContext_MetadataEntry_descriptor =
      internal_static_data_SessionContext_descriptor.getNestedTypes().get(0);
    internal_static_data_SessionContext_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_SessionContext_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_data_RunConfig_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_data_RunConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_RunConfig_descriptor,
        new java.lang.String[] { "Runcfg", "BuildInformation", "ReportName", });
    internal_static_data_BuildInformation_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_data_BuildInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_BuildInformation_descriptor,
        new java.lang.String[] { "BuildJavaVersion", "BuildOsName", "BuildOsVersion", "BuildUserName", "BuildVersion", "BuildTimestamp", });
    internal_static_data_StackTraceCause_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_data_StackTraceCause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_StackTraceCause_descriptor,
        new java.lang.String[] { "ClassName", "Message", "StackTraceElements", });
    internal_static_data_ScriptSource_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_data_ScriptSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ScriptSource_descriptor,
        new java.lang.String[] { "FileName", "MethodName", "Lines", "Mark", });
    internal_static_data_ScriptSourceLine_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_data_ScriptSourceLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_ScriptSourceLine_descriptor,
        new java.lang.String[] { "Line", "LineNumber", });
    internal_static_data_File_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_data_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_File_descriptor,
        new java.lang.String[] { "Id", "Size", "Mimetype", "RelativePath", "CreatedTimestamp", "Sha1Checksum", "Meta", "LastModified", "ProjectId", "JobId", "IsDirectory", "Name", });
    internal_static_data_File_MetaEntry_descriptor =
      internal_static_data_File_descriptor.getNestedTypes().get(0);
    internal_static_data_File_MetaEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_data_File_MetaEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
