// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package eu.tsystems.mms.tic.testframework.report.model;

public interface HistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.History)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .data.HistoryAggregate entries = 1;</code>
   */
  java.util.List<eu.tsystems.mms.tic.testframework.report.model.HistoryAggregate> 
      getEntriesList();
  /**
   * <code>repeated .data.HistoryAggregate entries = 1;</code>
   */
  eu.tsystems.mms.tic.testframework.report.model.HistoryAggregate getEntries(int index);
  /**
   * <code>repeated .data.HistoryAggregate entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .data.HistoryAggregate entries = 1;</code>
   */
  java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.HistoryAggregateOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .data.HistoryAggregate entries = 1;</code>
   */
  eu.tsystems.mms.tic.testframework.report.model.HistoryAggregateOrBuilder getEntriesOrBuilder(
      int index);
}
