// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

/**
 * Protobuf type {@code data.LogMessage}
 */
public final class LogMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.LogMessage)
    LogMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LogMessage.newBuilder() to construct.
  private LogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LogMessage() {
    type_ = 0;
    loggerName_ = "";
    message_ = "";
    threadName_ = "";
    stackTrace_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LogMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LogMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            loggerName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 32: {

            timestamp_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            threadName_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              stackTrace_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.StackTraceCause>();
              mutable_bitField0_ |= 0x00000001;
            }
            stackTrace_.add(
                input.readMessage(eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.parser(), extensionRegistry));
            break;
          }
          case 56: {

            prompt_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        stackTrace_ = java.util.Collections.unmodifiableList(stackTrace_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_LogMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_LogMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.tsystems.mms.tic.testframework.report.model.LogMessage.class, eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.data.LogMessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.data.LogMessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public eu.tsystems.mms.tic.testframework.report.model.LogMessageType getType() {
    @SuppressWarnings("deprecation")
    eu.tsystems.mms.tic.testframework.report.model.LogMessageType result = eu.tsystems.mms.tic.testframework.report.model.LogMessageType.valueOf(type_);
    return result == null ? eu.tsystems.mms.tic.testframework.report.model.LogMessageType.UNRECOGNIZED : result;
  }

  public static final int LOGGER_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object loggerName_;
  /**
   * <code>string logger_name = 2;</code>
   * @return The loggerName.
   */
  @java.lang.Override
  public java.lang.String getLoggerName() {
    java.lang.Object ref = loggerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      loggerName_ = s;
      return s;
    }
  }
  /**
   * <code>string logger_name = 2;</code>
   * @return The bytes for loggerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLoggerNameBytes() {
    java.lang.Object ref = loggerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loggerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int THREAD_NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object threadName_;
  /**
   * <code>string thread_name = 5;</code>
   * @return The threadName.
   */
  @java.lang.Override
  public java.lang.String getThreadName() {
    java.lang.Object ref = threadName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      threadName_ = s;
      return s;
    }
  }
  /**
   * <code>string thread_name = 5;</code>
   * @return The bytes for threadName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreadNameBytes() {
    java.lang.Object ref = threadName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      threadName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STACK_TRACE_FIELD_NUMBER = 6;
  private java.util.List<eu.tsystems.mms.tic.testframework.report.model.StackTraceCause> stackTrace_;
  /**
   * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
   */
  @java.lang.Override
  public java.util.List<eu.tsystems.mms.tic.testframework.report.model.StackTraceCause> getStackTraceList() {
    return stackTrace_;
  }
  /**
   * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder> 
      getStackTraceOrBuilderList() {
    return stackTrace_;
  }
  /**
   * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
   */
  @java.lang.Override
  public int getStackTraceCount() {
    return stackTrace_.size();
  }
  /**
   * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getStackTrace(int index) {
    return stackTrace_.get(index);
  }
  /**
   * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
   */
  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder getStackTraceOrBuilder(
      int index) {
    return stackTrace_.get(index);
  }

  public static final int PROMPT_FIELD_NUMBER = 7;
  private boolean prompt_;
  /**
   * <code>bool prompt = 7;</code>
   * @return The prompt.
   */
  @java.lang.Override
  public boolean getPrompt() {
    return prompt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != eu.tsystems.mms.tic.testframework.report.model.LogMessageType.LMT_OFF.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!getLoggerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loggerName_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(4, timestamp_);
    }
    if (!getThreadNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, threadName_);
    }
    for (int i = 0; i < stackTrace_.size(); i++) {
      output.writeMessage(6, stackTrace_.get(i));
    }
    if (prompt_ != false) {
      output.writeBool(7, prompt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != eu.tsystems.mms.tic.testframework.report.model.LogMessageType.LMT_OFF.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!getLoggerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loggerName_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, timestamp_);
    }
    if (!getThreadNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, threadName_);
    }
    for (int i = 0; i < stackTrace_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, stackTrace_.get(i));
    }
    if (prompt_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, prompt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.tsystems.mms.tic.testframework.report.model.LogMessage)) {
      return super.equals(obj);
    }
    eu.tsystems.mms.tic.testframework.report.model.LogMessage other = (eu.tsystems.mms.tic.testframework.report.model.LogMessage) obj;

    if (type_ != other.type_) return false;
    if (!getLoggerName()
        .equals(other.getLoggerName())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getThreadName()
        .equals(other.getThreadName())) return false;
    if (!getStackTraceList()
        .equals(other.getStackTraceList())) return false;
    if (getPrompt()
        != other.getPrompt()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + LOGGER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getLoggerName().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + THREAD_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getThreadName().hashCode();
    if (getStackTraceCount() > 0) {
      hash = (37 * hash) + STACK_TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getStackTraceList().hashCode();
    }
    hash = (37 * hash) + PROMPT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPrompt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.tsystems.mms.tic.testframework.report.model.LogMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code data.LogMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.LogMessage)
      eu.tsystems.mms.tic.testframework.report.model.LogMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_LogMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.tsystems.mms.tic.testframework.report.model.LogMessage.class, eu.tsystems.mms.tic.testframework.report.model.LogMessage.Builder.class);
    }

    // Construct using eu.tsystems.mms.tic.testframework.report.model.LogMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStackTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      loggerName_ = "";

      message_ = "";

      timestamp_ = 0L;

      threadName_ = "";

      if (stackTraceBuilder_ == null) {
        stackTrace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        stackTraceBuilder_.clear();
      }
      prompt_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_LogMessage_descriptor;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.LogMessage getDefaultInstanceForType() {
      return eu.tsystems.mms.tic.testframework.report.model.LogMessage.getDefaultInstance();
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.LogMessage build() {
      eu.tsystems.mms.tic.testframework.report.model.LogMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.LogMessage buildPartial() {
      eu.tsystems.mms.tic.testframework.report.model.LogMessage result = new eu.tsystems.mms.tic.testframework.report.model.LogMessage(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.loggerName_ = loggerName_;
      result.message_ = message_;
      result.timestamp_ = timestamp_;
      result.threadName_ = threadName_;
      if (stackTraceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          stackTrace_ = java.util.Collections.unmodifiableList(stackTrace_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.stackTrace_ = stackTrace_;
      } else {
        result.stackTrace_ = stackTraceBuilder_.build();
      }
      result.prompt_ = prompt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.tsystems.mms.tic.testframework.report.model.LogMessage) {
        return mergeFrom((eu.tsystems.mms.tic.testframework.report.model.LogMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.tsystems.mms.tic.testframework.report.model.LogMessage other) {
      if (other == eu.tsystems.mms.tic.testframework.report.model.LogMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getLoggerName().isEmpty()) {
        loggerName_ = other.loggerName_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getThreadName().isEmpty()) {
        threadName_ = other.threadName_;
        onChanged();
      }
      if (stackTraceBuilder_ == null) {
        if (!other.stackTrace_.isEmpty()) {
          if (stackTrace_.isEmpty()) {
            stackTrace_ = other.stackTrace_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStackTraceIsMutable();
            stackTrace_.addAll(other.stackTrace_);
          }
          onChanged();
        }
      } else {
        if (!other.stackTrace_.isEmpty()) {
          if (stackTraceBuilder_.isEmpty()) {
            stackTraceBuilder_.dispose();
            stackTraceBuilder_ = null;
            stackTrace_ = other.stackTrace_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stackTraceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStackTraceFieldBuilder() : null;
          } else {
            stackTraceBuilder_.addAllMessages(other.stackTrace_);
          }
        }
      }
      if (other.getPrompt() != false) {
        setPrompt(other.getPrompt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.tsystems.mms.tic.testframework.report.model.LogMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.tsystems.mms.tic.testframework.report.model.LogMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.data.LogMessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.data.LogMessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.data.LogMessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.LogMessageType getType() {
      @SuppressWarnings("deprecation")
      eu.tsystems.mms.tic.testframework.report.model.LogMessageType result = eu.tsystems.mms.tic.testframework.report.model.LogMessageType.valueOf(type_);
      return result == null ? eu.tsystems.mms.tic.testframework.report.model.LogMessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.data.LogMessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(eu.tsystems.mms.tic.testframework.report.model.LogMessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.data.LogMessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object loggerName_ = "";
    /**
     * <code>string logger_name = 2;</code>
     * @return The loggerName.
     */
    public java.lang.String getLoggerName() {
      java.lang.Object ref = loggerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loggerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string logger_name = 2;</code>
     * @return The bytes for loggerName.
     */
    public com.google.protobuf.ByteString
        getLoggerNameBytes() {
      java.lang.Object ref = loggerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loggerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string logger_name = 2;</code>
     * @param value The loggerName to set.
     * @return This builder for chaining.
     */
    public Builder setLoggerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      loggerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string logger_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoggerName() {
      
      loggerName_ = getDefaultInstance().getLoggerName();
      onChanged();
      return this;
    }
    /**
     * <code>string logger_name = 2;</code>
     * @param value The bytes for loggerName to set.
     * @return This builder for chaining.
     */
    public Builder setLoggerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      loggerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object threadName_ = "";
    /**
     * <code>string thread_name = 5;</code>
     * @return The threadName.
     */
    public java.lang.String getThreadName() {
      java.lang.Object ref = threadName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        threadName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string thread_name = 5;</code>
     * @return The bytes for threadName.
     */
    public com.google.protobuf.ByteString
        getThreadNameBytes() {
      java.lang.Object ref = threadName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string thread_name = 5;</code>
     * @param value The threadName to set.
     * @return This builder for chaining.
     */
    public Builder setThreadName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      threadName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string thread_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadName() {
      
      threadName_ = getDefaultInstance().getThreadName();
      onChanged();
      return this;
    }
    /**
     * <code>string thread_name = 5;</code>
     * @param value The bytes for threadName to set.
     * @return This builder for chaining.
     */
    public Builder setThreadNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      threadName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<eu.tsystems.mms.tic.testframework.report.model.StackTraceCause> stackTrace_ =
      java.util.Collections.emptyList();
    private void ensureStackTraceIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        stackTrace_ = new java.util.ArrayList<eu.tsystems.mms.tic.testframework.report.model.StackTraceCause>(stackTrace_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.StackTraceCause, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder, eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder> stackTraceBuilder_;

    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.StackTraceCause> getStackTraceList() {
      if (stackTraceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stackTrace_);
      } else {
        return stackTraceBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public int getStackTraceCount() {
      if (stackTraceBuilder_ == null) {
        return stackTrace_.size();
      } else {
        return stackTraceBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getStackTrace(int index) {
      if (stackTraceBuilder_ == null) {
        return stackTrace_.get(index);
      } else {
        return stackTraceBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder setStackTrace(
        int index, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause value) {
      if (stackTraceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStackTraceIsMutable();
        stackTrace_.set(index, value);
        onChanged();
      } else {
        stackTraceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder setStackTrace(
        int index, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder builderForValue) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.set(index, builderForValue.build());
        onChanged();
      } else {
        stackTraceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder addStackTrace(eu.tsystems.mms.tic.testframework.report.model.StackTraceCause value) {
      if (stackTraceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStackTraceIsMutable();
        stackTrace_.add(value);
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder addStackTrace(
        int index, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause value) {
      if (stackTraceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStackTraceIsMutable();
        stackTrace_.add(index, value);
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder addStackTrace(
        eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder builderForValue) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.add(builderForValue.build());
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder addStackTrace(
        int index, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder builderForValue) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.add(index, builderForValue.build());
        onChanged();
      } else {
        stackTraceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder addAllStackTrace(
        java.lang.Iterable<? extends eu.tsystems.mms.tic.testframework.report.model.StackTraceCause> values) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stackTrace_);
        onChanged();
      } else {
        stackTraceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder clearStackTrace() {
      if (stackTraceBuilder_ == null) {
        stackTrace_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stackTraceBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public Builder removeStackTrace(int index) {
      if (stackTraceBuilder_ == null) {
        ensureStackTraceIsMutable();
        stackTrace_.remove(index);
        onChanged();
      } else {
        stackTraceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder getStackTraceBuilder(
        int index) {
      return getStackTraceFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder getStackTraceOrBuilder(
        int index) {
      if (stackTraceBuilder_ == null) {
        return stackTrace_.get(index);  } else {
        return stackTraceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public java.util.List<? extends eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder> 
         getStackTraceOrBuilderList() {
      if (stackTraceBuilder_ != null) {
        return stackTraceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stackTrace_);
      }
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder addStackTraceBuilder() {
      return getStackTraceFieldBuilder().addBuilder(
          eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.getDefaultInstance());
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder addStackTraceBuilder(
        int index) {
      return getStackTraceFieldBuilder().addBuilder(
          index, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.getDefaultInstance());
    }
    /**
     * <code>repeated .data.StackTraceCause stack_trace = 6;</code>
     */
    public java.util.List<eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder> 
         getStackTraceBuilderList() {
      return getStackTraceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.StackTraceCause, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder, eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder> 
        getStackTraceFieldBuilder() {
      if (stackTraceBuilder_ == null) {
        stackTraceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.StackTraceCause, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder, eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder>(
                stackTrace_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        stackTrace_ = null;
      }
      return stackTraceBuilder_;
    }

    private boolean prompt_ ;
    /**
     * <code>bool prompt = 7;</code>
     * @return The prompt.
     */
    @java.lang.Override
    public boolean getPrompt() {
      return prompt_;
    }
    /**
     * <code>bool prompt = 7;</code>
     * @param value The prompt to set.
     * @return This builder for chaining.
     */
    public Builder setPrompt(boolean value) {
      
      prompt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool prompt = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrompt() {
      
      prompt_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.LogMessage)
  }

  // @@protoc_insertion_point(class_scope:data.LogMessage)
  private static final eu.tsystems.mms.tic.testframework.report.model.LogMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.tsystems.mms.tic.testframework.report.model.LogMessage();
  }

  public static eu.tsystems.mms.tic.testframework.report.model.LogMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogMessage>
      PARSER = new com.google.protobuf.AbstractParser<LogMessage>() {
    @java.lang.Override
    public LogMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LogMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LogMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.LogMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

