// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

public interface LogMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.LogMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.data.LogMessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.data.LogMessageType type = 1;</code>
   * @return The type.
   */
  eu.tsystems.mms.tic.testframework.report.model.LogMessageType getType();

  /**
   * <code>string logger_name = 2;</code>
   * @return The loggerName.
   */
  java.lang.String getLoggerName();
  /**
   * <code>string logger_name = 2;</code>
   * @return The bytes for loggerName.
   */
  com.google.protobuf.ByteString
      getLoggerNameBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string thread_name = 5;</code>
   * @return The threadName.
   */
  java.lang.String getThreadName();
  /**
   * <code>string thread_name = 5;</code>
   * @return The bytes for threadName.
   */
  com.google.protobuf.ByteString
      getThreadNameBytes();

  /**
   * <code>.data.StackTraceCause cause = 6;</code>
   * @return Whether the cause field is set.
   */
  boolean hasCause();
  /**
   * <code>.data.StackTraceCause cause = 6;</code>
   * @return The cause.
   */
  eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getCause();
  /**
   * <code>.data.StackTraceCause cause = 6;</code>
   */
  eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder getCauseOrBuilder();
}
