// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

public interface StackTraceCauseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.StackTraceCause)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string class_name = 1;</code>
   * @return The className.
   */
  java.lang.String getClassName();
  /**
   * <code>string class_name = 1;</code>
   * @return The bytes for className.
   */
  com.google.protobuf.ByteString
      getClassNameBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *    StackTraceCause cause = 4 [deprecated = true];
   * </pre>
   *
   * <code>repeated string stack_trace_elements = 3;</code>
   * @return A list containing the stackTraceElements.
   */
  java.util.List<java.lang.String>
      getStackTraceElementsList();
  /**
   * <pre>
   *    StackTraceCause cause = 4 [deprecated = true];
   * </pre>
   *
   * <code>repeated string stack_trace_elements = 3;</code>
   * @return The count of stackTraceElements.
   */
  int getStackTraceElementsCount();
  /**
   * <pre>
   *    StackTraceCause cause = 4 [deprecated = true];
   * </pre>
   *
   * <code>repeated string stack_trace_elements = 3;</code>
   * @param index The index of the element to return.
   * @return The stackTraceElements at the given index.
   */
  java.lang.String getStackTraceElements(int index);
  /**
   * <pre>
   *    StackTraceCause cause = 4 [deprecated = true];
   * </pre>
   *
   * <code>repeated string stack_trace_elements = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stackTraceElements at the given index.
   */
  com.google.protobuf.ByteString
      getStackTraceElementsBytes(int index);
}
