// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

/**
 * Protobuf type {@code data.StackTraceCause}
 */
public  final class StackTraceCause extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:data.StackTraceCause)
    StackTraceCauseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StackTraceCause.newBuilder() to construct.
  private StackTraceCause(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StackTraceCause() {
    className_ = "";
    message_ = "";
    stackTraceElements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StackTraceCause();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StackTraceCause(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            className_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              stackTraceElements_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            stackTraceElements_.add(s);
            break;
          }
          case 34: {
            eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder subBuilder = null;
            if (cause_ != null) {
              subBuilder = cause_.toBuilder();
            }
            cause_ = input.readMessage(eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cause_);
              cause_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        stackTraceElements_ = stackTraceElements_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_StackTraceCause_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_StackTraceCause_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.class, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder.class);
  }

  public static final int CLASS_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object className_;
  /**
   * <code>string class_name = 1;</code>
   * @return The className.
   */
  public java.lang.String getClassName() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      className_ = s;
      return s;
    }
  }
  /**
   * <code>string class_name = 1;</code>
   * @return The bytes for className.
   */
  public com.google.protobuf.ByteString
      getClassNameBytes() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      className_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STACK_TRACE_ELEMENTS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList stackTraceElements_;
  /**
   * <code>repeated string stack_trace_elements = 3;</code>
   * @return A list containing the stackTraceElements.
   */
  public com.google.protobuf.ProtocolStringList
      getStackTraceElementsList() {
    return stackTraceElements_;
  }
  /**
   * <code>repeated string stack_trace_elements = 3;</code>
   * @return The count of stackTraceElements.
   */
  public int getStackTraceElementsCount() {
    return stackTraceElements_.size();
  }
  /**
   * <code>repeated string stack_trace_elements = 3;</code>
   * @param index The index of the element to return.
   * @return The stackTraceElements at the given index.
   */
  public java.lang.String getStackTraceElements(int index) {
    return stackTraceElements_.get(index);
  }
  /**
   * <code>repeated string stack_trace_elements = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the stackTraceElements at the given index.
   */
  public com.google.protobuf.ByteString
      getStackTraceElementsBytes(int index) {
    return stackTraceElements_.getByteString(index);
  }

  public static final int CAUSE_FIELD_NUMBER = 4;
  private eu.tsystems.mms.tic.testframework.report.model.StackTraceCause cause_;
  /**
   * <code>.data.StackTraceCause cause = 4;</code>
   * @return Whether the cause field is set.
   */
  public boolean hasCause() {
    return cause_ != null;
  }
  /**
   * <code>.data.StackTraceCause cause = 4;</code>
   * @return The cause.
   */
  public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getCause() {
    return cause_ == null ? eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.getDefaultInstance() : cause_;
  }
  /**
   * <code>.data.StackTraceCause cause = 4;</code>
   */
  public eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder getCauseOrBuilder() {
    return getCause();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClassNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, className_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < stackTraceElements_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stackTraceElements_.getRaw(i));
    }
    if (cause_ != null) {
      output.writeMessage(4, getCause());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClassNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, className_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < stackTraceElements_.size(); i++) {
        dataSize += computeStringSizeNoTag(stackTraceElements_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getStackTraceElementsList().size();
    }
    if (cause_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCause());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof eu.tsystems.mms.tic.testframework.report.model.StackTraceCause)) {
      return super.equals(obj);
    }
    eu.tsystems.mms.tic.testframework.report.model.StackTraceCause other = (eu.tsystems.mms.tic.testframework.report.model.StackTraceCause) obj;

    if (!getClassName()
        .equals(other.getClassName())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getStackTraceElementsList()
        .equals(other.getStackTraceElementsList())) return false;
    if (hasCause() != other.hasCause()) return false;
    if (hasCause()) {
      if (!getCause()
          .equals(other.getCause())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLASS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getClassName().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getStackTraceElementsCount() > 0) {
      hash = (37 * hash) + STACK_TRACE_ELEMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getStackTraceElementsList().hashCode();
    }
    if (hasCause()) {
      hash = (37 * hash) + CAUSE_FIELD_NUMBER;
      hash = (53 * hash) + getCause().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(eu.tsystems.mms.tic.testframework.report.model.StackTraceCause prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code data.StackTraceCause}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:data.StackTraceCause)
      eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_StackTraceCause_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_StackTraceCause_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.class, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder.class);
    }

    // Construct using eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      className_ = "";

      message_ = "";

      stackTraceElements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (causeBuilder_ == null) {
        cause_ = null;
      } else {
        cause_ = null;
        causeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return eu.tsystems.mms.tic.testframework.report.model.Framework.internal_static_data_StackTraceCause_descriptor;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getDefaultInstanceForType() {
      return eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.getDefaultInstance();
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause build() {
      eu.tsystems.mms.tic.testframework.report.model.StackTraceCause result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause buildPartial() {
      eu.tsystems.mms.tic.testframework.report.model.StackTraceCause result = new eu.tsystems.mms.tic.testframework.report.model.StackTraceCause(this);
      int from_bitField0_ = bitField0_;
      result.className_ = className_;
      result.message_ = message_;
      if (((bitField0_ & 0x00000001) != 0)) {
        stackTraceElements_ = stackTraceElements_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.stackTraceElements_ = stackTraceElements_;
      if (causeBuilder_ == null) {
        result.cause_ = cause_;
      } else {
        result.cause_ = causeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof eu.tsystems.mms.tic.testframework.report.model.StackTraceCause) {
        return mergeFrom((eu.tsystems.mms.tic.testframework.report.model.StackTraceCause)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(eu.tsystems.mms.tic.testframework.report.model.StackTraceCause other) {
      if (other == eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.getDefaultInstance()) return this;
      if (!other.getClassName().isEmpty()) {
        className_ = other.className_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.stackTraceElements_.isEmpty()) {
        if (stackTraceElements_.isEmpty()) {
          stackTraceElements_ = other.stackTraceElements_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureStackTraceElementsIsMutable();
          stackTraceElements_.addAll(other.stackTraceElements_);
        }
        onChanged();
      }
      if (other.hasCause()) {
        mergeCause(other.getCause());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      eu.tsystems.mms.tic.testframework.report.model.StackTraceCause parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (eu.tsystems.mms.tic.testframework.report.model.StackTraceCause) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object className_ = "";
    /**
     * <code>string class_name = 1;</code>
     * @return The className.
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string class_name = 1;</code>
     * @return The bytes for className.
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string class_name = 1;</code>
     * @param value The className to set.
     * @return This builder for chaining.
     */
    public Builder setClassName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      className_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string class_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassName() {
      
      className_ = getDefaultInstance().getClassName();
      onChanged();
      return this;
    }
    /**
     * <code>string class_name = 1;</code>
     * @param value The bytes for className to set.
     * @return This builder for chaining.
     */
    public Builder setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      className_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList stackTraceElements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureStackTraceElementsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        stackTraceElements_ = new com.google.protobuf.LazyStringArrayList(stackTraceElements_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @return A list containing the stackTraceElements.
     */
    public com.google.protobuf.ProtocolStringList
        getStackTraceElementsList() {
      return stackTraceElements_.getUnmodifiableView();
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @return The count of stackTraceElements.
     */
    public int getStackTraceElementsCount() {
      return stackTraceElements_.size();
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @param index The index of the element to return.
     * @return The stackTraceElements at the given index.
     */
    public java.lang.String getStackTraceElements(int index) {
      return stackTraceElements_.get(index);
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the stackTraceElements at the given index.
     */
    public com.google.protobuf.ByteString
        getStackTraceElementsBytes(int index) {
      return stackTraceElements_.getByteString(index);
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @param index The index to set the value at.
     * @param value The stackTraceElements to set.
     * @return This builder for chaining.
     */
    public Builder setStackTraceElements(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStackTraceElementsIsMutable();
      stackTraceElements_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @param value The stackTraceElements to add.
     * @return This builder for chaining.
     */
    public Builder addStackTraceElements(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureStackTraceElementsIsMutable();
      stackTraceElements_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @param values The stackTraceElements to add.
     * @return This builder for chaining.
     */
    public Builder addAllStackTraceElements(
        java.lang.Iterable<java.lang.String> values) {
      ensureStackTraceElementsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, stackTraceElements_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStackTraceElements() {
      stackTraceElements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string stack_trace_elements = 3;</code>
     * @param value The bytes of the stackTraceElements to add.
     * @return This builder for chaining.
     */
    public Builder addStackTraceElementsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureStackTraceElementsIsMutable();
      stackTraceElements_.add(value);
      onChanged();
      return this;
    }

    private eu.tsystems.mms.tic.testframework.report.model.StackTraceCause cause_;
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.StackTraceCause, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder, eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder> causeBuilder_;
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     * @return Whether the cause field is set.
     */
    public boolean hasCause() {
      return causeBuilder_ != null || cause_ != null;
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     * @return The cause.
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getCause() {
      if (causeBuilder_ == null) {
        return cause_ == null ? eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.getDefaultInstance() : cause_;
      } else {
        return causeBuilder_.getMessage();
      }
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     */
    public Builder setCause(eu.tsystems.mms.tic.testframework.report.model.StackTraceCause value) {
      if (causeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cause_ = value;
        onChanged();
      } else {
        causeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     */
    public Builder setCause(
        eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder builderForValue) {
      if (causeBuilder_ == null) {
        cause_ = builderForValue.build();
        onChanged();
      } else {
        causeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     */
    public Builder mergeCause(eu.tsystems.mms.tic.testframework.report.model.StackTraceCause value) {
      if (causeBuilder_ == null) {
        if (cause_ != null) {
          cause_ =
            eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.newBuilder(cause_).mergeFrom(value).buildPartial();
        } else {
          cause_ = value;
        }
        onChanged();
      } else {
        causeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     */
    public Builder clearCause() {
      if (causeBuilder_ == null) {
        cause_ = null;
        onChanged();
      } else {
        cause_ = null;
        causeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder getCauseBuilder() {
      
      onChanged();
      return getCauseFieldBuilder().getBuilder();
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     */
    public eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder getCauseOrBuilder() {
      if (causeBuilder_ != null) {
        return causeBuilder_.getMessageOrBuilder();
      } else {
        return cause_ == null ?
            eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.getDefaultInstance() : cause_;
      }
    }
    /**
     * <code>.data.StackTraceCause cause = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        eu.tsystems.mms.tic.testframework.report.model.StackTraceCause, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder, eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder> 
        getCauseFieldBuilder() {
      if (causeBuilder_ == null) {
        causeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            eu.tsystems.mms.tic.testframework.report.model.StackTraceCause, eu.tsystems.mms.tic.testframework.report.model.StackTraceCause.Builder, eu.tsystems.mms.tic.testframework.report.model.StackTraceCauseOrBuilder>(
                getCause(),
                getParentForChildren(),
                isClean());
        cause_ = null;
      }
      return causeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:data.StackTraceCause)
  }

  // @@protoc_insertion_point(class_scope:data.StackTraceCause)
  private static final eu.tsystems.mms.tic.testframework.report.model.StackTraceCause DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new eu.tsystems.mms.tic.testframework.report.model.StackTraceCause();
  }

  public static eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StackTraceCause>
      PARSER = new com.google.protobuf.AbstractParser<StackTraceCause>() {
    @java.lang.Override
    public StackTraceCause parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StackTraceCause(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StackTraceCause> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StackTraceCause> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public eu.tsystems.mms.tic.testframework.report.model.StackTraceCause getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

