// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: framework.proto

package eu.tsystems.mms.tic.testframework.report.model;

public interface SuiteContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.SuiteContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.data.ContextValues context_values = 1;</code>
   * @return Whether the contextValues field is set.
   */
  boolean hasContextValues();
  /**
   * <code>.data.ContextValues context_values = 1;</code>
   * @return The contextValues.
   */
  eu.tsystems.mms.tic.testframework.report.model.ContextValues getContextValues();
  /**
   * <code>.data.ContextValues context_values = 1;</code>
   */
  eu.tsystems.mms.tic.testframework.report.model.ContextValuesOrBuilder getContextValuesOrBuilder();

  /**
   * <pre>
   *repeated string test_context_ids = 6 [deprecated = true]; // list of all test
   * </pre>
   *
   * <code>string execution_context_id = 7;</code>
   * @return The executionContextId.
   */
  java.lang.String getExecutionContextId();
  /**
   * <pre>
   *repeated string test_context_ids = 6 [deprecated = true]; // list of all test
   * </pre>
   *
   * <code>string execution_context_id = 7;</code>
   * @return The bytes for executionContextId.
   */
  com.google.protobuf.ByteString
      getExecutionContextIdBytes();
}
