= Events and Listeners

Testerra provides a Google Guava event bus with custom events for test execution. The following events are currently implemented:

|===
|Event |Description

| `MethodStartEvent`
|Called on start of every test method annotated by TestNG `@Test` annotation.


|`MethodEndEvent`
|Called at the end of every test method annotated by TestNG `@Test` annotation. This can be used to send test results to a test management system or issue tracker.


//|TEST_START
//|Called on start of every test method annotated by TestNG `@Test` annotation and every test configuration method annotated by TestNG `@BeforeMethod` or similar, but before the execution of registered <<Before Method Worker>>
//|TIMESTAMP+
//ITestResult +
//IInvokedMethod

| `ExecutionFinishEvent`
|Called at the end of test run to trigger report generation and other output worker.


|`ExecutionAbortEvent`
|Called on test run abortion due to unclear circumstances like hanging sessions, JVM exit or other.


|`InterceptMethodsEvent`
|Called before suite execution. The events methods list provides a list of tests to execute. Read more about this in <<Intercept test method execution>>



//|FIRST_FAILED_TEST
//|Called on the first failing test of your test run.
//|TIMESTAMP +
//METHOD_NAME +
//ITestResult +
//IInvokedMethod
//
//|TEST_WITH_FILTERED_THROWABLE
//|Called on every failed test method when Testerra `RetryAnalyzer`found a cause to retry the test.
//|TIMESTAMP +
//METHOD_NAME +
//ITestResult +
//IInvokedMethod

|`ContextUpdateEvent`
|Called every time the internal context data has been changed significantly. This can be used to synchronize the internal test context model.

|===

== Create custom event listeners

The simplest way to get in touch with the event bus is to write and register your own implementation of the event's `Listener` interface and add the `@Subscribe` annotation.

.Simple LogEventListener
[source,java]
----
import com.google.common.eventbus.Subscribe;
import eu.tsystems.mms.tic.testframework.events.MethodStartEvent;
import eu.tsystems.mms.tic.testframework.logging.Loggable;

public class LogEventListener implements MethodStartEvent.Listener, Loggable {

    @Override
    @Subscribe
    public void onMethodStart(MethodStartEvent event) {
        log().info("Event logged: " + event.getMethod());
    }
}
----

If you want to react to some more events, you can just implement multiple interfaces.

== Register custom event listener

After you defined your first custom listener you now have to register it to the `TesterraListener`.

.Registering your listener
[source,java]
----
TesterraListener.getEventBus().register(new LogEventListener());
----

== Fire events by yourself

While Implementing your own module you may reach a point, where you want to inform other components or modules about an important event.
You can achieve this by just posting this event to the bus.

For example, if your module changes some data in the underlying data model, you have to inform all other "participants"  about your change by firing an `ContextUpdateEvent` event.

[source,java]
----

// Update some data in data model...
methodContext.name = "new_Test_Method_Name";

TesterraListener.getEventBus().post(new ContextUpdateEvent().setContext(methodContext));
----

== Create custom event types

If you want to provide some custom events to other modules. You can implement these by implementing any kind of class for the event bus.

.Creating custom event types
[source,java]
----
public class CustomEvent {
    public interface Listener {
        void onCustomEvent(CustomEvent event);
    }
}
----

With your `CustomEvent` created, you now can fire these events or react to them in the way described in the sections <<Fire Events by yourself>> and <<Create Custom Event Listeners>>.

.CustomEvent Listener Example
[source,java]
----
@Override
@Subscribe
public void onCustomEvent(CustomEvent event) {
   log().info("Custom Event started!");
}
----

== Intercept test method execution

With the test `InterceptMethodsEvent`, you are able to modify the list of tests being executed before execution.

[source,java]
----
import eu.tsystems.mms.tic.testframework.events.InterceptMethodsEvent;

public class MyTest extends TesterraTest {

    public class MyListener implements InterceptMethodsEvent.Listener {

        @Override
        @Subscribe
        public void onInterceptMethods(InterceptMethodsEvent event) {
            event.getMethodInstances().removeIf(iMethodInstance -> true);
        }
    }

    @BeforeTest
    public void setupListener() {
        TesterraListener.getEventBus().register(new MyListener());
    }
}
----

== Listen to TestNG events

Since the `TesterraListener` listens to `TestNG` events, it also forwards some of these events the same way like any other events.

[source,java]
----
import eu.tsystems.mms.tic.testframework.logging.Loggable;
import com.google.common.eventbus.Subscribe;
import org.testng.ISuite;
import org.testng.ISuiteListener;

class MySuiteListener implements ISuiteListener, Loggable {

    @Subscribe
    @Override
    public void onStart(ISuite suite) {
        log().info("Suite started");
    }
}
----
