= Modules and Hooks

The interface `ModuleHook` of Testerra framework offers you methods for the runtime lifecycle with the `ModuleHook.init()` and `ModuleHook.terminate()` methods.

While the `init()` method is called on startup of Testerra as one of the earliest steps, you are able to make your customizations as soon as possible and you are able to register to all <<Events and Listener>> of Testerra framework as well.

The `terminate()` method of your custom module hook is called at the most latest point for Testerra right before terminating the execution.
You should use this method to cleanup your module, if necessary, for example closing database connections in a database module.

.Simple Testerra ModuleHook
[source,java]
----
import eu.tsystems.mms.tic.testframework.hooks.ModuleHook;

public class SimpleCustomHook implements ModuleHook {

    @Override
    public void init() {
        //
    }

    @Override
    public void terminate() {
        //
    }
}
----

To register your module hook, you need to create a module dependency injection configuration based on the Google Guice framework.

[source,java]
----
package eu.tsystems.mms.tic.testframework.ioc;

import com.google.inject.AbstractModule;
import com.google.inject.Scopes;
import com.google.inject.multibindings.Multibinder;

public class ConfigureMyModule extends AbstractModule {
    @Override
    protected void configure() {
        Multibinder<ModuleHook> hookBinder = Multibinder.newSetBinder(binder(), ModuleHook.class);
        hookBinder.addBinding().to(SimpleCustomHook.class).in(Scopes.SINGLETON);
    }
}
----

NOTE: Please be aware, that the package namespace is required in order to find your module configuration.
