= Modules and Hooks

To register your module hook, you need to create a module dependency injection configuration based on the Google Guice framework.

[source,java]
----
package eu.tsystems.mms.tic.testframework.ioc;

import com.google.inject.AbstractModule;
import com.google.inject.Scopes;
import com.google.inject.multibindings.Multibinder;

public class ConfigureMyModule extends AbstractModule implements ModuleHook {
    @Override
    protected void configure() {
        //
    }

    @Override
    public void init() {
        //
    }

    @Override
    public void terminate() {
        //
    }
}
----

IMPORTANT: Please be aware, that the package namespace prefix `eu.tsystems.mms.tic` is required in order to find your module configuration.

The `configure()` method is dependency injection configuration.

While the `init()` method is called on startup of Testerra as one of the earliest steps, you are able to make your customizations as soon as possible and you are able to register to all <<Events and Listeners>> of Testerra framework as well.

The `terminate()` method is called at the most latest point for Testerra right before terminating the execution.
You should use this method to cleanup your module, if necessary, for example closing database connections in a database module.

NOTE: All module configuration instances are loaded in an alphabetical order.
