= Modules

To register your module, you need to create a module injection configuration based on the Google Guice framework.

[source,java]
----
package eu.tsystems.mms.tic.mymodule;

import com.google.inject.AbstractModule;

public class ConfigureMyModule extends AbstractModule {
    @Override
    protected void configure() {
        // inject dependencies here
    }
}
----

IMPORTANT: Please be aware, that the package namespace prefix `eu.tsystems.mms.tic` is required in order to find your module configuration.

NOTE: All module configuration instances are loaded in alphabetical order.

= Hooks

When you need more module features, like registering to <<Events and Listeners, Events>> or perform setup and teardown functionality, you can implement the `ModuleHook` interface.

[source,java]
----
package eu.tsystems.mms.tic.mymodule;

import eu.tsystems.mms.tic.testframework.hooks.ModuleHook;

public class ConfigureMyModule extends AbstractModule implements ModuleHook {
    @Override
    public void init() {
        //
    }

    @Override
    public void terminate() {
        //
    }
}
----

While the `init()` method is called on startup of Testerra as one of the earliest steps, you are able to make your customizations as soon as possible.

The `terminate()` method is called at the most latest point for Testerra right before terminating the execution.
You should use this method to cleanup your module, if necessary, for example closing database connections in a database module.
