= Project extensions

include::../properties/property-attributes.adoc[]

== Using a proxy

There are three ways for setting up a proxy for your test run environment.

- System proxy settings for Gradle and the JVM
- Testerra proxy settings for TestNG and JVM
- Browser proxy settings for the SUT set up by browser capabilities you can find here <<Browser capabilities,Proxy setup>>

=== System proxy (recommended)

To setup a proxy for the whole system, including Gradle, the JVM and Testerra, the recommended way is to pass it by command line arguments like
[source]
----
gradle test -Dhttps.proxyHost=your-proxy-host.com -Dhttps.proxyPort=8080
----
IMPORTANT: Setting the System proxy will override the Testerra proxy settings.

=== Testerra proxy

If you want to setup a proxy for Testerra, including TestNG and the JVM, just add `proxysettings.properties` to your resource bundle at `src/test/resources` with the following content

For example Testerra requires this setting to connect to a Selenium grid, if you are in a corporate network.

.Example of proxysettings.properties
[source,properties]
----
https.proxyHost=your-proxy-host.com
https.proxyPort=8080
https.proxyUser=
https.proxyPassword=
https.nonProxyHosts=localhost|192.168.0.1
----
These properties are automatically loaded by the `PropertyManager` and set up as System proxy settings during runtime with the following message
----
[main] [INFO ]: common.TesterraCommons - Setting system property proxy = http://your-proxy-host.com:8080
----

IMPORTANT: Setting up the Testerra proxy will not setup a proxy for Gradle nor a browser.

== Logging
If you're on Gradle, the logging of Testerra should work out of the box. But if you're on Maven you MUST add the following SLF4J-dependency to your main `pom.xml`.

.pom.xml
[source, xml]
----
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-log4j12</artifactId>
    <version>1.8.0-beta2</version>
    <scope>test</scope>
</dependency>
----

=== Customize Logging
The `TesterraLogger` logs to `System.out` by default.
If you want to have more control over several log levels of classes, add a `log4j.xml` to your `resources/`.

.log4j.xml
[source, xml]
----
include::../../res/log4j.xml[]
----
