= Working with sessions

If you want to interact with your `WebDriver` session you can use the utilities provided by Testerra:

* WebDriverManagerUtils
* WebDriverUtils

== Working with cookies

If you want get and store the cookies of your current `WebDriver` session you can use `WebDriverUtils.getCookieString(WebDriver driver)`.
It will give you access to the complete cookie string, which you can use to open plain HTTP connections or make HTTP calls with your actual session cookies.

To delete all the cookies of your current `WebDriver` session just call `WebDriverManagerUtils.deleteAllCookies(WebDriver driver)`.

== Switching windows

Sometimes you will come across testing websites with multiple windows, such as popups or something similar.

[source,java]
----
// Switch to a window by matching title
WebDriver webDriver = WEB_DRIVER_MANAGER.switchToWindowTitle(WebDriver webDriver, String windowTitle);

// Switch to a window by a custom condition
Optional<WebDriver> optionalWebDriver = WEB_DRIVER_MANAGER.switchToWindow(WebDriver webDriver, webDriver -> webDriver.getCurrentUrl().contains("login"));

Assert.assertTrue(optionalWebDriver.isPresent(), "Login window not found");
----
