= Working with sessions

If you want to interact with your `WebDriver` session you can use the utilities provided by Testerra:

* WebDriverManagerUtils
* WebDriverUtils

== Get current session

.Get the current session context with information about your WebDriver session.
[source,java]
----
WebDriver driver = WebDriverManager.getWebDriver();
Optional<SessionContext> sessionContext = WebDriverSessionsManager.getSessionContext(driver);
----

== Working with cookies

.Get current cookies from driver.
[source,java]
----
WebDriver driver = WebDriverManager.getWebDriver();

// Get all cookies from driver
Set<Cookie> cookieSet = driver.manage().getCookies();

// Returns all cookies like "cookie1=value1;cookie2=value2;... as string
// You can use it to open plain HTTP connections or make HTTP calls with your actual session cookies.
String cookieString = WebDriverUtils.getCookieString(driver);
----

.Delete all cookies.
[source,java]
----
WebDriver driver = WebDriverManager.getWebDriver();
WebDriverUtils.deleteAllCookies(driver)
----

== Switching windows

Sometimes you will come across testing websites with multiple windows, such as popups or something similar.
To switch windows in a easy way Testerra provides some methods, which will automatically retry the window switching for maximum of seconds you can define with `{wdm_timeouts_window_switch}`.

[source,java]
----
// Switch to a window by matching title
Optional<WebDriver> optionalWebDriver = WebDriverUtils.switchToWindow(webDriver -> webDriver.getTitle().equals(windowTitle));

// Window context switched
optionalWebDriver.isPresent();
----

== Difference in session key and session id

There is a difference between session key and session id.
The session key is value that you can declare and provide to handle multiple web driver sessions in one test method, as you can read in section "Multiple sessions".
The session id is an internal id of Selenium itself.

[source,java]
----
WebDriver driver = WebDriverManager.getWebDriver("mySession");

// Returns generated UUID of the Selenium session
String sessionId = WebDriverUtils.getSessionId(driver);

// will be "mySession"
String sessionKey = WebDriverManagerUtils.getSessionKey(driver);
----
