= Retry analyzer
include::../properties/property-attributes.adoc[]

== Common
Testerra provides an adjustable mechanism to automatically retry failed tests.

The default retry count is `1`. Each failed method is executed exactly one more time.

You can change the default by the following property.

.test.properties
[source, properties, subs="attributes"]
----
{failed_tests_max_retries}=1
----

NOTE: The retry mechanism always ignores testcase with a valid Fails annotation.

== Specific retry count for test methods

You can change the retry count for specific test methods.

[source, java]
----
@Test()
@Retry(maxRetries = 2)
public void testMethod() {
    ...
}
----

== Specific retries

Testerra can also retry failed methods when matching certain criteria.
The filtering process contains of checks of classes and messages matching the thrown Exception, which are set within the test.properties file.

.test.properties
[source, properties, subs="attributes"]
----
# set additional classes that engage a retry,
# instances of TimeoutException are always retried
{failed_tests_if_throwable_classes}=java.sql.SQLRecoverableException

# set additional messages of Throwable that engage a retry,
# by default the following messages are evaluated
#           "Error communicating with the remote browser. It may have died",
#           "was terminated due to TIMEOUT",
#           "was terminated due to SO_TIMEOUT",
#           "The requested URL could not be retrieved",
#           "Squid is unable to create a TCP socket"

{failed_tests_if_throwable_messages}=failed to connect, error communicating with database
----

== Customize retry behaviour

For further adjustment additional analyzers can be registered expanding the default behaviour.

.Defining AdditionalRetryAnalyzer for `InstantiationException`
[source, java]
----
// custom Retryanalyzers need to implement the functional interface AdditionalRetryAnalyzer
public class InstantiationExceptionRetryAnalyzer implements AdditionalRetryAnalyzer {

    final String message = "failed instantiation";

    @Override
    public Throwable analyzeThrowable(Throwable throwable, String tMessage) {
        if (throwable instanceof InstantiationException) {
            if (tMessage != null) {
                final String tMessageLC = tMessage.toLowerCase();
                boolean match = tMessageLC.contains(message);
                if (match) {
                return throwable;
                }
            }
        }

        return null;
    }
}
----

.Register your retry analyzer
[source, java]
----
public class AbstractTest extends TesterraTest {

    static {
        // register the additional Analyzer,
        // which checks for "InstantiationException" and the message "failed instantiation"
        RetryAnalyzer.registerAdditionalRetryAnalyzer(new InstantiationExceptionRetryAnalyzer());
    }

}
----
