= Failure Corridor
include::../properties/property-attributes.adoc[]

This mechanism is used to define the test goal of test runs so that the test suite only fails with a broken failure corridor.

Testerra provides to kinds of a Failure corridor:

* Define a maximum number of allowed failed tests - _or_
* define for every test a weight (low, medium, high) and set specific number of allowed failed tests.

== General
The Failure corridor can be activated by the following property.

[source, properties, subs="attributes"]
----
{failure_corridor_active}=true
# default is false
----

== Maximum allowed failures
The simplest variant is to define the maximum number of allowed test failures.

.test.properties
[source, properties, subs="attributes"]
----
{failure_corridor_allowed_failed_tests}=2
# Ff less than two methods fail the suite will be marked as passed
----

== Custom failure corridor
For further adjustment test methods can be weighted while defining the maximum number of failures for the corresponding weightings.

.Examples of method weighting
[source, java]
----
// This testcase is marked with a high weight.
@FailureCorridor.High
@Test
public void test1() throws Exception {
    Assert.fail();
}

// This testcase is not marked, but the default weight is high.
@Test
public void test2() throws Exception {
    Assert.fail();
}

// This testcase is marked with a middle weight.
@FailureCorridor.Mid
@Test
public void test3() throws Exception {
    Assert.fail();
}

// This testcase is additional marked with @Fails.
// So the test result is ignored by the Failure corridor.
@Fails
@FailureCorridor.Mid
@Test
public void test4() throws Exception {
    Assert.fail();
}

// This testcase is marked with a low weight.
@FailureCorridor.Low
@Test
public void test5() throws Exception {
    Assert.fail();
}
----

Define your own failure corridor with the maximum number of failed tests by the following settings:

.test.properties
[source, properties, subs="attributes"]
----
{failure_corridor_allowed_failed_tests_high}=0
{failure_corridor_allowed_failed_tests_mid}=1
{failure_corridor_allowed_failed_tests_low}=2
----

[IMPORTANT]
====
If you do not define any failure corridor, but activate them, Testerra uses the default value `-1`.

In that case the custom failure corridor is used with `HIGH=-1, MID=-1, LOW=-1`.
====
