= Timer Utilities

The timer utilities provide some useful time related classes.

== Sleepy interface

The `Sleepy` interface provides for proper sleep logging.

[source,java]
----
import eu.tsystems.mms.tic.testframework.utils.Sleepy;

class MyWorkflow implements Sleepy {
    public void doSomething() {
        sleep();        // Sleeps for an internal default timeout
        sleep(long);    // Sleeps for milliseconds
    }
}
----

This will log something like

[source]
----
MyWorkflow - sleep(200ms) on MyWorkflow@62b635fe
----

== TimerUtils

If you want to pause your current test execution, because you may have to wait for something or need a hard timeout you can use the `TimerUtils`.

[source,java]
----
// Will pause current thread for 1 second.
TimerUtils.sleep(1000);

// You can pass a comment as well
TimerUtils.sleep(5000, "Wait for something to happen.");
----

Both of these methods calls of `sleep()` will produce a log message.
If you want to sleep without a message, `TimerUtils` of Testerra provides a method `sleepSilent()`.

== Timer (*deprecated*)

NOTE: Timings can be controlled using <<Test controlling,TestController>>, therefore this class is marked as `@deprecated` and should not be used anymore.

The `Timer` provides a basic timer feature, if you have to execute the same snippet of code in a defined interval. It stops after timeout or your sequence code was executed without any exceptions. If your sequence code was not successful the `Timer` will occur a `TimeoutException`.

.Simple timer sequence
[source,java]
----
final Timer timer = new Timer(500, 15_000);
timer.executeSequence(new Timer.Sequence<Boolean>() {
    @Override
    public void run() throws Throwable {
        // sequence code here
    }
});
----

[NOTE]
====
With this approach you will block your current thread, mostly your main thread.

If you want to execute your `Sequence` in another thread - we got you.
Just use the `executeSequenceThread` method.
====

You can also return an object. In that case no `TimeoutException` will occur. Therefor you have to verify your returning object.

[source,java]
----

public MyObject runTimer() {
    final Timer timer = new Timer(500, 15_000);
    ThrowablePackedResponse<MyObject> myObjectResponse = timer.executeSequenceThread(new Timer.Sequence<Boolean>() {
        @Override
        public void run() throws Throwable {
            // sequence code here
            setPassState(boolean);  // exit the sequence if your condition is true before timeout
            setReturningObject(new MyObject());

        }
    });
    return myObjectResponse.getResponse();
}
----
